src/main/java/com/gg/server/global/security/info/OAuthUserInfo.java
src/main/java/com/gg/server/global/security/info/OAuthUserInfoFactory.java
src/main/java/com/gg/server/global/security/info/ProviderType.java
src/main/java/com/gg/server/global/security/info/impl/FortyTwoOAuthUserInfo.java
src/main/java/com/gg/server/global/security/info/impl/KakaoOAuthUserInfo.java
src/main/java/com/gg/server/global/security/service/CustomOAuth2UserService.java

Ggbe 3 kakao o auth 카카오 로그인

---

.gitignore
src/main/java/com/gg/server/domain/user/UserRepository.java
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/dto/UserNormalDetailResponseDto.java
src/main/java/com/gg/server/domain/user/dto/UserSearchResponseDto.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/main/java/com/gg/server/global/config/WebConfig.java
src/main/java/com/gg/server/global/security/jwt/utils/AuthTokenProvider.java
src/main/java/com/gg/server/global/utils/AsyncNewUserImageUploader.java
src/main/java/com/gg/server/global/utils/argumentresolver/Login.java
src/main/java/com/gg/server/global/utils/argumentresolver/LoginMemberArgumentResolver.java

- user 기본정보 조회 /pingpong/users 작성 완료
- @Login 어노테이션 추가 , controller단에서 @Login User user 같이 User타입 앞에 @Login 어노테이션 붙이면 현재 로그인된 사용자 불러옴
-

GGBE-17 user 기본정보 조회 api 완료

---

src/main/java/com/gg/server/domain/announcement/Announcement.java
src/main/java/com/gg/server/domain/feedback/Feedback.java
src/main/java/com/gg/server/domain/game/Game.java
src/main/java/com/gg/server/domain/noti/Noti.java
src/main/java/com/gg/server/domain/pchange/PChange.java
src/main/java/com/gg/server/domain/rank/Rank.java
src/main/java/com/gg/server/domain/season/Season.java
src/main/java/com/gg/server/domain/slotmanagement/SlotManagement.java
src/main/java/com/gg/server/domain/team/Team.java
src/main/java/com/gg/server/domain/teamuser/TeamUser.java
src/main/java/com/gg/server/domain/user/User.java
src/main/java/com/gg/server/global/types/FeedbackType.java
src/main/java/com/gg/server/global/types/Mode.java
src/main/java/com/gg/server/global/types/NotiType.java
src/main/java/com/gg/server/global/types/StatusType.java

Ggbe 49 make entitiy

---

build.gradle
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/global/config/SwaggerConfig.java
src/main/java/com/gg/server/global/security/config/SecurityConfig.java

- api 확인과 프론트와의 소통을 위해 Spring doc 을 추가했습니다.
- 필요하다면 api 설명과 파라미터 설명을 적어주세요
- http://localhost:8080/oauth2/authorization/42 해당 경로로 로그인 후 개발자도구에 있는 access token을 가지고 authorize 하면 됩니다
- http://localhost:8080/api-docs
- @Login 으로 가져오는 User 객체는 swagger annotation의 @parameter(hidden = true) 어노테이션을 추가하면 스웨거 문서에서 보여지지 않습니다.

[feat] GGBE-43 swagger 추가

---

src/main/java/com/gg/server/domain/noti/controller/NotiController.java
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/main/java/com/gg/server/global/utils/argumentresolver/LoginMemberArgumentResolver.java
src/test/java/com/gg/server/utils/TestDataUtils.java

GGBE-17 @Login UserDto로 사용하도록 수정

---

src/main/java/com/gg/server/domain/user/dto/UserSearchResponseDto.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

GGBE-17 api 3개 테스트 코드 완료

---

build.gradle
src/main/java/com/gg/server/domain/season/SeasonController.java
src/main/java/com/gg/server/domain/season/SeasonService.java
src/main/java/com/gg/server/domain/season/dto/SeasonListResDto.java
src/main/java/com/gg/server/domain/season/dto/SeasonResDto.java
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/test/java/com/gg/server/season/SeasonTestController.java

- /pingpong/seasons API 완성
- 전체 시즌 목록을 {id, name} 형태의 리스트로 가져오는 api 입니다.
- 
- 기존 api에서 시즌마다 존재하는 mode를 하나만 리스트와 함께 보내주던 부분을 삭제했습니다.

GGBE-15 시즌 조회

---

src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/global/exception/ErrorCode.java
src/main/java/com/gg/server/global/exception/ErrorResponse.java
src/main/java/com/gg/server/global/exception/GlobalExceptionHandler.java
src/main/java/com/gg/server/global/exception/custom/InvalidParameterException.java
src/test/java/com/gg/server/game/GameControllerTest.java

- 에러 처리를 따로 관리하기 위해 Controller advice 를 추가했습니다.
- ErrorCode를 통해 에러 코드와 에러 메시지를 관리합니다.
- 에러 발생시 리턴되는 응답 형태는 ErrorResponse 클래스입니다.

GGBE-58 exception handler 등록

---

src/main/java/com/gg/server/Application.java
src/main/java/com/gg/server/domain/rank/redis/RankRedis.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisRepository.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
src/main/java/com/gg/server/domain/rank/redis/RedisKeyManager.java
src/test/java/com/gg/server/domain/rank/redis/RankRedisRepositoryTest.java

- redis repository, redis key manager 완성
- 각자 api짜면서 필요한 redis service는 redis key manager랑 redis repository이용해서 짜시면 될 것 같습니다
-

GGBE-61 redis crud 완성

---

src/main/java/com/gg/server/domain/slotmanagement/data/SlotManagementRepository.java
src/main/java/com/gg/server/domain/user/User.java
src/main/java/com/gg/server/domain/user/UserRepository.java
src/main/java/com/gg/server/global/security/info/OAuthUserInfo.java
src/main/java/com/gg/server/global/security/info/impl/FortyTwoOAuthUserInfo.java
src/main/java/com/gg/server/global/security/info/impl/KakaoOAuthUserInfo.java
src/main/java/com/gg/server/global/security/service/CustomOAuth2UserService.java

- 로그인 kakao 아이디 식별 로직 추가
- 로그인 kakao 아이디 식별 로직 추가
- domain slotManagement repo도 추가되긴 했는데 슬롯 조회 api에서 써야 되서 추가하겠습니다.
-

[fix] GGBE-62 add kakao identification

---

src/main/java/com/gg/server/domain/rank/controller/RankController.java
src/main/java/com/gg/server/domain/rank/dto/ExpRankDto.java
src/main/java/com/gg/server/domain/rank/dto/ExpRankPageResponseDto.java
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/user/UserRepository.java
src/main/java/com/gg/server/global/config/WebConfig.java
src/test/java/com/gg/server/domain/rank/controller/RankControllerTest.java
src/test/java/com/gg/server/game/GameControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- user exp rank page api 완성
-
-

GGBE-60 rank exp api

---

src/main/java/com/gg/server/domain/rank/data/Rank.java
src/main/java/com/gg/server/domain/rank/data/RankRepository.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- rank table 매핑 수정, user update시에 rank table도 업데이트 하도록 수정
-
-

GGBE-50 rank table 매핑 수정, user update시에 rank table도 업데이트 하도록 수정

---

src/main/java/com/gg/server/domain/noti/data/Noti.java
src/main/java/com/gg/server/domain/rank/controller/RankController.java
src/main/java/com/gg/server/domain/rank/dto/RankDto.java
src/main/java/com/gg/server/domain/rank/dto/RankPageResponseDto.java
src/main/java/com/gg/server/domain/rank/redis/RankRedis.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisRepository.java
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/test/java/com/gg/server/domain/rank/controller/RankControllerTest.java
src/test/java/com/gg/server/domain/rank/redis/RankRedisRepositoryTest.java
src/test/java/com/gg/server/game/GameControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- rank page api 완료
- rankRedis에 intraId 필드 추가, notiType size 15로 증가
-

GGBE-77 rank page api 완료

---

build.gradle
src/main/resources/db/migration/V1.1__migration_42gg_v2.sql

- flyway와 마이그레이션 스크립트 추가했습니다.
- yml파일에 flyway설정 추가됬습니다. flyway설정에 사용할 db스키마, 사용자, 비밀번호 수정해서 사용해야 합니다.
- 기존에 사용하던 백업db 넣어놓은 상태로 부트 실행하시면 최신 db로 바뀝니다!
-

[feat] add flyway and migration script

---

src/main/java/com/gg/server/domain/rank/redis/RankRedisRepository.java
src/main/java/com/gg/server/domain/rank/service/RankService.java

- rank api에서 totalPage계산시에 redis hash의 갯수 말고 zset의 갯수로 계산하도록 로직 변경
-
-

Ggbe 77 rank ppp

---

src/main/java/com/gg/server/domain/noti/data/NotiRepository.java
src/main/java/com/gg/server/domain/noti/dto/NotiDto.java
src/main/java/com/gg/server/domain/noti/dto/NotiResponseDto.java
src/main/java/com/gg/server/domain/noti/service/NotiService.java
src/main/resources/db/migration/V1.2.1__add_modified_at_to_announcement.sql
src/test/java/com/gg/server/domain/match/service/MatchRedisServiceTest.java
src/test/java/com/gg/server/domain/match/service/MatchTestUtils.java
src/test/java/com/gg/server/domain/noti/controller/NotiControllerTest.java
src/test/java/com/gg/server/game/GameControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- noti noti test 추가했습니다.
- announcement 테이블에 modified_at컬럼 추가, create_time이 이름이 잘못되어 create_at으로 수정했습니다
-
-

GGBE-73--add-noti-test

---

src/main/java/com/gg/server/domain/noti/controller/NotiController.java
src/test/java/com/gg/server/domain/noti/controller/NotiControllerTest.java

- PUT /pingpong/notifications/check
- DELETE /notifications
테스트 추가했습니다.
-
-

Ggbe 73  add noti test

---

src/main/java/com/gg/server/admin/announcement/controller/AnnouncementAdminController.java
src/main/java/com/gg/server/admin/announcement/data/AnnouncementAdminRepository.java
src/main/java/com/gg/server/admin/announcement/dto/AnnouncementAdminDto.java
src/main/java/com/gg/server/admin/announcement/dto/AnnouncementAdminListResponseDto.java
src/main/java/com/gg/server/admin/announcement/dto/AnnouncementAdminResponseDto.java
src/main/java/com/gg/server/admin/announcement/service/AnnouncementAdminService.java
src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerTest.java

- 관리자 공지사항 조회 pingpong/admin/announcement?page=${currentpage}&size=${recordSize}
-
-

GGbe 31 announcement curd

---

src/main/java/com/gg/server/admin/announcement/controller/AnnouncementAdminController.java
src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerFailTest.java

- @Valid param 추가 및 테스트 코드 추가
-
-

[fix][test]valid param 추가 및 테스트 코드 추가

---

src/main/java/com/gg/server/admin/penalty/controller/PenaltyController.java
src/main/java/com/gg/server/admin/penalty/dto/PenaltyListResponseDto.java
src/main/java/com/gg/server/admin/penalty/dto/PenaltyUserResponseDto.java
src/main/java/com/gg/server/admin/penalty/service/PenaltyService.java
src/test/java/com/gg/server/admin/penalty/controller/PenaltyControllerTest.java

- [GET]pingpong/admin/penalty/users?page={pageNumber}&size=10
- [GET]pingpong/admin/penalty/users?q=${keyword}&page=${pageNumber}
- parameter valid 와 페이징네이션 오류 수정 및 테스트코드 작성
-

Ggbe 35  get admin penalty

---

createView.sql
src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/game/GameService.java
src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/game/dto/req/GameListReqDto.java
src/main/java/com/gg/server/domain/game/dto/req/NormalGameListReqDto.java
src/main/java/com/gg/server/domain/game/dto/req/RankGameListReqDto.java
src/test/java/com/gg/server/game/GameControllerTest.java

- user intra Id 를 가지고 게임 결과 목록을 조회하는 api 입니다.
- 기존 랭크, 일반, 전체 게임 조회 api 에 user nickname을 추가로 받아서 처리하도록 수정했습니다.

GGBE-20 유저별 게임 결과 전체 조회

---

src/main/java/com/gg/server/admin/announcement/controller/AnnouncementAdminController.java
src/main/java/com/gg/server/admin/announcement/dto/AnnouncementAdminUpdateDto.java
src/main/java/com/gg/server/admin/announcement/service/AnnouncementAdminService.java
src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerTest.java

- 관리자 공지사항 삭제 api
- 81번 풀리퀘 먼저 merge 필요
- 최신 공지사항 PUT을 통한 삭제시간 추가를 통한 삭제 
-

Ggbe 80 put pingpong admin announcement

---

src/main/java/com/gg/server/admin/announcement/controller/AnnouncementAdminController.java
src/main/java/com/gg/server/admin/announcement/data/AnnouncementAdminRepository.java
src/main/java/com/gg/server/admin/announcement/dto/AnnouncementAdminAddDto.java
src/main/java/com/gg/server/admin/announcement/service/AnnouncementAdminService.java
src/main/java/com/gg/server/domain/announcement/Announcement.java
src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerTest.java

Ggbe 81 post pingpong admin announcement

---

createView.sql
src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/game/GameService.java
src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/game/dto/GameResultResDto.java
src/main/java/com/gg/server/domain/game/dto/GameTeamInfo.java
src/main/java/com/gg/server/domain/game/dto/GameTeamUserInfo.java
src/main/java/com/gg/server/domain/team/dto/MatchTeamsInfoDto.java
src/main/java/com/gg/server/domain/team/dto/TeamInfo.java
src/main/java/com/gg/server/domain/team/dto/TeamUserInfoDto.java
src/main/java/com/gg/server/global/exception/custom/GameDBException.java
src/test/java/com/gg/server/game/GameControllerTest.java

- pingpong/games/players -> /pingpong/games/{gameId} 로 변경했습니다.
- 한 게임에 대한 팀 정보(점수, user 정보)를 보여주는 api 입니다.

GGBE-75 현재 유저의 게임 정보 조회

---

src/main/java/com/gg/server/admin/announcement/controller/AnnouncementAdminController.java
src/main/java/com/gg/server/admin/announcement/service/AnnouncementAdminService.java

- 관리다 공지사항 api 중에서 변경된 코드 스타일 적용
-
- [fix][style] 400에러 예외처리 수정
-  [fix][style]ResponseEntity 생성. service 말고 Controller에서.
-  [fix][style] Pageable을 service에서 controller로 옮김

Ggbe 86 fix admin 400 exception

---

src/main/java/com/gg/server/global/security/service/CustomOAuth2UserService.java

- user 회원가입시에 RankRedis와 Rank 만들어주기 ZSet은 제외!!
- Transactional 처리가 안되어있어서 추가
-
-

user 회원가입시 rank data만들어주기

---

src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/game/GameService.java
src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/test/java/com/gg/server/game/GameControllerTest.java
src/test/java/com/gg/server/game/GameServiceTest.java

- game 관련 기능 리팩토링입니다.
- Game Service 를 두개로 분리했습니다.

GGBE-88 game api 리팩토링

---

src/main/java/com/gg/server/domain/rank/data/RankRepository.java
src/main/java/com/gg/server/domain/rank/redis/RankRedis.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisRepository.java
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/rank/service/RedisUploadService.java
src/main/java/com/gg/server/global/exception/ErrorCode.java
src/main/java/com/gg/server/global/exception/GlobalExceptionHandler.java

- server 올릴 때 redis가 비어있으면 db에서 redis정보를 채우는 로직
- 
-

Ggbe 78 redis db backup

---

src/main/java/com/gg/server/domain/pchange/data/PChangeRepositoryCustom.java
src/main/java/com/gg/server/domain/pchange/data/PChangeRepositoryImpl.java
src/main/java/com/gg/server/domain/rank/controller/RankController.java
src/main/java/com/gg/server/domain/user/User.java
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/test/java/com/gg/server/domain/rank/controller/RankControllerTest.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java

GGBE-90 user api 수정

---

src/main/java/com/gg/server/domain/feedback/controller/FeedbackController.java
src/main/java/com/gg/server/domain/feedback/data/Feedback.java
src/main/java/com/gg/server/domain/feedback/data/FeedbackRepository.java
src/main/java/com/gg/server/domain/feedback/dto/FeedbackRequestDto.java
src/main/java/com/gg/server/domain/feedback/service/FeedbackService.java
src/main/java/com/gg/server/domain/feedback/type/FeedbackType.java
src/test/java/com/gg/server/domain/feedback/controller/FeedbackControllerTest.java

- 유저 피드백 등록
- [post]/pingpong/feedback
-

Ggbe 76 feat user feedback

---

src/main/java/com/gg/server/admin/feedback/controller/FeedbackAdminController.java
src/main/java/com/gg/server/admin/feedback/data/FeedbackAdminRepositorySearch.java
src/main/java/com/gg/server/admin/feedback/data/FeedbackAdminRepositorySearchImpl.java
src/main/java/com/gg/server/admin/feedback/service/FeedbackAdminService.java
src/test/java/com/gg/server/admin/feedback/controller/FeedbackAdminControllerTest.java

- 관리자 유저별 피드백 검색
- [get]pingpong/admin/feedback?intraId=${intraId}&page=${pageNumber}&size={size}
-

Ggbe 84 feat admin get user feedback

---

src/main/java/com/gg/server/admin/feedback/controller/FeedbackAdminController.java
src/main/java/com/gg/server/admin/feedback/data/FeedbackAdminRepository.java
src/main/java/com/gg/server/admin/feedback/service/FeedbackAdminService.java
src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/game/dto/req/NormalGameListReqDto.java
src/main/java/com/gg/server/domain/game/exception/GameDataException.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/game/service/GameStatusService.java
src/main/java/com/gg/server/domain/noti/service/NotiService.java
src/main/java/com/gg/server/domain/pchange/data/PChange.java
src/main/java/com/gg/server/domain/pchange/service/PChangeService.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
src/main/java/com/gg/server/domain/team/data/TeamUserRepository.java
src/main/java/com/gg/server/global/exception/ErrorCode.java
src/test/java/com/gg/server/game/GameControllerTest.java

- 변경된 API 스펙에 맞게 코드 수정했습니다.
- Rank 점수 입력 시 exp 도 올라가도록 수정했습니다.

GGBE-88 game api 리팩토링

---

src/main/java/com/gg/server/domain/game/dto/GameResultResDto.java
src/main/java/com/gg/server/domain/game/dto/GameTeamInfo.java
src/main/java/com/gg/server/domain/game/service/GameStatusService.java

- 게임 API 에러 처리
- 게임 스케줄러 예외처리
- 팀 세팅 로직 수정
- 게임 스케줄러 시작 5분전 게임이 없을 경우 예외처리

GGBE-108 게임 관련 api 에러 수정

---

src/main/java/com/gg/server/domain/rank/exception/RankNotFoundException.java
src/main/java/com/gg/server/domain/rank/exception/RedisDataNotFoundException.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisRepository.java
src/main/java/com/gg/server/domain/rank/service/RankFindService.java
src/main/java/com/gg/server/domain/rank/service/RedisUploadService.java
src/main/java/com/gg/server/domain/season/exception/SeasonNotFoundException.java
src/main/java/com/gg/server/domain/season/service/SeasonFindService.java
src/main/java/com/gg/server/domain/user/exception/TokenNotValidException.java
src/main/java/com/gg/server/domain/user/exception/UserNotFoundException.java
src/main/java/com/gg/server/domain/user/service/UserFindService.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/main/java/com/gg/server/global/security/jwt/repository/JwtRedisRepository.java
src/test/java/com/gg/server/domain/rank/controller/RankControllerTest.java

GGBE-93 error handle class 수정

---

src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/game/dto/req/NormalGameListReqDto.java
src/main/java/com/gg/server/global/dto/PageRequestDto.java

GGBE-114 game controller request 객체 수정

---

src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/game/dto/ExpChangeResultResDto.java
src/main/java/com/gg/server/domain/game/dto/PPPChangeResultResDto.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/pchange/data/PChangeRepositoryCustom.java
src/main/java/com/gg/server/domain/pchange/data/PChangeRepositoryImpl.java
src/main/java/com/gg/server/domain/pchange/exception/PChangeNotExistException.java
src/main/java/com/gg/server/domain/pchange/service/PChangeService.java
src/main/java/com/gg/server/global/exception/ErrorCode.java
src/test/java/com/gg/server/game/GameControllerTest.java

- 게임 결과 exp, ppp 변경 데이터 조회하는 api 입니다
- Rank 게임 결과는 exp, ppp 변경 정보를 보여줍니다.
- Normal 게임 결과는 exp 변경 정보만 보여줍니다

GGBE-22 게임 결과 1 건 조회

---

src/main/java/com/gg/server/admin/user/controller/UserAdminController.java
src/main/java/com/gg/server/admin/user/dto/UserDetailAdminResponseDto.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/resources/db/migration/V1.2.3__add_penalty_table.sql
src/test/java/com/gg/server/admin/user/controller/UserAdminControllerTest.java

- 유저 세부정보 조회, 마이그레이션 스크립트 수정
- 마이그레이션 스크립트가 수정되어서 flyway가 터질수 있습니다. DB새로 밀고 돌려주시면 됩니다.
-

Ggbe 99  get pingpong admin users {user id}

---

src/main/resources/db/migration/V1.2.3__add_penalty_table.sql

- penalty테이블의 penalty time의 자료형을 DATETIME에서 INT로 바꿨습니다
-
-

[feat] testcode 작성

---

src/main/java/com/gg/server/admin/announcement/controller/AnnouncementAdminController.java
src/main/java/com/gg/server/admin/announcement/dto/AnnouncementAdminListResponseDto.java
src/main/java/com/gg/server/admin/announcement/service/AnnouncementAdminService.java

- 관리자 공지 page dto 대응 및 현재 페이지 반환 제거
-
-

Ggbe 110 fix an pageable

---

src/main/java/com/gg/server/domain/noti/service/NotiService.java
src/test/java/com/gg/server/domain/noti/service/NotiServiceTest.java

- Matched와 Cancel에 대한 알림 생성 메서드를 NotiService에 추가했습니다
-
-

GGBE-126 feat-notiCreateMethod

---

src/main/java/com/gg/server/domain/game/dto/ExpChangeResultResDto.java
src/main/java/com/gg/server/domain/game/dto/GameListResDto.java
src/main/java/com/gg/server/domain/game/dto/GameResultResDto.java
src/main/java/com/gg/server/domain/game/dto/GameTeamInfo.java
src/main/java/com/gg/server/domain/game/dto/PPPChangeResultResDto.java
src/main/java/com/gg/server/domain/game/dto/req/GameListReqDto.java
src/main/java/com/gg/server/domain/game/dto/req/NormalGameListReqDto.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/pchange/service/PChangeService.java
src/main/java/com/gg/server/domain/team/dto/MatchTeamsInfoDto.java
src/main/java/com/gg/server/domain/team/dto/TeamInfo.java
src/main/java/com/gg/server/domain/team/dto/TeamUserInfoDto.java
src/main/java/com/gg/server/domain/team/dto/TeamUserListDto.java
src/test/java/com/gg/server/game/GameControllerTest.java
src/test/java/com/gg/server/game/service/GameFindServiceTest.java

[fix] GGBE-128 class equals method 수정

---

src/main/java/com/gg/server/global/security/config/SecurityConfig.java
src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerFailTest.java
src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerTest.java
src/test/java/com/gg/server/admin/feedback/controller/FeedbackAdminControllerTest.java
src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java
src/test/java/com/gg/server/admin/season/SeasonAdminControllerTest.java
src/test/java/com/gg/server/admin/slotmanagement/controller/SlotAdminControllerFailTest.java
src/test/java/com/gg/server/admin/slotmanagement/controller/SlotAdminControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- 관리자 모드 접근, admin 권한 있는 user만 접근 되도록 변경(테스트 코드 : 공지사항, 피드백, 게임, 시즌, 슬롯관리 대응완료)
-
-

[fix]GGBE-117 어드민 유저 외의 관리자 모드 접근 금지 대응

---

src/main/java/com/gg/server/admin/feedback/dto/FeedbackAdminResponseDto.java

- 관리자 피드백 리스폰스 DTO 변수 이름 변경
-
-

[fix]feedback response DTO 수정

---

src/main/java/com/gg/server/domain/user/dto/UserLiveResponseDto.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java

- users live api response에 game id값 추가했습니다
-
-

GGBE-105 users live api response에 game id 추가

---

src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/game/dto/GameResultResDto.java
src/main/java/com/gg/server/domain/game/dto/GameTeamUser.java
src/main/java/com/gg/server/domain/game/dto/req/RankGameListReqDto.java
src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/team/dto/MatchTeamsInfoDto.java
src/main/java/com/gg/server/domain/team/dto/TeamInfo.java
src/main/java/com/gg/server/domain/team/dto/TeamUserInfoDto.java
src/main/java/com/gg/server/domain/team/dto/TeamUserListDto.java
src/main/java/com/gg/server/global/config/SwaggerConfig.java
src/main/resources/db/migration/V1.2.6__add_v_game_detail_list.sql

- 랭크게임 조회 결과에 wins, losses 값이 누락되어 추가했습니다.
- wins, losses 값 가져올 때 rank 테이블도 같이 조회해야해서 view table 추가했습니다.

GGBE-132 랭크 게임 조회 시 wins losses 값 추가

---

src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/test/java/com/gg/server/game/service/GameFindServiceTest.java
src/test/java/com/gg/server/game/service/GameStatusServiceTest.java

- 랭크게임 점수 입력을 기존에 두명에게 입력받기로 했던 것에서 한명만 입력하는 것으로 수정했습니다.

GGBE-129 게임 점수 등록 api 변경 대응

---

src/main/java/com/gg/server/domain/game/data/Game.java
src/main/java/com/gg/server/domain/team/data/Team.java
src/main/java/com/gg/server/domain/team/data/TeamUser.java
src/main/resources/db/migration/V1.2.7__team_and_teamuser_cascade.sql
src/test/java/com/gg/server/game/service/GameDBTest.java

- Game Team TeamUser 사이 CasCade 설정 추가해서 Game레코드를 지우면 연관 레코드들도 전부 삭제됩니다.
-
-

GGBE-130-DB-team_user-Cascade-slotManagement

---

src/main/java/com/gg/server/admin/game/service/GameAdminService.java
src/main/java/com/gg/server/admin/noti/service/NotiAdminService.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java

GGBE-36--modify-exception

---

src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/user/controller/UserController.java

- user api response status 수정, rank api 에러처리 수정
-
-

GGBE-138 user api response status , rank api 수정

---

src/main/resources/db/migration/V1.2.8__modify_slot_management_table.sql
src/test/java/com/gg/server/season/SeasonTriggerTest.java

- Season 삭제 방지 트리거및 slot_management테이블 수정
-
-

GGBE-135-DB-add-season-remove-prevent-trigger

---

src/main/java/com/gg/server/domain/game/dto/GameTeamInfo.java

- 게임 상태 조회하는 API 입니다.
- 점수 입력 상태 확인하는 곳에서 -1일때 점수 입력 전이었는데 0으로 체크해서 수정했습니다.

[fix] GGBE-144 game 점수 입력 체크 로직 수정

---

src/main/java/com/gg/server/domain/user/service/UserService.java

Ggbe 137 user live refacoring

---

.gitignore
src/main/java/com/gg/server/domain/rank/controller/RankController.java
update-yml.sh

[fix] GGBE-137 rank exp 수정

---

src/main/java/com/gg/server/domain/game/service/GameService.java
src/test/java/com/gg/server/game/GameControllerTest.java

- 랭크게임 점수 입력하는 API 입니다
- 게임 결과 등록 시 기존 score 가 -1 일때만 점수 입력이 가능하도록 수정했습니다.

[fix] GGBE-146 게임 결과 등록 API 수정

---

src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/game/dto/req/GameListReqDto.java
src/main/java/com/gg/server/domain/game/dto/req/NormalGameListReqDto.java

- 게임 목록 조회 api 수정입니다.
- 상속받은 클래스를 요청으로 받는 경우 모든 부모 클래스에 @Setter 어노테이션을 추가했습니다.

[fix] GGBE-147 게임 목록 조회 시 intraId 안들어가는 문제 수정

---

src/main/java/com/gg/server/domain/game/exception/GameExistException.java
src/main/java/com/gg/server/domain/match/data/RedisMatchTime.java
src/main/java/com/gg/server/domain/match/data/RedisMatchUser.java
src/main/java/com/gg/server/domain/match/dto/MatchStatusDto.java
src/main/java/com/gg/server/domain/match/service/MatchService.java
src/main/java/com/gg/server/global/exception/ErrorCode.java

- 게임 생성 에러 수정 및 Redis hash 추가
-
-

Ggbe 150 match modify game error

---

src/main/java/com/gg/server/domain/rank/controller/RankController.java
src/main/java/com/gg/server/domain/rank/dto/ExpRankDto.java
src/main/java/com/gg/server/domain/rank/dto/RankDto.java
src/main/java/com/gg/server/domain/rank/redis/RankRedis.java
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/user/UserRepository.java
src/main/java/com/gg/server/domain/user/dto/UserNormalDetailResponseDto.java

- user rank api 수정했습니다 user image uri 주도록 수정
-
-

Ggbe 149 user rank api

---

src/main/java/com/gg/server/domain/match/service/MatchService.java
src/main/java/com/gg/server/domain/penalty/service/PenaltyService.java
src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java
src/test/java/com/gg/server/domain/match/service/MatchTestUtils.java

- 유저 게임 생성되고 나서 슬롯이 등록되는 에러 수정
- 패널티 time to live 수정
- 유저 게임 생성되고 나서 슬롯이 등록되는 에러 수정
- 패널티 time to live 수정
-

Ggbe 151  handle exception with user game

---

src/test/java/com/gg/server/domain/match/service/MatchTestUtils.java
src/test/java/com/gg/server/domain/rank/redis/RankRedisRepositoryTest.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

GGBE-149 test 코드 수정

---

src/main/java/com/gg/server/Application.java
src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/global/config/RedisConfig.java

- 게임 목록 조회 시 Redis 에 캐싱되도록 추가하였습니다.
- 캐싱 된 내용이 오래도록 참조되지 않을 경우를 대비해 캐싱 기한을 1일로 설정하였습니다.
- 스케줄러 사용을 위해 추가했던 EnableScheduling 어노테이션을 사용하지 않아 삭제했습니다.

GGBE-136 게임 목록 조회 시 캐싱 기능 추가

---

src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/game/dto/GameResultResDto.java
src/main/java/com/gg/server/domain/game/dto/req/RankGameListReqDto.java
src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java

- ppp result 가 DB에서 NotNull 이기 때문에 null 로 저장되던 부분을 현재 ppp 값이 저장되도록 수정했습니다.
- response Dto 에 LocalDateTime 이 직렬화/역직렬화 문제가 있어 JsonSerialize, JsonDeserialize 추가했습니다.

GGBE-153 normal 게임 결과 입력 시 ppp result 값 null 오류 수정

---

src/main/java/com/gg/server/domain/game/dto/ExpChangeResultResDto.java

- exp 변화량을 보여주는 api입니다.
-
- beforeExp 가 totalExp 가 아니라 현재 레벨의 exp 를 보여주도록 수정했습니다.

[fix] GGBE-156 before exp before레벨의 exp 로 수정

---

src/main/java/com/gg/server/admin/announcement/data/AnnouncementAdminRepository.java
src/main/java/com/gg/server/admin/announcement/dto/AnnouncementAdminResponseDto.java
src/main/java/com/gg/server/admin/announcement/service/AnnouncementAdminService.java
src/main/java/com/gg/server/admin/feedback/dto/FeedbackAdminResponseDto.java
src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerTest.java

- res dto 변수타입 수정 및 optional 추가
-
-

Ggbe 155 admin dto fix

---

src/main/java/com/gg/server/admin/announcement/dto/AnnouncementAdminAddDto.java
src/main/java/com/gg/server/admin/feedback/controller/FeedbackAdminController.java
src/main/java/com/gg/server/admin/feedback/dto/FeedbackAdminPageRequestDto.java
src/main/java/com/gg/server/admin/game/controller/GameAdminController.java
src/main/java/com/gg/server/admin/game/dto/GameLogAdminRequestDto.java
src/main/java/com/gg/server/admin/noti/controller/NotiAdminController.java
src/main/java/com/gg/server/admin/noti/dto/NotiAdminDto.java
src/main/java/com/gg/server/admin/noti/dto/SendNotiAdminRequestDto.java
src/main/java/com/gg/server/admin/noti/service/NotiAdminService.java
src/main/java/com/gg/server/admin/rank/service/RankAdminService.java
src/main/java/com/gg/server/admin/season/controller/SeasonAdminController.java
src/main/java/com/gg/server/admin/season/dto/SeasonCreateRequestDto.java
src/main/java/com/gg/server/admin/season/dto/SeasonUpdateRequestDto.java
src/main/java/com/gg/server/admin/slotmanagement/dto/SlotCreateRequestDto.java
src/main/java/com/gg/server/admin/slotmanagement/service/SlotAdminService.java
src/main/java/com/gg/server/admin/team/data/TeamAdminRepository.java
src/main/java/com/gg/server/domain/feedback/controller/FeedbackController.java
src/main/java/com/gg/server/domain/feedback/exception/FeedbackNotFoundException.java
src/main/java/com/gg/server/domain/feedback/service/FeedbackService.java
src/main/java/com/gg/server/global/exception/ErrorCode.java
src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerFailTest.java
src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java
src/test/java/com/gg/server/admin/season/SeasonAdminControllerTest.java
src/test/java/com/gg/server/admin/user/controller/UserAdminControllerTest.java

- [style]exception errorcode 수정 및 admin 안쓰는 import 삭제
-
-

[style]exception errorcode 수정 및 admin 안쓰는 import 삭제

---

src/main/java/com/gg/server/domain/announcement/data/AnnouncementRepository.java
src/main/java/com/gg/server/domain/announcement/service/AnnouncementService.java

GGBE-145--api-fix-optional

---

src/main/java/com/gg/server/admin/penalty/data/PenaltyUserAdminRedisRepository.java
src/test/java/com/gg/server/admin/penalty/controller/PenaltyAdminControllerTest.java

- penalty test 및 admin 로직 수정
- penalty test 및 admin 로직 수정
-

Ggbe 160 penalty test 

---

src/main/java/com/gg/server/domain/match/dto/SlotStatusResponseListDto.java
src/main/java/com/gg/server/domain/match/utils/SlotGenerator.java
src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java

- FE 요청대로 get match/time/scope?mode={mode} 수정
- FE 요청대로 get match/time/scope?mode={mode} 수정
-

Ggbe 161 fix get api dto

---

src/main/resources/logback-spring.xml

- 테섭 로그파일 생성 상태 확인을 위한 파일 수정
-
-

[fix]테스트로그를 위한 로그 파일 용량 수정

---

src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/java/com/gg/server/domain/rank/redis/RankRedis.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
src/test/java/com/gg/server/game/service/GameServiceTest.java

- ELO ppp change 함수 결과값을 ppp에 update 하는 과정에서 오류를 수정했습니다

GGBE-162 rank data redis db 정합성 오류

---

src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java
src/test/java/com/gg/server/admin/season/SeasonAdminControllerTest.java

- 디비 삭제가 의존성으로 인해 안 되는 것을 수정
- 레디스 삭제 후 디비 삭제로 변경
- 레디스 삭제 후 디비 삭제로 변경

[fix]디비 삭제(의존성 문제로 삭제 안됨)후 레디스 삭제로 인한 의존성 문제 해결

---

src/main/java/com/gg/server/admin/game/dto/RankGamePPPModifyReqDto.java
src/main/java/com/gg/server/admin/game/service/GameAdminService.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/pchange/data/PChange.java
src/main/java/com/gg/server/domain/pchange/data/PChangeRepository.java
src/main/java/com/gg/server/domain/pchange/service/PChangeService.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/main/resources/db/migration/V1.4__pchange_add_is_checked_column.sql
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java
src/test/java/com/gg/server/domain/user/controller/dto/GameInfoDto.java
src/test/java/com/gg/server/game/GameControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- DB PChange 테이블에 is_checked 컬럼 추가했습니다. 해당 컬럼이 false일 경우 envet는 game으로 전송되고 재요청시에는 해당 컬럼이 true로 바뀌어 null로 전송됩니다. 
-
-

GGBE-137-user-live-api-fix-event

---

src/main/java/com/gg/server/domain/game/service/GameService.java

- ppp와 exp 변화량 따로 처리해줬습니다.
-
-

GGBE-175--fix-pchange-beforeExp-0-bug

---

.gitignore
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/season/data/SeasonRepository.java
src/main/java/com/gg/server/domain/season/service/SeasonService.java

-  rank api -> rank 데이터 없을 시 빈 리스트 나오도록 수정
- season 조회에서 현재시즌까지의 시즌만 조회하도록 (예약된 시즌 조회 안되도록 수정)
-
-

Ggbe 137 rank api season api 수정

---

src/main/java/com/gg/server/admin/slotmanagement/service/SlotAdminService.java
src/test/java/com/gg/server/admin/slotmanagement/controller/SlotAdminControllerFailTest.java

[feat]정책추가

---

src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
src/main/java/com/gg/server/global/exception/GlobalExceptionHandler.java

- admin 게임 점수 수정시 ppp update 해야되는데 redis 에 기존 ppp 에 plus 하고 있어서 수정했습니다.

GGBE-172 admin 게임 점수 수정시 ppp 값 변경 오류

---

src/main/java/com/gg/server/domain/rank/data/Rank.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java

- 게임 조회 시 게임 결과 반영되는 api 수정
- 승패 카운트를 Redis 에만 반영하고 DB 에는 update 되지 않는 문제를 수정했습니다.

[fix] GGBE-177 게임 승패 수 반영 안되는 문제 수정

---

src/main/java/com/gg/server/domain/match/utils/MatchCalculator.java
src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java

- both normal 매칭 로직 수정
- both normal 매칭 로직 수정
-

Ggbe 179 match fix matching algorithm

---

src/main/resources/logback-spring.xml

[feat]로그 본섭용으로 설정 완료

---

src/main/resources/db/migration/V1.4__pchange_add_is_checked_column.sql

- 마이그레이션 스크립트에 main 키워드 뺐습니다.
-
-

HOTFIX-V1.4 migrationScript

---

src/main/java/com/gg/server/admin/slotmanagement/controller/SlotAdminController.java
src/main/java/com/gg/server/admin/slotmanagement/service/SlotAdminService.java
src/main/java/com/gg/server/domain/slotmanagement/SlotManagement.java
src/test/java/com/gg/server/admin/slotmanagement/controller/SlotAdminControllerFailTest.java
src/test/java/com/gg/server/admin/slotmanagement/controller/SlotAdminControllerTest.java

- 어드민 슬롯매니지먼트 최신기록 삭제
- post 부분에 로그 추가 상태 확인후 삭제 예정

Ggbe 181 slotmanagement del

---

src/main/java/com/gg/server/admin/feedback/controller/FeedbackAdminController.java
src/main/java/com/gg/server/admin/feedback/dto/FeedbackAdminPageRequestDto.java
src/test/java/com/gg/server/admin/feedback/controller/FeedbackAdminControllerTest.java

Ggbe 182 fix feedback

---

src/main/java/com/gg/server/domain/season/data/SeasonRepository.java
src/main/java/com/gg/server/global/security/info/impl/KakaoOAuthUserInfo.java
src/main/java/com/gg/server/global/security/service/CustomOAuth2UserService.java

- user login시에 rank만들어주도록 수정
-
-

Ggbe 185 user login rank

---

src/main/java/com/gg/server/admin/game/service/GameAdminService.java
src/main/resources/db/migration/V1.5__insert_pchange_normal_ppp_result.sql
src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- Normal 게임 플레이시 기존에 Phange가 0으로 입력되어 있던것이 원인 -> Normal게임 ppp_result 채워주는 쿼리 추가
-
-

GGBE-180--fix-admin-game-history

---

src/main/java/com/gg/server/global/security/handler/OAuthAuthenticationSuccessHandler.java

- 계정 연동시 카카오 유저 리프레쉬 토큰 삭제
-
-

[fix] GGBE-170 remove deleted user refresh token

---

src/main/java/com/gg/server/admin/slotmanagement/data/adminSlotManagementRepository.java
src/main/java/com/gg/server/admin/slotmanagement/service/SlotAdminService.java
src/test/java/com/gg/server/admin/slotmanagement/controller/SlotAdminControllerFailTest.java
src/test/java/com/gg/server/admin/slotmanagement/controller/SlotAdminControllerTest.java

- 슬롯 매니지먼트 현재, 최신값만 리스트 주기
- 시간 중복으로 추가되는 것 해결

Ggbe 184 get slotmanagement feat

---

src/main/java/com/gg/server/domain/game/type/Mode.java
src/main/java/com/gg/server/domain/penalty/type/PenaltyType.java

[fix] GGBE-187-fix-match-both-error

---

src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/global/security/config/SecurityConfig.java
src/main/java/com/gg/server/global/security/config/properties/AppProperties.java
src/main/java/com/gg/server/global/security/cookie/CookieUtil.java
src/main/java/com/gg/server/global/security/handler/OAuthAuthenticationSuccessHandler.java

[fix] GGBE-190 oauth 로그인 연동

---

src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/java/com/gg/server/domain/user/service/UserFindService.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/main/java/com/gg/server/global/security/cookie/CookieUtil.java

Ggbe 191 kakako user

---

src/main/java/com/gg/server/domain/match/controller/MatchController.java
src/main/java/com/gg/server/domain/match/service/MatchFindService.java
src/test/java/com/gg/server/domain/match/service/MatchBothServiceTest.java
src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java
src/test/java/com/gg/server/domain/match/service/MatchTestUtils.java

- 카카오 유저 관련 조회 api  로직 추가
- 카카오 유저 관련 조회 api 로직 추가
-

[fix] GGBE-179 modify logic of guest user

---

src/main/java/com/gg/server/admin/penalty/dto/PenaltyUserResponseDto.java
src/main/java/com/gg/server/admin/penalty/service/PenaltyAdminService.java

- 패널티 시간 잘못 저장되고 조회되는 부분 수정
- 패널티 시간 잘못 저장되고 조회되는 부분 수정
-

[fix] GGBE-193 time error

---

src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/pchange/data/PChange.java
src/main/java/com/gg/server/domain/pchange/data/PChangeRepository.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
src/main/java/com/gg/server/global/utils/AsyncMailSender.java

[fix] GGBE-194 normal game 결과 입력 api수정

---

src/main/java/com/gg/server/admin/slotmanagement/controller/SlotAdminController.java

[style]로그 삭제

---

src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java

[fix]테스트를 위한 로그처리

---

src/main/java/com/gg/server/domain/game/service/GameFindService.java

- game live 인것 조회할때 wait 상태도 조회할 수 있게 수정했습니다
-
-

[fix] GGBE-200 LIVE 상태 조회 시 END, WAIT 상태인것도 조회하도록 수정

---

src/main/java/com/gg/server/domain/announcement/service/AnnouncementService.java
src/test/java/com/gg/server/domain/announcement/controller/AnnouncementControllerTest.java

[feat]공지가 없을 경우 빈 문자열로 반환으로 변경

---

src/main/java/com/gg/server/admin/slotmanagement/service/SlotAdminService.java

[test] slot테섭을 위한 주석처리

---

src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/game/service/GameStatusService.java

- 게임 live 상태로 변경될 때 이전 캐시 삭제가 되지 않아 삭제 코드 추가했습니다.

GGBE-200 현재 게임중인 것이 포함되지 않는 문제

---

src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java

[fix]본섭 배포전 주석 지운 것 적용할 것

---

src/main/java/com/gg/server/admin/slotmanagement/service/SlotAdminService.java

- 테스트를 위해 주석처리한 것
- 본섭 배포 전, 주석 처리 한 것 해제 후 머지할 것,
-
-

본섭 배포 전, 주석 처리 한 것 해제 후 머지할 것

---

src/main/java/com/gg/server/admin/season/data/SeasonAdminRepository.java
src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java

- admin season list 출력방식 변경
-
-

[fix]admin season list 출력방식 변경

---

src/main/java/com/gg/server/admin/season/data/SeasonAdminRepository.java
src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java
src/main/java/com/gg/server/domain/season/data/SeasonRepository.java
src/main/java/com/gg/server/domain/season/service/SeasonService.java

- 도메인 시즌 출력 변경
- 시즌 중복 입력 방지
-
-

Ggbe 203 season start time

---

src/main/java/com/gg/server/admin/season/data/SeasonAdminRepository.java
src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java

[fix]중복 입력방지

---

src/main/java/com/gg/server/admin/game/service/GameAdminService.java
src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/game/service/GameStatusService.java

- 캐싱으로 인해 db 와 싱크가 맞지 않는 부분을 수정했습니다.

[fix] GGBE-200 caching 분류 추가

---

src/main/java/com/gg/server/domain/user/type/RoleType.java
src/main/java/com/gg/server/global/security/UserPrincipal.java

- User RoleType key 수정 (Ex. ROLE_USER -> USER)
-
-

GGBE-204 modify User RoleType key

---

src/main/java/com/gg/server/admin/game/service/GameAdminService.java
src/main/java/com/gg/server/domain/game/data/Game.java
src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/game/service/GameStatusService.java
src/main/java/com/gg/server/global/config/RedisConfig.java

- localdatetime serialize 오류로 캐싱 어노테시연 service layer 로 위치 변경했습니다.

[fix] GGBE-200 redis serializer error -> reset

---

src/main/java/com/gg/server/domain/user/type/RoleType.java
src/main/java/com/gg/server/global/security/UserPrincipal.java

GGBE-204 fix User RoleType key

---

src/main/resources/logback-spring.xml

[feat] logstash 연동시 merge 할것(KIBANA)

---

src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/game/keyGenerator/GameKeyGenerator.java
src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/game/service/GameStatusService.java

[fix] GGBE-200 cache 삭제 메소드 이동

---

src/main/resources/logback-spring.xml

[fix]host net

---

src/main/java/com/gg/server/admin/user/dto/UserUpdateAdminRequestDto.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/java/com/gg/server/domain/user/User.java
src/main/java/com/gg/server/domain/user/type/RoleType.java

GGBE-204 fix modify user Detail

---

src/main/java/com/gg/server/admin/rank/service/RankAdminService.java
src/main/java/com/gg/server/admin/rank/service/RankRedisAdminService.java

- [feat]레디스 게스트 유저 안들어가도록 막기
-
-

[feat]레디스 게스트 유저 안들어가도록 막기

---

src/main/resources/logback-spring.xml

[fix]kibana 다음기회로

---

src/main/java/com/gg/server/global/security/handler/OAuthAuthenticationSuccessHandler.java

- user 로그인시 기존 user refresh token에대한 검증로직 수정
-
-

[fix] GGBE-207 user login로직 수정

---

src/main/java/com/gg/server/domain/rank/dto/RankDto.java
src/main/java/com/gg/server/domain/rank/redis/RankRedis.java
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/dto/UserImageDto.java
src/main/java/com/gg/server/domain/user/dto/UserImageResponseDto.java
src/main/java/com/gg/server/domain/user/service/UserAuthenticationService.java
src/main/java/com/gg/server/domain/user/service/UserService.java

[fix] GGBE-208 user image api추가, redis에서 user iamge삭제

---

src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/service/UserService.java

[fix] GGBE-208 user image api수정

---

README.md

- readme 파일 디자인 수정 환영!! 
- 개인 담당 업무 입력해 주세요

readme 브랜치 받아서 내용 추가 해주세요!!

---

src/main/java/com/gg/server/domain/match/service/GameUpdateService.java
src/main/java/com/gg/server/domain/noti/service/NotiService.java
src/main/java/com/gg/server/domain/noti/service/SnsNotiService.java
src/main/java/com/gg/server/domain/noti/service/sns/NotiMailSender.java
src/main/java/com/gg/server/domain/noti/service/sns/SlackbotService.java

- 메일 보내는 기능 추가
- 메일 보내는 기능 추가
-

[fix] add mail service

---

src/main/java/com/gg/server/domain/match/service/GameUpdateService.java
src/test/java/com/gg/server/domain/match/service/MatchBothServiceTest.java

- 매칭 상대가 아닌 유저가 경기 취소할 때 발생하는 에러 수정
- 매칭 상대가 아닌 유저가 경기 취소할 때 발생하는 에러 수정
-

[fix] match delete error

---

src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/user/UserRepository.java

- vip list 조회시 totalExp > 0인 조건 추가
-
-

[fix] GGBE-209 vip api 수정

---

src/main/java/com/gg/server/admin/user/dto/UserDetailAdminResponseDto.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/java/com/gg/server/domain/match/service/MatchService.java
src/main/java/com/gg/server/global/security/info/impl/KakaoOAuthUserInfo.java

- admin user detail api kakao user 자세히 누를 때 버그수정
-
-

[fix] GGBE-210 admin user detail 수정

---

src/main/java/com/gg/server/admin/rank/service/RankRedisAdminService.java
src/main/java/com/gg/server/admin/user/controller/UserAdminController.java

- user detail수정시 rank게임 history있을 시에만 zset에 업데이트하도록 수정
- 
-
-

[fix] GGBE-211 user detail update수정

---

src/main/java/com/gg/server/domain/match/data/RedisMatchTimeRepository.java
src/main/java/com/gg/server/domain/match/service/GameUpdateService.java
src/main/java/com/gg/server/domain/match/service/MatchService.java
src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java

- 대기 큐 게임 생성 후에도 남겨두게끔 수정
- 대기 큐 게임 생성 후에도 남겨두게끔 수정
-

[fix] reserve waiting queue

---

src/main/java/com/gg/server/global/security/handler/OAuthAuthenticationSuccessHandler.java

[fix] GGBE-212 예상치못한 에러시 front url로 redir, 백엔드 에러페이지 안뜨도록

---

src/main/java/com/gg/server/admin/item/controller/ItemAdminController.java
src/main/java/com/gg/server/admin/item/data/ItemAdminRepository.java
src/main/java/com/gg/server/admin/item/dto/ItemHistoryResponseDto.java
src/main/java/com/gg/server/admin/item/dto/ItemListResponseDto.java
src/main/java/com/gg/server/admin/item/service/ItemAdminService.java
src/main/java/com/gg/server/domain/item/data/ItemRepository.java
src/main/java/com/gg/server/domain/user/data/User.java
src/main/java/com/gg/server/domain/user/type/BackgroundType.java
src/main/java/com/gg/server/domain/user/type/EdgeType.java
src/test/java/com/gg/server/admin/item/controller/ItemAdminControllerTest.java

- 아이템 변경내역 조회 api 추가
- 아이템 변경내역 조회 api 추가하였습니다. (/pingpong/admin/items/history)
- 테스트 코드 작성하였습니다.
- x

[GGBE-35--item-history-list-api] 아이템 변경내역 조회 api

---

src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/dto/UserNormalDetailResponseDto.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java

- 출석여부 응답값 추가
- 유저 기본 정보 조회에 출석 여부 응답값 추가했습니다. 추후 티어 이미지도 추가될 것을 고려하여 유저 서비스에 추가하였습니다.
- x

[GGBE-20--attendance-response] 출석여부 응답값 추가

---

src/main/java/com/gg/server/admin/coin/controller/CoinPolicyAdminController.java
src/main/java/com/gg/server/admin/coin/dto/CoinPolicyAdminListResponseDto.java
src/main/java/com/gg/server/admin/coin/dto/CoinPolicyAdminResponseDto.java
src/main/java/com/gg/server/admin/coin/service/CoinPolicyAdminService.java
src/test/java/com/gg/server/admin/coin/controller/CoinPolicyAdminControllerTest.java

- coinpolicy 리스트 가져오기
- 리스트 반환 및 테스트코드 작성 완료

Ggbe 22 get coinpolicy api

---

src/main/java/com/gg/server/admin/item/controller/ItemAdminController.java
src/main/java/com/gg/server/admin/item/service/ItemAdminService.java
src/test/java/com/gg/server/admin/item/controller/ItemAdminControllerTest.java

- 상품 삭제 API
- 전달받은 itemId에 해당하는 상품의 isVisible 값을 false로 바꿉니다
- x

[GGBE4-33--item-delete-api] 상품 삭제 API 추가

---

src/main/java/com/gg/server/admin/item/controller/ItemAdminController.java
src/main/java/com/gg/server/admin/item/dto/ItemDeleteRequestDto.java
src/main/java/com/gg/server/admin/item/dto/ItemHistoryResponseDto.java
src/main/java/com/gg/server/admin/item/dto/ItemUpdateRequestDto.java
src/main/java/com/gg/server/admin/item/service/ItemAdminService.java
src/main/java/com/gg/server/domain/item/data/Item.java
src/main/resources/db/migration/V2.1__add_item_creator.sql
src/test/java/com/gg/server/admin/item/controller/ItemAdminControllerTest.java

- Item 엔티티 수정 및 상품 수정, 삭제 API 수정
- Item 테이블에 생성한 관리자 intra id, 삭제한 관리자 intra id 컬럼을 추가하였습니다. (flyway 마이그레이션 완료)
- 그에 따른 item 엔티티 수정과 조회 서비스 모두 컬럼 추가 반영하였습니다.
- 상품 수정 시 수정한 관리자 intra id가 기록됩니다
- 상품 삭제 시 삭제한 관리자 intra id가 기록됩니다
- x

GGBE4-46--DB-migration

---

src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/dto/UserCoinResponseDto.java
src/main/java/com/gg/server/domain/user/service/UserCoinService.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java

- 유저의 현재 코인 가져오기
- 유저의 현재 코인 가져오기

[GGBE4-14-get-user-coin-api] 유저 현재 코인량 가져오기

---

src/main/java/com/gg/server/domain/item/exception/ItemTypeException.java
src/main/java/com/gg/server/domain/megaphone/controller/MegaphoneController.java
src/main/java/com/gg/server/domain/megaphone/dto/MegaphoneDetailResponseDto.java
src/main/java/com/gg/server/domain/megaphone/service/MegaphoneService.java
src/main/java/com/gg/server/global/exception/ErrorCode.java
src/test/java/com/gg/server/domain/megaphone/controller/MegaphoneControllerTest.java

- 확성기 상세 조회 api 추가하였습니다.
- 확성기 상세 조회 api 추가하였습니다.
- 아이템 타입 추가되어서 확인 로직 추가하였습니다.
- 확성기 id 확인할 수 있게 되어서 삭제에서 확성기 id 사용으로 수정하였습니다.
- x

[GGBE4-16--megaphone-detail-api] 확성기 상세 조회 api 추가

---

src/main/java/com/gg/server/admin/receipt/controller/ReceiptAdminController.java
src/main/java/com/gg/server/admin/receipt/data/ReceiptAdminRepository.java
src/main/java/com/gg/server/admin/receipt/data/ReceiptAdminRepositorySearch.java
src/main/java/com/gg/server/admin/receipt/dto/ReceiptAdminPageRequestDto.java
src/main/java/com/gg/server/admin/receipt/service/ReceiptAdminService.java
src/test/java/com/gg/server/admin/receipt/controller/ReceiptAdminControllerTest.java

- 기존 전체 거래내역 조회에 유저별 검색 기능 추가하였습니다
- 유저별 거래내역 조회 (구매자, 소유자 포함) 기능 추가하였습니다
- 테스트 코드 작성하였습니다

[GGBE4-25--receipt] 관리자 페이지 유저별 거래내역 조회 API 추가

---

src/main/java/com/gg/server/domain/coin/data/CoinHistoryRepository.java
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/dto/CoinHistoryResponseDto.java
src/main/java/com/gg/server/domain/user/dto/UserCoinHistoryListResponseDto.java
src/main/java/com/gg/server/domain/user/service/UserCoinService.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java

- 유저 코인 사용내역 조회
- 유저 코인 사용내역 조회, 테스트 코드

[GGBE4-19-getuser-coinhistory-api] 유저 코인 사용내역 조회

---

src/main/java/com/gg/server/admin/user/dto/UserDetailAdminResponseDto.java
src/test/java/com/gg/server/admin/user/controller/UserAdminControllerTest.java

- 어드민 유저 상세보기 api 수정
- 상세보기 로직에서 코인 추가
- 상세보기에서 코인항목 추가

[GGBE4-34-get-fix-admin-user-api] 유저상세보기 코인 추가

---

src/main/java/com/gg/server/admin/user/controller/UserAdminController.java
src/main/java/com/gg/server/admin/user/dto/UserUpdateAdminRequestDto.java
src/main/java/com/gg/server/domain/user/data/User.java

- 유저 어드민 상세보기 저장 api
- coin 값도 받도록 수정
- MultipartFile imgData 덤프값 생성 불가로 테스트 코드 작성 불가
- coin 값도 받도록 수정

[GGBE4-37-put-fix-admin-user-api] 어드민 유저 상세보기 저장api

---

src/main/java/com/gg/server/domain/game/service/GameFindService.java

- 테스트코드 동작 오류 수정
- 기존 테스트 코드에서 null 넣는 문제로 오류가 발생하여 수정했습니다.

[fix] game 조회 null guard 추가

---

src/main/java/com/gg/server/domain/megaphone/controller/MegaphoneController.java
src/main/java/com/gg/server/domain/megaphone/dto/MegaphoneTodayListResponseDto.java
src/main/java/com/gg/server/domain/megaphone/redis/MegaphoneRedis.java
src/main/java/com/gg/server/domain/megaphone/redis/MegaphoneRedisRepository.java
src/main/java/com/gg/server/domain/megaphone/service/MegaphoneService.java
src/test/java/com/gg/server/domain/megaphone/controller/MegaphoneControllerTest.java

- 확성기 당일 조회 api 추가
- 확성기 당일 조회 api 구현하였습니다.
- 레디스 저장용 test 하나 만들어두었습니다. 확성기 마지막 구현에서 삭제하겠습니다.
- x

[GGBE4-15--megaphone-today-list-api] 확성기 당일 조회 api 추가

---

src/main/java/com/gg/server/admin/megaphone/controller/MegaphoneAdminController.java
src/main/java/com/gg/server/admin/megaphone/data/MegaphoneAdminRepository.java
src/main/java/com/gg/server/admin/megaphone/dto/MegaphoneAdminResponseDto.java
src/main/java/com/gg/server/admin/megaphone/dto/MegaphoneHistoryResponseDto.java
src/main/java/com/gg/server/admin/megaphone/service/MegaphoneAdminService.java
src/main/java/com/gg/server/domain/megaphone/controller/MegaphoneController.java
src/main/java/com/gg/server/domain/megaphone/service/MegaphoneService.java
src/main/java/com/gg/server/domain/receipt/type/ItemStatus.java
src/test/java/com/gg/server/admin/megaphone/controller/MegaphoneAdminControllerTest.java

- 확성기 전체 조회 api 추가
- 확성기 전체 조회 api 추가하였습니다.
- intraId로 유저 별 조회도 가능하게 구현하였습니다,
- 테스트용 삭제하였습니다.

[GGBE4-17--megaphone-all-list-api] 확성기 전체 조회 api 추가

---

src/main/java/com/gg/server/admin/receipt/controller/ReceiptAdminController.java
src/main/java/com/gg/server/domain/rank/data/Rank.java
src/main/java/com/gg/server/domain/tier/data/Tier.java
src/main/java/com/gg/server/domain/tier/data/TierRepository.java
src/main/java/com/gg/server/domain/user/dto/UserDetailResponseDto.java
src/main/java/com/gg/server/domain/user/dto/UserNormalDetailResponseDto.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- User 정보 조회 (/pingpong/users, /pingpong/users/{targetUserId}/detail) 에 티어 정보 추가
- 유저 정보 조회시 티어이름, 티어이미지Uri 추가하였습니다.

[GGBE4-31-tier-api] User 정보 조회에 Tier 정보 추가

---

src/main/java/com/gg/server/domain/coin/service/CoinHistoryService.java
src/main/java/com/gg/server/domain/coin/service/UserCoinChangeService.java
src/main/java/com/gg/server/domain/game/dto/ExpChangeResultResDto.java
src/main/java/com/gg/server/domain/game/dto/PPPChangeResultResDto.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/test/java/com/gg/server/domain/coin/service/UserCoinChangeServiceTest.java

- 랭크게임 결과 경험치 증가량 출력시 코인 증가량 추가
- 랭크게임 결과 경험치 증가량 출력시 코인 증가량 추가

[Ggbe4-44-feat-rank-game-result]랭크게임결과 코인증가량 추가

---

src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/dto/UserCoinHistoryListResponseDto.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java

- 명세서랑 다른 json 키값 변경 및 api 주소 변경
- 해당 브랜치는 #224 가 먼저 merge가 된 이후에 merge를 진행 되어야 합니다
- 명세서랑 다른 json 키값 변경 및 api 주소 변경

[GGBE4-53-fix-user-coins-api] 명세서랑 다른 부분 수정

---

src/main/java/com/gg/server/domain/coin/service/CoinHistoryService.java
src/main/java/com/gg/server/domain/coin/service/UserCoinChangeService.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/test/java/com/gg/server/domain/coin/service/UserCoinChangeServiceTest.java

- 출석 코인 증가 코인 서비스로 로직 이동 완료
- 해당 브랜치는 #223 보다 먼저 merge가 진행 되어야 합니다
- 출석 코인 증가 코인 서비스로 로직 이동 완료

[GGBE4-54-refactor-user-attendance] 출석 코인 증가 코인 서비스로 로직 이동 완료

---

src/main/java/com/gg/server/domain/item/service/ItemService.java
src/main/java/com/gg/server/domain/noti/service/NotiService.java
src/main/java/com/gg/server/domain/noti/type/NotiType.java

- 상점 선물하기 API 와 동시에 noti가 전송됨
- "ଘ(੭ˊᵕˋ)੭* ੈ✩ " + payUser.getIntraId() + "님에게 " + itemName + " 아이템을 선물받았어요!"; 이렇게 전송됩니다
- #227 을 우선으로 merge 하고, 이것은 3번째로 merge 되어야 합니다
- merge는 제가 하겠습니다
- 기존 Noti 활용했습니다

[GGBE4-40--gift-item-api] 선물 시 알림 탭에서 알림 조회

---

src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/dto/UserCoinHistoryListResponseDto.java
src/test/java/com/gg/server/domain/user/controller/UserControllerTest.java

- 머지 순서 꼬임으로 인한 등록되지 못한 코드 업로드
-
-

Ggbe4 53 fix user coins api

---

src/main/java/com/gg/server/admin/user/controller/UserAdminController.java
src/main/java/com/gg/server/admin/user/data/UserImageAdminRepository.java
src/main/java/com/gg/server/admin/user/dto/UserImageAdminDto.java
src/main/java/com/gg/server/admin/user/dto/UserImageListAdminResponseDto.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/test/java/com/gg/server/admin/user/controller/UserAdminControllerTest.java

- admin에서 유저 이미지 테이블에 is_deleted 열이 true인 행들을 pagenation하여 보내줍니다.
- 유저 프로필 삭제내역 created_at 기준 내림차순으로 정렬
-

[GGBE4-58--profile-image-delete-list-api] 부적절한 이미지 삭제내역 조회(관리자)

---

src/main/java/com/gg/server/admin/item/controller/ItemAdminController.java
src/main/java/com/gg/server/admin/item/dto/ItemUpdateRequestDto.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/item/data/Item.java
src/main/java/com/gg/server/domain/rank/data/Rank.java
src/main/java/com/gg/server/domain/rank/data/RankRepository.java
src/main/java/com/gg/server/domain/rank/dto/RankDto.java
src/main/java/com/gg/server/domain/rank/dto/RankPageResponseDto.java
src/main/java/com/gg/server/domain/rank/redis/RankRedis.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisRepository.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
src/main/java/com/gg/server/domain/tier/data/Tier.java
src/main/java/com/gg/server/domain/tier/data/TierRepository.java
src/main/java/com/gg/server/domain/tier/service/TierService.java
src/test/java/com/gg/server/domain/match/service/MatchTestUtils.java
src/test/java/com/gg/server/domain/rank/redis/RankRedisRepositoryTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- 아기다리고기다리던 티어 서비스 및 로직 추가되었습니다
- 기존에 꼬인 브랜치 커밋 내용 전부 반영해서 올렸습니다
- TierService 추가 및 RankRedisService 변경
- ItemUpdateRequestDto이름 UpdateItemInfo로 변경

[GGBE4-30-Rank-Tier-Logic] 티어 로직 MySQL & Redis 반영

---

src/main/java/com/gg/server/admin/user/dto/UserDetailAdminResponseDto.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/domain/user/data/User.java
src/main/java/com/gg/server/domain/user/data/UserImage.java
src/main/java/com/gg/server/domain/user/dto/UserDetailResponseDto.java
src/main/java/com/gg/server/domain/user/dto/UserImageDto.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/main/java/com/gg/server/global/utils/aws/AsyncNewUserImageUploader.java
src/main/resources/db/migration/V2.5__add_userImage_and_user_image_uri.sql

- views에서 전에 drop했던 USER  테이블의 imageUrl 을 참조하는데 이 부분을 다시 살렸습니다.
- User 테이블의 ImageUrl 은 유저 이미지 테이블에 수정 될 때 마다 업데이트 됩니다.
- top3 rank에 null 이 담기는 문제를 해결
- user 엔티티에 imageUri를 추가했습니다.
- 조회 api 부분도 user.getImageUri로 수정했습니다.

[GGBE4-60--user-image-view] views userImage 누락 문제 해결

---

src/main/java/com/gg/server/admin/user/dto/UserImageAdminDto.java
src/main/java/com/gg/server/domain/user/dto/UserImageDto.java
src/main/java/com/gg/server/domain/user/service/UserService.java

- 유저 top3 조회에 이미지띠 정보와 tier 이미지 정보를 추가
- 유저 admin 이미지 조회시 body에 유저 intraId 가 보이도록 추가
- userImageDto 에 edge와 tierImage를 추가했습니다.
- userImagaeAdminDto 에 userIntraId를 추가했습니다.
-

[GGBE4-62--top3-edge-tier-add-api] top3 이미지띠 및 티어이미지 추가 && admin 이미지 조회페이지 Intra Id 추가

---

src/main/java/com/gg/server/domain/coin/service/CoinHistoryService.java
src/main/java/com/gg/server/domain/coin/type/HistoryType.java
src/test/java/com/gg/server/domain/coin/service/UserCoinChangeServiceTest.java

- 프론트요청사항으로 코인히스토리 저장 내역 명명 수정
- 상점에서 사용한 경우 음수로 보이기
- 각 명칭 별 저장 String 수정
아이템 구매 시:  (아이템이름) 구매
출석 시: 출석
선물 시 : 누구에게 아이템 선물

[GGBE4-63-fix-coinHistory] 코인히스토리 저장 내역 명명 수정

---

src/main/java/com/gg/server/admin/user/controller/UserAdminController.java
src/main/java/com/gg/server/admin/user/data/UserImageAdminRepository.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java

- 관리자 유저 이미지 리스트 페이징 안되는 문제 해결 && delete-list/{intraId} 추가
- 기존 쿼리의 오류를 수정하였습니다. 그리고 프론트 요청으로 delete-list 유저 아이디 검색 api 도 추가했습니다.
-

[GGBE4-65--image-list-page-bug] 유저 이미지 페이징 안되는 문제 해결 && delete-list/{intraId} 추가

---

src/main/java/com/gg/server/admin/megaphone/controller/MegaphoneAdminController.java

- 확성기 정렬 조건 수정
- 확성기 정렬 조건 날짜에서 아이디로 변경하였습니다.

[GGBE4-17--megaphone-all-list-api] 확성기 정렬 조건 수정

---

src/main/java/com/gg/server/admin/rank/service/RankAdminService.java
src/main/java/com/gg/server/admin/rank/service/RankRedisAdminService.java
src/main/java/com/gg/server/domain/rank/data/Rank.java
src/main/java/com/gg/server/domain/rank/redis/RankRedis.java

- 새로운 시즌 생성 시 모든 랭크 유저 티어 1 (손바닥) 으로 초기화
- 레디스 및 MySQL 데이터베이스 상에서 티어 1 로 초기화 하는 로직 추가하였습니다.

[GGBE4-68--Season-Tier] 새로운 시즌 생성 시 티어 1로 초기화

---

src/main/java/com/gg/server/admin/user/controller/UserAdminController.java
src/main/java/com/gg/server/admin/user/data/UserImageAdminRepository.java
src/main/java/com/gg/server/admin/user/dto/UserImageAdminDto.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/java/com/gg/server/domain/rank/dto/ExpRankDto.java
src/main/java/com/gg/server/domain/rank/dto/RankDto.java
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/user/data/UserImage.java
src/main/java/com/gg/server/domain/user/data/UserImageRepository.java
src/main/java/com/gg/server/domain/user/dto/UserImageDto.java
src/main/java/com/gg/server/domain/user/dto/UserNormalDetailResponseDto.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/main/java/com/gg/server/global/utils/aws/AsyncNewUserImageUploader.java
src/main/resources/db/migration/V2.5__add_userImage_and_user_image_uri.sql
src/test/java/com/gg/server/admin/user/controller/UserAdminControllerTest.java

- 유저기본조회 edge 추가 && Current Page 추가
- 유저기본정보 조회에 edge를 추가하고 현재 유저 프로필 이미지를 조회할 수 있는 currentPage를 구현하였습니다!
- userImage 테이블에 isDeleted 를 deletedAt으로 변경하고 currentPage를 추가했습니다.

[GGBE4-66--rank-text-color-user-info-edge] 유저기본조회 edge 추가 && Current Page 추가

---

src/main/java/com/gg/server/domain/match/service/MatchFindService.java
src/main/java/com/gg/server/domain/rank/dto/ExpRankDto.java
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/global/security/service/CustomOAuth2UserService.java
src/test/java/com/gg/server/game/GameControllerTest.java
src/test/java/com/gg/server/game/service/GameFindServiceTest.java
src/test/java/com/gg/server/game/service/GameServiceTest.java

- 신규 시즌 생성 시 티어 기본값 1로 추가되게 설정 (에러 사항 수정)
- ExpRankDto에 textColor 값 추가
- 이하동문

[GGBE4-68--Season-Tier-2] 신규 시즌 티어 기본값 추가 및 ExpRank에 textColor 추가

---

src/main/java/com/gg/server/domain/coin/service/CoinHistoryService.java
src/main/java/com/gg/server/domain/coin/type/HistoryType.java
src/main/java/com/gg/server/domain/item/service/ItemService.java

-  코인히스토리 내역 저장 명명 변경
- 선물했을 때 내역이 오지 않는 문제 확인하기(디비 저장은 확인완료) -> 누락된 코드 부분 추가
- 랭크전 승리(패배) 코인 획득 -> 랭크전 승리(패배) 로 수정
- 일반전 코인 획득 -> 일반전 참가 로 수정
- amount가 0일 때는 응답에서 제거, 프론트에서 0일 때 가리니까 페이지네이션이 꼬임현상

[GGBE4-67-style-userCoinHistory] 코인히스토리 내역 저장 명명 변경

---

src/main/java/com/gg/server/global/utils/aws/AsyncNewItemImageUploader.java

- ItemNotFound ImageUrl 설정하였습니다.
- itemNotFound 이미지 추가

[GGBE4-68--Season-Tier-2] itemNotFoundImageUrl 추가

---

src/main/java/com/gg/server/admin/user/controller/UserAdminController.java
src/main/java/com/gg/server/domain/rank/dto/ExpRankDto.java
src/main/java/com/gg/server/domain/rank/dto/RankDto.java
src/main/java/com/gg/server/domain/rank/redis/RankRedis.java
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/test/java/com/gg/server/domain/match/service/MatchTestUtils.java
src/test/java/com/gg/server/domain/rank/redis/RankRedisRepositoryTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- RankRedis에 textcolor 추가 및 userController 및 userAdminController 수정
- RankRedis에 textColor 추가하고 생성자를 수정했습니다.
- Controller에 ResponseEntity.ok 로 적은 부분을 dto로 리턴하도록 수정했습니다.
-

[GGBE4-72--rankredis-text-color-add] RankRedis에 textcolor 추가 및 userController 및 userAdminController 수정

---

src/main/java/com/gg/server/admin/megaphone/controller/MegaphoneAdminController.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/java/com/gg/server/domain/item/service/ItemService.java
src/main/java/com/gg/server/domain/megaphone/dto/MegaphoneUseRequestDto.java
src/main/java/com/gg/server/domain/megaphone/service/MegaphoneService.java
src/main/java/com/gg/server/domain/user/data/UserImage.java
src/main/java/com/gg/server/domain/user/service/UserService.java

- 아이템 체크 함수 병합
- 응답 형태 통일
- 아이템 체크 함수 병합 (확성기, 유저 서비스에 있던 함수 아이템서비스로 통합)
- 응답 형태 통일

[GGBE4-71--item-check-function] 아이템 체크 함수 병합 & 응답 형태 통일

---

src/main/java/com/gg/server/admin/user/data/UserImageAdminRepository.java

- UserImageAdminRepository에 Param 어노테이션을 추가했습니다.
- 기존쿼리에 ?1로 되있는 부분을 Param 어노테이션으로 받게끔 수정했습니다!
-

[GGBE4-73--userImageAdminRepository-add-Param] UserImageAdminRepository에 Param 어노테이션 추가

---

src/main/java/com/gg/server/domain/user/data/UserRepository.java
src/test/java/com/gg/server/domain/coin/service/UserCoinChangeServiceTest.java

- UserRepository의 getUserByIntraId에 optional을 추가했습니다.
-
-

[GGBE4-75--user-repository-optional-add] UserRepository optional 추가

---

src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/game/service/GameFindService.java
src/main/java/com/gg/server/domain/game/service/GameService.java

- main 브랜치에 작업했던 Lock 부분이 pr 에서 사라져서 다시 반영했습니다.
- game 상태 변경을 위해 행을 조회할 때 행에 대해 Lock 을 걸어 다른 곳에서 조회하지 못하도록 합니다.

[fix] game 점수 입력 시 synchronized 문제 해결 위해 Lock 추가

---

src/main/java/com/gg/server/domain/game/data/GameRepository.java

[FIX] param 오류 수정

---

src/main/java/com/gg/server/domain/game/data/GameRepository.java

- game 점수 입력 시 동시에 수정하는 것을 막기 위해 lock 을 추가했습니다.
- jpql 쿼리가 필요 없어서 삭제했습니다.

[merge] #265 jpql 쿼리 제거

---

src/main/java/com/gg/server/admin/user/data/UserImageAdminRepository.java

- userImageAdminRepository ?1 부분을 Param 어노테이션으로 수정
-
-

[GGBE4-78-userImageRepository-?1-refactor] userImageAdminRepository ?1 수정

---

src/main/java/com/gg/server/admin/game/data/GameAdminRepository.java
src/main/java/com/gg/server/admin/game/dto/GameLogAdminDto.java
src/main/java/com/gg/server/admin/game/service/GameAdminService.java
src/main/java/com/gg/server/domain/game/data/GameRepository.java

- /pingpong/admin/games api 수정
- 모든 상태의 게임을 조회하도록 수정했습니다.
- api 응답에 게임 상태 필드를 추가했습니다.

#274 fix admin page 에서 end 외의 게임 상태 보이게 수정하기

---

src/main/java/com/gg/server/admin/coin/controller/CoinPolicyAdminController.java
src/main/java/com/gg/server/admin/coin/dto/CoinPolicyAdminAddDto.java
src/main/java/com/gg/server/domain/coin/data/CoinHistoryRepository.java
src/main/java/com/gg/server/domain/coin/data/CoinPolicyRepository.java
src/main/java/com/gg/server/domain/coin/exception/CoinHistoryNotFoundException.java
src/main/java/com/gg/server/domain/coin/service/CoinHistoryService.java
src/main/java/com/gg/server/domain/coin/service/UserCoinChangeService.java
src/main/java/com/gg/server/domain/feedback/dto/FeedbackRequestDto.java
src/main/java/com/gg/server/domain/feedback/service/FeedbackService.java
src/main/java/com/gg/server/global/exception/ErrorCode.java
src/test/java/com/gg/server/domain/coin/service/UserCoinChangeServiceTest.java

- 코드 리뷰 대응 
- 이 외의 대응을 해야 할 부분은 부탁드립니다...ㅠ
- 리뷰 수정 마다 커밋을 하였습니다.
- 코인 외에도 피드백도 함께 한번에 수정을 하였습니다

[GGBE4-80-fix-style-mycoin] 코드 리뷰 대응(코인, 피드백)

---

src/main/java/com/gg/server/admin/item/service/ItemAdminService.java
src/main/java/com/gg/server/admin/receipt/dto/ReceiptAdminPageRequestDto.java
src/main/java/com/gg/server/admin/receipt/dto/ReceiptListResponseDto.java
src/main/java/com/gg/server/domain/item/data/Item.java
src/main/java/com/gg/server/domain/user/service/UserService.java

- ReceiptDto에 private 추가하여 @Getter 역할 살리기
- UserService에서 카카오 유저 랭크 테이블 조회시 try catch로 에러 방지

[GGBE4-79-Receipt-api] ReceiptDto에 private 추가 및 카카오 유저 에러 처리

---

src/main/java/com/gg/server/domain/coin/data/CoinHistoryRepository.java
src/main/java/com/gg/server/domain/coin/service/CoinHistoryService.java

- existsUserAttendedCheckToday의 쿼리에 endOfDay를 제외 (23시 59분 59초까지, 24시는 안들어가게)
-
-

[GGBE4-84--CoinHistoryRepository-Query-change] existsUserAttendedCheckToday 날짜 범위 변경

---

src/main/java/com/gg/server/admin/coin/service/CoinAdminService.java
src/main/java/com/gg/server/admin/coin/service/CoinPolicyAdminService.java
src/main/java/com/gg/server/admin/game/service/GameAdminService.java
src/main/java/com/gg/server/admin/noti/service/NotiAdminService.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/java/com/gg/server/domain/coin/service/UserCoinChangeService.java
src/main/java/com/gg/server/domain/feedback/service/FeedbackService.java
src/main/java/com/gg/server/domain/item/service/ItemService.java
src/main/java/com/gg/server/domain/megaphone/service/MegaphoneService.java
src/main/java/com/gg/server/domain/noti/service/NotiService.java
src/main/java/com/gg/server/domain/user/service/UserCoinService.java
src/main/java/com/gg/server/domain/user/service/UserFindService.java
src/main/java/com/gg/server/domain/user/service/UserService.java
src/main/java/com/gg/server/global/security/service/CustomUserDetailsService.java

- User'name'NotFoundException 중 'name' 삭제함
- (() -> new UserNotFoundException()); 을 .orElseThrow(UserNotFoundException::new); 로 수정
- 람다 -> 메소드 참조 방식으로 바꾼 것
- User'name'NotFoundException 중 'name' 삭제함
-

[GGBE4-82--UserNotFoundException] User'name'NotFoundException 수정

---

src/main/java/com/gg/server/domain/coin/service/UserCoinChangeService.java

[GGBE4-85--UserGameCoinResultDto-error] UserGameCoinResultDto error 수정

---

src/main/java/com/gg/server/admin/receipt/data/ReceiptAdminRepositorySearch.java

- 중복되는 정렬 제거 (Pageable, JPQL)
- Jpql 쿼리에서 order by 구문을 제거하였습니다.
- 불필요하게 두 번 정렬되던 것을 하나로 합쳤습니다.
-

[GGBE4-87-ReceiptAdminRepositorySearch] 중복되는 정렬 제거

---

src/main/java/com/gg/server/admin/game/service/GameAdminService.java

- findAllByStatus 를 findAll로 변경

[GGBE4-88-GameAdminRepository] GameAdminRepository 오류 수정

---

src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java

- 레디스 리스트가 이상하게 나오는 것을 수정했습니다.
- updateRankRedis를 고쳐서 제대로 반영되게 수정하였습니다.

[GGBE4-89-RankRedis-PPP] 랭크게임 후 레디스 에러 해결

---

src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java

- 랭겜 안한 유저도 랭크 리스트에 뜨는 에러를 해결했습니다.

[REFACTOR] RankRedisService updateRankUser 수정

---

src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java

- rank 업데이트 로직에서 tier 변동로직 transaction 따로 분리
-  ## 💻 작업사항 
-
-

tier업데이트 로직 분리

---

src/main/java/com/gg/server/domain/game/GameController.java
src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java
src/main/java/com/gg/server/domain/season/service/SeasonFindService.java

- update tier에서 season 찾아오는 로직 수정
-
-

fix season find

---

src/main/java/com/gg/server/domain/rank/dto/RankDto.java
src/main/java/com/gg/server/domain/rank/service/RankService.java

[REFACTOR] RankDto 수정

---

src/main/java/com/gg/server/domain/user/data/UserRepository.java
src/main/java/com/gg/server/global/utils/aws/AsyncNewUserImageUploader.java

- user 회원가입시 user table에 user image가 생성되지 않던 오류 수정
-
-

fix user image upload

---

src/main/java/com/gg/server/domain/tournament/data/Tournament.java

- `Tournament` Entity 수정
- 생성자 반환을 위한 static factory method `of` 추가
- 기존 `comments` column `contents`로 수정
- `from`에 대해서는 고민 필요

🔨 [Refactor] Tournament 정적 팩토리 메서드 of 추가

---

src/main/resources/db/migration/V3__migration_42gg_5th.sql

- 토너먼트 id를 fk로 사용중인 테이블에서 constraint `NO ACTION`으로 수정
- 기존 `CASCADE`로 constraint 걸었지만, default인 `NO ACTION`이 더 안전하다고 판단되어 수정합니다.
- [MySQL 공식문서](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html)
-  따로 설정하지 않을 경우, 4가지 options 중에 default 동작인 `NO ACTION`으로 설정되며 수정/삭제가 불가능 합니다.

🔨 [Refactor] 토너먼트 FK constraint NO ACTION으로 수정

---

.github/workflows/test-migrate-deploy.yml

- `test-migrate-deploy`
- TEST 서버 마이그레이션용 깃허브 액션
- 서버 이전으로 인해 깃허브 테스트 및 기존 action에 영향을 주지 않기 위해 시크릿 값 및 action을 새로 작성하였습니다.
- 도커 이미지명 및 사용하는 환경변수값 외 작동 방식은 기존과 동일합니다. 
- close #319

✨ feat: 마이그레이션 테스트 서버 배포용 github action 추가

---

src/main/java/com/gg/server/global/config/RedisConfig.java

- 기존 로컬 환경의 레디스를 Elasticache로 변경하며 CONFIG 에러가 발생합니다.
- Elasticache는 기본적으로 클러스터 설정을 변경할 수 없어 발생합니다.
- ConfigureRedisAction.NO_OP 빈을 추가하여 변경사항이 없음을 알리고 배포시 발생하는 에러를 개선합니다.
- #323

🐛  [Fix] ConfigureRedisAction Bean 추가

---

src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java
src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java

- `tournament` endpoint `tournaments`로 수정
- 단수형에서 복수형으로 수정하기로 얘기 되어서 수정합니다.

:hammer: [Refactor] tournament에서 tournaments로 엔드포인트 수정

---

src/main/java/com/gg/server/admin/noti/service/NotiAdminService.java
src/main/java/com/gg/server/global/config/RedisConfig.java

- #324 
- main으로부터 변경사항 dev 적용하기 위한 merge
- 해당 커밋이 합쳐져야 dev 브랜치 배포가 가능해집니다.

💚 [Merge] dev 브랜치 배포를 위한 redis hotfix commit 합치기

---

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
src/main/java/com/gg/server/domain/tournament/data/Tournament.java
src/main/resources/db/migration/V3__migration_42gg_5th.sql
src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java

- 토너먼트 유저와 게임을 관리하기 쉽게 Cascade 적용
- `V3__migration_42gg_5th`
> Data Grip 테이블 드랍
Sql 파일로 초기화
스프링 실행
mysql -u root -p {database 이름} < 2032311.sql
- `Tournament`: tournamentUser & tournamentGame 에 대해 CascadeType.ALL 로 설정
- `TournamentAdminService`: cascade 추가로 인한 매서드 로직 변경
- `TournamentAdminServiceTest`: ascade 추가로 인한 테스트 코드 변경
-
- close #350

🔨  [Refactor] Cascade 추가 

---

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java

-
- `TournamentAdminService`
-  `addTournamentUser`: 불필요한 쿼리 삭제 및 코드 수정
-  `deleteTournamentUser`: 불필요한 쿼리 삭제 및 코드 수정
- `TournamentAdminServiceTest`: 리팩토링으로 인한 코드 수정
- 각 서비스 매서드 별로 `@Transactional` 필요한 부분 추가
- close #353

🔨 [Refactor] 관리자 토너먼트 유저 추가 & 삭제 서비스 로직 리팩토링

---

src/test/java/com/gg/server/domain/tournament/controller/TournamentGameControllerTest.java
src/test/java/com/gg/server/utils/TestDataUtils.java

- 돌아가지 않던 테스트 코드 수정
- `TournamentGameControllerTest` : 난수 생성 하는 부분 0부터 오름차순으로 변경
- `TestDataUtils`: cascade 활용을 통한 코드 간략화
-

🐛  [Fix] findTournamentGameTest 테스트 코드 수정 및 TestDataUtils 매서드 수정

---

src/main/java/com/gg/server/global/security/handler/OAuthAuthenticationSuccessHandler.java
src/main/java/com/gg/server/global/security/jwt/utils/AuthTokenProvider.java

- refresh token 생성 로직 수정
- refresh token 생성 시 다른 유저와 동일한 토큰이 생성될 수 있는 문제가 있습니다. 현재 라이브 중인 서비스에서 발생하는 이슈로 인해 main 으로 바로 merge 요청합니다!
- refresh token 으로 access token 재 요청시 refresh token 에 담긴 값이 유저마다 고유하지 않을 수 있는 문제로 인해 유저 로그인이 다른 사용자로 바뀌는 문제가 있어서 refresh token 생성 로직 수정함
- close #394

[FIX] #394 refresh token create logic fix

---

.github/workflows/test-deploy.yml

- test-deploy 실패에 따라 다시 올립니다.
- docker rm 제거
- #405

🐛 [Fix] test-deploy 개선

---

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java
src/main/java/com/gg/server/global/exception/ErrorCode.java
src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java

- 토너먼트 생성 시, 제목 중복 체크 삭제
- 토너먼트 제목 중복 체크 로직 삭제
- 토너먼트 제목 중복 ErrorCode 삭제
- 테스트 코드 내 토너먼트 제목 중복 체크 로직 삭제
-
- close #398

💚 [Chore] 토너먼트 제목 중복 체크 제거

---

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
src/main/java/com/gg/server/global/config/ConstantConfig.java
src/main/java/com/gg/server/global/scheduler/TournamentScheduler.java
src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java
src/test/resources/application.yml

- pr을 진행할 필요없이 yml 값을 통해 스케줄링 및 토너먼트 생성 시간을 조절할 수 있게 합니다. 
- 제가 작성하기는 하였지만 이게 좋은 구조인지에 대해서는 의문이 들긴 합니다.
- 단위테스트 시 해당 값을 raw 값으로 설정해야 하는 부분 때문입니다.
- 의견 주시는 것에 따라 pr close 할지 결정하겠습니다
- yml 값에 의존하여 스케줄링 및 토너먼트 생성 시간 검증 수행
- #412

✨ [Feature] yml 을 활용한 content 값 의존

---

src/main/java/com/gg/server/domain/match/service/MatchTournamentService.java
src/main/java/com/gg/server/domain/tournament/data/Tournament.java
src/test/java/com/gg/server/domain/match/service/MatchTournamentTest.java

- 토너먼트 종료시 endTime 마지막 게임 endTime으로 갱신
- `MatchTournamentService` && `Tournament` : 시간 업데이트 로직 추가
- `MatchTournamentTest` : 로직 추가로 인한 테스트 코드 추가
-
- close #426

✨ [Feature] 토너먼트 종료시 endTime 갱신 로직 추가

---

src/main/java/com/gg/server/domain/match/service/MatchTournamentService.java
src/test/java/com/gg/server/domain/match/service/MatchTournamentTest.java

- 토너먼트 첫 8강 게임 진행시간 이슈 해결
- 기존 index `i` 잘못된 사용중인 부분 삭제
- `startTime` 업데이트하면서 게임 생성
- 8강 시간 확인하는 테스트코드 추가
- close #423

:bug: [Fix] 토너먼트 첫 8강 게임 진행시간 문제 수정

---

src/main/java/com/gg/server/domain/noti/service/sns/NotiMailSender.java
src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/global/security/cookie/CookieUtil.java

- 기존 refresh token을 js로 접근하여 읽을 수 있는 보안문제 해결
- secure cookie로 바꾸면서 access token재발급 api 수정 (front와 상의함)
- 기존 제대로 찍히지 않던 로그 수정
-
- #413

[Fix] refresh token secure cookie로 수정, log 제대로 찍히도록 수정 

---

src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/pchange/data/PChangeRepository.java

- findPChangeByGameId optional인데 여러개가 있을경우 생기는 500 에러 수정
- close #443

🐛 [Fix] findPChangeByGameId optional 버그 수정

---

src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java
src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminAddUserResponseDto.java
src/main/java/com/gg/server/domain/game/data/GameRepository.java
src/main/java/com/gg/server/domain/tournament/data/Tournament.java
src/main/java/com/gg/server/domain/tournament/dto/TournamentResponseDto.java
src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
src/main/java/com/gg/server/global/exception/ErrorCode.java
src/test/java/com/gg/server/domain/game/GameControllerTest.java
src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java

- 영선님 커맨트 중 수정할 수 있는 간략한 코드들을 수정하였습니다.
- `TournamentAdminService` : 빌더 패턴 사용하는 부분에 대해서는 추가 질문 남겨놓은 상태입니다.
- `GameController` : synchronized 빼고 db 락을 서비스 단으로 빼는 부분은 정확하게 이해하지를 못해서 일단 넘긴상태 입니다.
- `TournamentAdminController` : `@Validated` 삭제
- `TournamentAdminAddUserResponseDto`: `@NotNull` 삭제
- `GameRepository` && `TournamentService`: `findTeamsByGameId` 매서드 Optional 로 감싸서 반환으로 인한 수정
- `Tournament` : `String` 인자들 사이즈 명시
- `TournamentResponseDto` && `TournamentFindControllerTest`: snake case 수정
- `ErrorCode`: `findTeamsByGameId` 매서드 Optional 로 감싸서 반환으로 인한 에러 코드 추가
- `GameControllerTest` : 출력문 수정
- 
-
- close #372

🔨 [Refactor] main merge 전 dev 브랜치 수정사항

---

src/main/java/com/gg/server/global/security/cookie/CookieUtil.java

- 프론트에서 작업 완료되지 않아 httpOnly false로 되돌립니다.

:green_heart: [Chore] httpOnly false로 rollback

---

src/main/java/com/gg/server/domain/user/controller/UserController.java
src/main/java/com/gg/server/global/security/cookie/CookieUtil.java

- access token 쿠키 설정 rollback
- 참고 #436

💚 [Chore] access token 쿠키 설정 rollback

---

.github/workflows/main-deploy.yml
.github/workflows/test-deploy.yml

- deploy 할때 프로메테우스도 추가합니다
- deploy 할때 프로메테우스도 추가
- #453

✨ [Feat] deploy 프로메테우스 추가

---

.gitattributes

- OS별로 `LF`, `CRLF` 설정 차이에 대해 `.gitattributes`로 일치시킵니다.
- `text=auto` 
> When text is set to "auto", the path is marked for automatic end-of-line normalization. If Git decides that the content is text, its line endings are normalized to LF on checkin.
> text=auto Git은 가장 좋다고 생각하는 방식으로 파일을 처리합니다. 좋은 기본 옵션입니다.
- text 속성이 설정되지 않으면 git은 `core.autocrlf` configuration 변수로 파일 변환 여부를 결정합니다.
- [StackOverflow 참고](https://stackoverflow.com/questions/21472971/what-is-the-purpose-of-text-auto-in-gitattributes-file)
- [GitHub Docs 참고](https://docs.github.com/ko/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=mac)
```
git rm -rf --cached .
git reset --hard HEAD
``` 
- closed #475

💚 [Setting] .gitattributes로 crlf 처리

---

src/main/java/com/gg/server/domain/match/service/MatchTournamentService.java

- 토너먼트 첫 라운드 경기 랜덤 매칭 추가
- `findMatchUser()` -> `findSortedPlayers()` 함수 변경
- 8강의 경우 랜덤 매칭을 위해 random한 순서로 player에 대한 리스트를 반환
- 나머지의 경우 이전 경기 우승자를 순서대로 정렬한 리스트로 반환
-> 현재는 리스트로 순서에 의존적입니다. 이후에 `TournamentRound` enum 리팩토링 (#381 ) 진행하면서 함께 리팩토링 고민해보겠습니다.
- closed #451

✨ [Feature] 토너먼트 첫 라운드 경기 랜덤 매칭 기능 추가

---

src/main/java/com/gg/server/domain/rank/controller/RankV2Controller.java

- path variable annotation 빠진 부분 수정
- annotation 추가
- close #478

[FIX] #478 path variable add

---

src/main/java/com/gg/server/domain/rank/controller/RankV2Controller.java
src/main/java/com/gg/server/domain/rank/data/RankRepository.java
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/user/data/UserRepository.java

merge dev into main

---

src/main/java/com/gg/server/domain/rank/data/RankRepository.java
src/main/java/com/gg/server/domain/rank/service/RankService.java
src/main/java/com/gg/server/domain/user/data/UserRepository.java

- rank api에서 cache key가 중복되어 응답이 제대로 나가지 않는 문제 수정
-
-
- #489

[Bug] rank paging cache 중복 이슈 해결

---

src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java

:bug: [Fix] 토너먼트 전체 조회 테스트 에러 수정

---

src/main/java/com/gg/server/domain/rank/service/RankService.java
src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java

[Merge] merge dev into main

---

.github/workflows/test-code-validation.yml

- codecov github 액션에서 지속적인 업로드 실패 발생
- 버전을 최신 버전으로 변경
- #509

🐛 [Fix] codecov version to v3

---

src/test/java/com/gg/server/utils/annotation/DataJpaUnitTest.java
src/test/java/com/gg/server/utils/annotation/WebMvcUnitTest.java

- slice test용 애노테이션을 추가합니다
- @DataJpaUnitTest, @WebMvcUnitTest 추가
- #512

✨[Feature] slice test용 애너테이션 추가

---

src/main/java/com/gg/server/admin/megaphone/service/MegaphoneAdminService.java
src/main/java/com/gg/server/domain/megaphone/controller/MegaphoneController.java
src/main/java/com/gg/server/domain/megaphone/service/MegaphoneService.java
src/test/java/com/gg/server/admin/megaphone/service/MegaphoneAdminServiceUnitTest.java
src/test/java/com/gg/server/domain/megaphone/service/MegaphoneServiceUnitTest.java

- Megaphone 단위 테스트 입니다.
- useMegaphone 파라미터 수정
- 내부 로직에서 LocalDate.now()를 사용하던 것을 함수의 파라미터로 받도록 수정하였습니다.
- verify 추가
- 네이버 컨벤션 적용
- close #514

🧪 [Unit Test] Megaphone 단위 테스트

---

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java
src/main/java/com/gg/server/domain/game/service/GameService.java
src/main/java/com/gg/server/domain/match/service/MatchTournamentService.java
src/main/java/com/gg/server/domain/match/type/TournamentMatchStatus.java
src/main/java/com/gg/server/domain/tournament/data/Tournament.java
src/main/java/com/gg/server/domain/tournament/data/TournamentGameRepository.java
src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
src/main/java/com/gg/server/domain/tournament/type/RoundNumber.java
src/main/java/com/gg/server/domain/tournament/type/TournamentRound.java
src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
src/test/java/com/gg/server/domain/match/service/MatchBothServiceTest.java
src/test/java/com/gg/server/domain/match/service/MatchFindServiceUnitTest.java
src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java
src/test/java/com/gg/server/domain/match/service/MatchTournamentServiceTest.java
src/test/java/com/gg/server/domain/match/service/MatchTournamentServiceUnitTest.java
src/test/java/com/gg/server/domain/match/utils/GameTestUtils.java
src/test/java/com/gg/server/domain/match/utils/MatchIntegrationTestUtils.java
src/test/java/com/gg/server/domain/match/utils/TournamentGameTestUtils.java
src/test/java/com/gg/server/domain/match/utils/TournamentTestUtils.java
src/test/java/com/gg/server/domain/match/utils/UserTestUtils.java
src/test/java/com/gg/server/domain/tournament/data/TournamentUnitTest.java

- MatchTournamentSerivce 단위 테스트
- MatchTournamentSerivce 단위 테스트 작성
- `RoundNumber` enum 추가 -> `TournamentRound` 리팩토링했습니다.
- 같은 라운드를 찾는 함수 등도 `RoundNumber`을 사용하도록 수정했습니다.
- 테스트 util 파일들을 생성했습니다. 임의로 만들어서 일단 Match 하위에 만들었는데 의견 주시면 감사하겠습니다.
- `TournamentMatchStatus` 수정했습니다.
-> `UNNECESSARY`, `REQUIRED`, `ALREADY_MATCHED`, `NO_MORE_MATCHES`
- #524

🧪 [Unit Test] MatchTournamentService 단위 테스트

---

src/main/java/com/gg/server/domain/pchange/service/PChangeService.java
src/test/java/com/gg/server/domain/pchange/data/PChangeDataTest.java
src/test/java/com/gg/server/domain/pchange/service/PChangeServiceTest.java

- pchange 테스트 코드
-  close #495

🧪 [Unit Test] pchange 테스트 코드 추가

---

src/main/java/com/gg/server/domain/noti/service/NotiService.java
src/main/java/com/gg/server/domain/noti/service/SnsNotiService.java
src/main/java/com/gg/server/domain/noti/service/sns/NotiMailSender.java
src/test/java/com/gg/server/domain/noti/service/NotiServiceUnitTest.java
src/test/java/com/gg/server/domain/noti/service/SnsNotiServiceUnitTest.java
src/test/java/com/gg/server/domain/noti/service/sns/NotiMailSenderUnitTest.java

- `NotiDomainService` 단위 테스트 코드입니다.
- `NotiAdminService`의 PR에 변경된 파일 개수가 많아 부득이하게 PR을 나눈 점 양해바랍니다!
- `NotiDomainService` 단위 테스트 코드 추가
- `NotiService` 내 `notiMsg` 메서드 삭제
- `getMessage` 메서드에 `notiMsg`에 해당하는 내용 적용
- 자바독 추가
-
- close #469

🧪 [Unit Test] NotiDomainService 단위 테스트

---

src/main/java/com/gg/server/admin/season/data/SeasonAdminRepository.java
src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java
src/test/java/com/gg/server/admin/season/service/SeasonAdminServiceUnitTest.java
src/test/java/com/gg/server/domain/season/service/SeasonServiceUnitTest.java

- Season 단위 테스트 추가 pr 입니다.
- 추후 리팩토링이 필요해 보이는 부분들은 제외하고 단위테스트를 작성하였습니다.
- SeasonAdminService
- 불필요한 중복 쿼리문들을 수정하였습니다.
- 로직중 시즌 시간 유효성을 체크하고 판별하는 부분들 중 중복 체크를 하거나 불필요한 체크를 하는 로직들을 수정하였습니다.
- javadoc 추가 
-
- close #527

🧪 [Unit Test] Season 단위 테스트 추가

---

src/test/java/com/gg/server/admin/season/service/SeasonAdminServiceUnitTest.java
src/test/java/com/gg/server/domain/noti/service/NotiServiceUnitTest.java
src/test/java/com/gg/server/domain/noti/service/SnsNotiServiceUnitTest.java
src/test/java/com/gg/server/domain/noti/service/sns/NotiMailSenderUnitTest.java
src/test/java/com/gg/server/domain/season/service/SeasonServiceUnitTest.java
src/test/java/com/gg/server/domain/user/service/UserFindServiceUnitTest.java
src/test/java/com/gg/server/utils/annotation/UnitTest.java

- 폴더 구조 변경에 따른 에러 수정
-폴더 구조 변경에 따른 에러 수정
- #546

🐛 [Fix] 폴더 구조 변경

---

src/main/java/com/gg/server/admin/season/data/SeasonAdminRepository.java
src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java
src/test/java/com/gg/server/admin/season/service/SeasonAdminServiceUnitTest.java

- season test 오류 수정했습니다
-
- close #568

[FIX] #568 season admin controller test error fix

---

src/main/java/com/gg/server/admin/receipt/service/ReceiptAdminService.java
src/test/java/com/gg/server/admin/receipt/service/ReceiptAdminServiceUnitTest.java

- Receipt 단위 테스트 입니다
- 서비스 테스트만 추가
- dto, data는 자명한 로직이어서 생략하였습니다.
-
- close #538

🧪 [Unit Test] Receipt 단위 테스트

---

src/main/java/com/gg/server/admin/slotmanagement/service/SlotAdminService.java
src/test/java/com/gg/server/admin/slotmanagement/service/SlotAdminServiceUnitTest.java

- Slot management 서비스 단위 테스트 입니다.
- `javadoc` 추가
- 서비스단 테스트 코드
-
- close #570

🧪 [Unit Test] Slot management 단위 테스트

---

src/main/java/com/gg/server/admin/penalty/service/PenaltyAdminService.java
src/test/java/com/gg/server/admin/penalty/service/PenaltyAdminServiceTest.java
src/test/java/com/gg/server/data/manage/PenaltyTest.java
src/test/java/com/gg/server/domain/penalty/service/PenaltyServiceTest.java

- Penalty admin 서비스, domain 서비스에 대한 단위 테스트
- Penalty admin, domain 서비스 단위 테스트 추가
- Java docs 추가
- close #523

🧪 [Unit Test] Penalty 단위 테스트

---

src/main/java/com/gg/server/admin/item/dto/ItemUpdateRequestDto.java
src/main/java/com/gg/server/admin/item/service/ItemAdminService.java
src/main/java/com/gg/server/data/store/Item.java
src/test/java/com/gg/server/utils/ItemTestUtils.java

- Item entity에 dto 의존성 제거
- Item 생성자 매개변수에 dto를 사용중이었습니다. 해당 생성자 삭제 및 dto에서 Item 반환하는 메서드 추가했습니다.
- closed #582

🔨 [Refactor] Item entity에 dto 의존성 제거

---

src/main/java/com/gg/server/admin/rank/service/RankRedisAdminService.java
src/main/java/com/gg/server/admin/season/dto/SeasonCreateRequestDto.java
src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java
src/main/java/com/gg/server/admin/user/service/UserAdminService.java
src/main/java/com/gg/server/data/game/Game.java
src/main/java/com/gg/server/data/game/Rank.java
src/main/java/com/gg/server/data/game/Season.java
src/main/java/com/gg/server/data/game/redis/RankRedis.java
src/main/java/com/gg/server/domain/match/service/GameUpdateService.java
src/main/java/com/gg/server/domain/match/service/MatchFindService.java
src/main/java/com/gg/server/global/security/service/CustomOAuth2UserService.java
src/test/java/com/gg/server/admin/season/service/SeasonAdminServiceUnitTest.java
src/test/java/com/gg/server/domain/game/GameControllerTest.java
src/test/java/com/gg/server/domain/game/service/GameFindServiceTest.java
src/test/java/com/gg/server/domain/game/service/GameServiceTest.java
src/test/java/com/gg/server/domain/match/service/MatchFindServiceUnitTest.java

- game domain 쪽에서 dto 에 의존하고 있는 부분들 수정했습니다.
- test code 같이 수정했습니다.
- close #583

🔨 [Refactor] game entity 에 dto 의존성 제거

---

gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/item/ItemAdminRepository.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/megaphone/MegaphoneAdminRepository.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/noti/NotiAdminRepository.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/noti/NotiAdminRepositoryCustom.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/noti/NotiAdminRepositoryCustomImpl.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/penalty/PenaltyAdminRepository.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/penalty/PenaltyAdminRepositoryCustom.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/penalty/PenaltyAdminRepositoryCustomImpl.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/penalty/PenaltyUserAdminRedisRepository.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/receipt/ReceiptAdminRepository.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/receipt/ReceiptAdminRepositorySearch.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/slotmanagement/AdminSlotManagementsRepository.java
gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo/team/TeamAdminRepository.java
gg-pingpong-data/src/main/java/gg/pingpong/data/manage/Penalty.java
gg-pingpong-data/src/main/java/gg/pingpong/data/manage/type/PenaltyKey.java
gg-pingpong-data/src/main/java/gg/pingpong/data/manage/type/PenaltyType.java
gg-pingpong-data/src/main/java/gg/pingpong/data/noti/Noti.java

- admin repo import error 수정
- data 모듈로 위치 제대로 안옮겨진 type 클래스 수정
- close #588

🔨 [Refactor] admin repo import error 해결

---

gg-pingpong-api/src/main/java/gg/pingpong/api/admin/item/dto/ItemUpdateRequestDto.java
gg-pingpong-api/src/main/java/gg/pingpong/api/admin/item/service/ItemAdminService.java
gg-pingpong-api/src/main/java/gg/pingpong/api/admin/rank/service/RankRedisAdminService.java
gg-pingpong-api/src/main/java/gg/pingpong/api/admin/season/dto/SeasonCreateRequestDto.java
gg-pingpong-api/src/main/java/gg/pingpong/api/admin/season/service/SeasonAdminService.java
gg-pingpong-data/src/main/java/gg/pingpong/data/game/Season.java
gg-pingpong-data/src/main/java/gg/pingpong/data/store/Item.java

- api쪽 바뀐 entity에 맞춰 에러 수정
-
-
- #599

599 refactoring multi module api admin dir

---

.github/workflows/test-code-validation.yml
Dockerfile
build.gradle
gg-pingpong-utils/build.gradle

- test multimodule test ci 수정했습니다!
-
-
- #610

[TEST] multimodule test ci fix

---

build.gradle
gg-pingpong-admin-repo/build.gradle
gg-pingpong-api/build.gradle
gg-pingpong-api/src/main/java/gg/pingpong/api/admin/tournament/controller/request/TournamentAdminUpdateRequestDto.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/config/SwaggerConfig.java
gg-pingpong-api/src/test/java/gg/pingpong/api/user/season/SeasonTestController.java
gg-pingpong-repo/build.gradle
gg-pingpong-utils/build.gradle

#619 refactoring gradle dependency 수정

---

.github/workflows/main-deploy.yml
.github/workflows/test-deploy.yml

- cd 스크립트 잘못된 경로 수정
-
-
- #625

[BUG] #625 test, main deploy수정

---

gg-data/src/main/java/gg/data/party/Room.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/request/RoomShowChangeReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
gg-utils/src/main/java/gg/utils/exception/party/RoomAlreadyHiddenException.java
gg-utils/src/main/java/gg/utils/exception/party/RoomStatNotFoundException.java

- Admin방 show 여부 API
- 방 show여부를 Admin권한으로 변경하는 API 작성
- Room Entity에 UpdateRoomStatus 추가
- admin에 roomadmin Controller,Dto, Service 추가
- exception에 RoomAlreadyHidden 추가
- #655

✨ [Feature] AdminRoom show변경 API

---

gg-pingpong-api/src/main/resources/logback-spring.xml

- main 서버 로그 경로 수정했습니다.
- close #701

[FIX] #701 Fix/log path main

---

gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/UserRoomResDto.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java

- 상세조회 API에 intraId를 조건부로 Dto에 추가하는 로직
- if분기를 나누어 시작 및 참가자인 경우에 한해 intraid 조회 가능하게 작성
- closed #709

[feature] 상세조회 복면가왕 API 추가

---

gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/RoomController.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomCreateResDto.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java

- Long 이 아닌 Dto로 response 수정
-  Long 이 아닌 Dto로 response 수정
- closed #713

[Refactoring] 방 생성 이후 dto로 response 수정

---

gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminCommentResDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminRoomDetailResDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java

- Admin 권한으로 방 상세조회하는 API 작성
- Admin이 접근하므로 방에 들어왔던 모든 인원의 intraId를 함께 반환하여 comment 실명화
- closed #716

[feature] Admin 방 상세 조회 api 작성

---

gg-admin-repo/src/main/java/gg/admin/repo/penalty/PartyPenaltyAdminRepository.java
gg-data/src/main/java/gg/data/party/PartyPenalty.java
gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/controller/PartyPenaltyAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/request/PartyPenaltyAdminReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/requset/PartyPenaltyAdminReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/service/PartyPenaltyAdminService.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/user/report/controller/ReportController.java
gg-pingpong-api/src/main/java/gg/party/api/user/report/controller/request/ReportReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
gg-utils/src/main/java/gg/utils/exception/party/OnPenaltyException.java
gg-utils/src/main/java/gg/utils/exception/party/PartyPenaltyNotFoundException.java
gg-utils/src/main/java/gg/utils/exception/party/PenaltyNotFoundException.java

- 패널티 추가, 수정 API 및 패널티 부여 로직 수정 및 RoomService에서 패널티 유저 체크 로직 추가
- 패널티 추가 API
- 패널티 수정 API
- 패널티 중복 부여 로직에서 덮어씌우기가 아닌 따로따로 되도록 수정
- 방 참여, 방 만들기 로직에서 먼저 패널티 당한 유저 유효성 검사 추가
- close #728 #729

[FEAT] 패널티 추가, 수정 API 및 패널티 부여 로직 수정 및 RoomService에서 패널티 유저 체크 로직 추가

---

gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswer.java
gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerCheckList.java
gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerText.java
gg-data/src/main/java/gg/data/recruit/recruitment/Question.java
gg-recruit-api/src/main/java/gg/recruit/api/user/controller/ApplicationController.java
gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/RecruitApplyFormListReqDto.java
gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/RecruitApplyFormReqDto.java
gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/ApplicationResultResDto.java
gg-recruit-api/src/main/java/gg/recruit/api/user/service/ApplicationService.java
gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/RecruitApplyFormParam.java
gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/RecruitApplyParam.java
gg-recruit-api/src/test/java/gg/recruit/api/user/RecruitMockData.java
gg-recruit-api/src/test/java/gg/recruit/api/user/controller/ApplicationControllerTest.java
gg-recruit-api/src/test/java/gg/recruit/api/user/controller/RecruitmentControllerTest.java
gg-repo/src/main/java/gg/repo/recruit/user/application/ApplicationRepository.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
gg-utils/src/main/java/gg/utils/exception/custom/DuplicationException.java

- 지원하기 기능 추가했습니다.
- recruit mock data 클래스 utils 모듈에서 recruit-api 모듈로 옮겼습니다
- close #555

#555 feature 지원하기 api

---

gg-data/src/main/java/gg/data/recruit/application/Application.java
gg-data/src/main/java/gg/data/recruit/recruitment/Recruitments.java
gg-recruit-api/src/main/java/gg/recruit/api/user/controller/ApplicationController.java
gg-recruit-api/src/main/java/gg/recruit/api/user/service/ApplicationService.java
gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/DelApplicationParam.java
gg-recruit-api/src/test/java/gg/recruit/api/user/RecruitMockData.java
gg-recruit-api/src/test/java/gg/recruit/api/user/controller/ApplicationControllerTest.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
gg-utils/src/main/java/gg/utils/exception/custom/ForbiddenException.java

[FEAT] #556 feature 지원 취소 api

---

gg-data/src/main/java/gg/data/party/Comment.java
gg-pingpong-api/src/main/java/gg/party/api/admin/category/controller/CategoryAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/admin/category/service/CategoryAdminService.java
gg-pingpong-api/src/main/java/gg/party/api/admin/comment/controller/CommentAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/controller/PartyPenaltyAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/controller/request/PartyPenaltyAdminReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/controller/response/PartyPenaltyAdminResDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/service/PartyPenaltyAdminService.java
gg-pingpong-api/src/main/java/gg/party/api/admin/report/controller/response/CommentReportListResDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/report/controller/response/RoomReportListResDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/report/controller/response/UserReportListResDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminRoomDetailResDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminRoomResDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/TemplateAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/user/category/controller/CategoryController.java
gg-pingpong-api/src/main/java/gg/party/api/user/category/controller/response/CategoryListResDto.java
gg-pingpong-api/src/main/java/gg/party/api/user/category/service/CategoryService.java
gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/RoomController.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomStartResDto.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomFindService.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
gg-pingpong-api/src/main/java/gg/party/api/user/templates/controller/TemplateController.java
gg-pingpong-api/src/main/java/gg/party/api/user/templates/controller/response/TemplateListResDto.java
gg-pingpong-api/src/main/java/gg/party/api/user/templates/service/TemplateService.java

- 리팩토링 및 명세와 맞지 않아서 프론트와 불일치하는 부분 수정
- return Long이라던가 list로 나가는 부분들 수정
- #745

[Refactoring] party 전체 파일 리팩토링 및 프론트 api 명세와 맞지 않는 부분 수정

---

README.md

- 5기 README 업데이트
2024년 3월 19일 기준으로 올립니다.
- close #460

:memo: [Docs] 5기 README.md 업데이트

---

gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/TemplateAdminController.java
gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminCreateReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminUpdateReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
gg-pingpong-api/src/test/java/gg/party/api/admin/template/TemplateAdminControllerTest.java
gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java

- Admin 템플릿 추가, 제거, 수정에 대한 테스트 코드를 작성했습니다.
- Admin User인지 확인하는 로직은 추가하지 않았습니다.
- @Valid 옵션이 확인하는 로직은 추가하지 않았습니다.
- @Valid 옵션 추가 및 message 달아서 에러코드 판독을 쉽게 바꾸었습니다.
- 템플릿 추가, 제거, 수정에 대한 테스트 코드를 작성했습니다.
- closed #755

🧪 [Test] Admin 템플릿 추가, 제거, 수정 테스트코드 작성

---

gg-pingpong-api/src/main/java/gg/party/api/admin/comment/controller/request/CommentUpdateAdminReqDto.java
gg-pingpong-api/src/test/java/gg/party/api/admin/comment/CommentAdminControllerTest.java
gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java

- Admin이 댓글의 isHidden 옵션을 수정하는 API의 테스트 코드를 작성했습니다.
- 중복처리 로직을 추가하고 싶었는데, 저번 pr에서 에러코드를 수정한게 있는데, 그거랑 통일하고 싶어서 차후 머지되면 리팩토링으로 진행하겠습니다.
- closed  #763

🧪 [Test] Admin 댓글 Show 여부 변경 테스트코드 작성

---

gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminCreateReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminUpdateReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/request/RoomCreateReqDto.java
gg-pingpong-api/src/test/java/gg/party/api/admin/category/CategoryAdminControllerTest.java
gg-pingpong-api/src/test/java/gg/party/api/admin/template/TemplateAdminControllerTest.java
gg-repo/src/main/java/gg/repo/party/CategoryRepository.java
gg-utils/src/main/java/gg/utils/exception/party/DefaultCategoryNeedException.java

- 기타로 나오지 않고 etc 원문 그대로 나오는 버그 수정
- admin 템플릿 수정 API에서 최소 최대인원 검증 안하는 버그 수정
- 기타로 나오지 않고 etc 원문 그대로 나오는 버그 수정
- admin 템플릿 수정 API에서 최소 최대인원 검증 안하는 버그 수정
- 및 그에 따라 바뀌는 Test 코드 수정 및 추가
- closed #773

🐛 [Bug] 카테고리가 etc로 나오는 버그 && admin 템플릿 수정에서 최대인원 최소인원에 상관없이 저장되는 버그

---

gg-pingpong-api/src/main/java/gg/party/api/admin/penalty/controller/request/PartyPenaltyAdminReqDto.java
gg-pingpong-api/src/main/java/gg/party/api/user/category/service/CategoryService.java
gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
gg-repo/src/main/java/gg/repo/party/PartyPenaltyRepository.java

- 패널티 수정 및 처리부분에서 생긴 버그를 잡았습니다.
- 패널티 수정할때 0으로 바뀌지 않게 @Valid 조절한 부분 수정
- 패널티 조회할때 한 객체에 여러개의 패널티 담으려던 부분 수정
- -closed #784

🐛 [Bug] party penalty 여러번 받은 유저는 영원히 사용할 수 없는 버그 수정 및 (패널티 수정) 버그 수정

---

gg-pingpong-api/src/main/java/gg/party/api/user/category/service/CategoryService.java
gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java
gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java
gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java
gg-pingpong-api/src/test/java/gg/party/api/user/category/CategoryControllerTest.java
gg-repo/src/main/java/gg/repo/party/PartyPenaltyRepository.java

- 바꿨음에도 불구하고 안되던 버그 수정
- Top 키워드 사용해서 가져오게 수정 및 테스트코드 작성
- -closed #787

🐛 [Bug] 방 생성시 카테고리를 프론트에서 받지 못하는 버그

---

build.gradle
gg-admin-repo/src/main/java/gg/admin/repo/recruit/manage/RecruitResultMessageRepository.java
gg-admin-repo/src/test/java/gg/admin/repo/TestSpringBootApplication.java
gg-admin-repo/src/test/java/gg/admin/repo/recurit/maage/RecruitResultMessageRepositoryTest.java
gg-admin-repo/src/test/resources/application.yml
gg-data/src/main/java/gg/data/recruit/manage/ResultMessage.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminController.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminService.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminServiceImpl.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/RecruitmentResultMessageDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/RecruitmentResultMessageDtoMapper.java
gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminControllerUnitTest.java
gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentResultMessageIntegrationTest.java
gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentResultMessageAdminServiceImplTest.java
gg-repo/src/main/java/gg/repo/recruit/user/manage/RecruitResultMessageRepository.java

- 결과 메시지 등록 api입니다
- 결과 메시지 등록 기능 구현
- 단위 테스트, 통합 테스트 작성 및 문서화
- mapping을 편하게 하기 위해 mapstruct 라이브러리 추가 (리플렉션을 사용하지 않아서 안전합니다)
- #564

✨ [Feature] 결과 message 등록 api

---

gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentAdminIntegrationTest.java
gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceUnitTest.java

- 공고 삭제 API
- 공고 삭제 API 추가
- service 단위 테스트, 통합테스트
- closed #551

✨ [Feature] 공고 삭제 API

---

gg-pingpong-api/src/main/java/gg/pingpong/api/admin/store/controller/response/CoinPolicyAdminResponseDto.java
gg-pingpong-api/src/main/java/gg/pingpong/api/admin/store/service/CoinAdminService.java
gg-pingpong-api/src/main/java/gg/pingpong/api/admin/store/service/CoinPolicyAdminService.java
gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/controller/CoinAdminControllerTest.java
gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/controller/CoinPolicyAdminControllerFailTest.java
gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/controller/CoinPolicyAdminControllerTest.java
gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/service/CoinAdminServiceTest.java
gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/service/CoinAdminServiceUnitTest.java
gg-pingpong-api/src/test/java/gg/pingpong/api/admin/store/service/CoinPolicyAdminServiceUnitTest.java

- CoinPolicyAdminService 단위 테스트 코드를 추가하였습니다.
- test 폴더 내 store 패키지 생성 및 coin 패키지 이동
- CoinPolicyAdminResponseDto 내에 UserNotFoundException 추가
- CoinPolicyAdminService 단위 테스트 코드 추가
- CoinPolicyAdminService, CoinAdminService javadoc 추가
-
- #471

🧪 [Unit Test] CoinPolicyAdminService 단위 테스트 코드

---

gg-admin-repo/src/main/java/gg/admin/repo/recruit/ApplicationAdminRepository.java
gg-admin-repo/src/test/java/gg/admin/repo/recruit/ApplicationAdminRepositoryTest.java
gg-data/src/main/java/gg/data/recruit/application/Application.java
gg-data/src/main/java/gg/data/recruit/application/RecruitStatus.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentApplicantResultResponseDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentApplicantResultsResponseDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentAdminControllerUnitTest.java
gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java

- 지원자 결과 목록 조회 api 입니다
- 지원자 결과 목록 조회 기능 구현 및 단위 테스트 작성
- RecruitStatus의 경우 정책상 존재하지 않는 경우가 존재해서 null 처리 허용
- RecruitStatus Application 간 양방향 매핑 처리 및, db 내용에 맞게 one to one으로 변경
- #580

✨ [Feature] 지원자 결과 목록 조회 api

---

gg-admin-repo/src/main/java/gg/admin/repo/recruit/RecruitmentAdminRepository.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/exception/GlobalExceptionHandler.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/InterviewRequestDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentsResponse.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/FormParam.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/result/AllRecruitmentsResult.java
gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceUnitTest.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java

- dto 수정 및 validation 추가
- 공고 조회 API 페이지네이션을 위한 `totalPage`컬럼 추가
- request dto에서 `@NotNull` validation 추가
- `BusinessException` handler 추가

🐛 [Fix] 공고 admin API dto 수정 및 validation 추가

---

gg-admin-repo/src/main/java/gg/admin/repo/recruit/RecruitmentAdminRepository.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/CheckItemAdminResDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/FormDetailAdminResDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentAdminDetailResDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/result/CheckItemAdminSvcDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/result/FormDetailAdminSvcDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/result/RecruitmentDetailAdminSvcDto.java
gg-recruit-api/src/test/java/gg/recruit/api/admin/integration/RecruitmentAdminIntegrationTest.java

- admin쪽 공고 상세조회 api입니다
-
-
- #811

[FEAT] #811 admin recruit detail api

---

gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/FormResDto.java
gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/MyApplicationDetailResDto.java

- api response format 수정
- api응답 포멧 맞추고 오타 수정했습니다
-
-

[FIX] #815 api response format

---

gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/RecruitmentRequestDto.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java
gg-recruit-api/src/main/java/gg/recruit/api/admin/service/param/CheckListContent.java
gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/MyApplicationDetailResDto.java

- form -> forms
- content -> contents
- 이렇게 데이터 이름 수정했습니다
-
-
- #819

[FIX] api req, resp data format

---

gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomFindService.java
gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java

- 참여하지 않은 방이 참여한 방 목록에 보이는 버그 수정
- 레포지토리에서 찾아올 때 isexist가 true일 때만 반환하게 수정
- closed #821

🐛 [Bug] 방 나간 이후 참여한 방 목록에서 보이는 버그 #821

---

gg-data/src/main/java/gg/data/recruit/application/Application.java
gg-pingpong-api/src/main/resources/db/migration/V2.1__recruit_update_status_length.sql
gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/InterviewRequestDto.java

- Application status mysql 타입 길이 수정
-
-
-

[FIX] # 831 Application status len

---

gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/config/SecurityConfig.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/handler/OauthAuthenticationFailureHandler.java

- auth error시에 whitelabel error page뜨지 않도록 프론트쪽 error페이지로 redir시켰습니다
-
-
- #833

[FIX] #833 error redir page설정

---

gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
gg-pingpong-api/src/test/java/gg/party/api/admin/template/TemplateAdminControllerTest.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
gg-utils/src/main/java/gg/utils/exception/party/RoomMinMaxTime.java

- 직접 템플릿 작성하다보니 인원 수 혹은 시간에 대한 예외처리가 필요할 것 같아서 추가했습니다.
- 템플릿 예외처리 익셉션 추가
- 추가된 익셉션에 맞는 테스트 코드 추가
- closed #827

[feature] 게임 템플릿 인원에 대한 예외처리 추가

---

gg-data/src/main/java/gg/data/agenda/Agenda.java
gg-data/src/main/java/gg/data/agenda/AgendaAnnouncement.java

- Entity 작성
- agenda
- agenda announcement 
- Entity 작성
- agenda
- agenda announcement 
- close #840

✨ [Feature] agenda, agenda_announcement Entity 작성

---

gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
gg-data/src/main/java/gg/data/agenda/Ticket.java

-agenda_profile, ticket Entity 작성
-agenda_profile, ticket Entity 작성
- - close  #838

✨ [Feature] agenda_profile, ticket Entity 작성

---

build.gradle
gg-agenda-api/src/main/java/gg/agenda/GgAgendaApiApplication.java
gg-agenda-api/src/test/java/gg/agenda/GgAgendaApiApplicationTests.java
gg-agenda-api/src/test/resources/application.yml
gg-data/src/main/java/gg/data/agenda/Agenda.java
gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
gg-pingpong-api/src/main/java/gg/PingpongApiApplication.java

- 멀티 모듈 의존성이 누락되어 빌드가 안됨
- 엔티티 누락 사항
- LocalDateTime이 String으로 되어있음 (Agenda)
- UUID가 byte[]로 되어있음 (Agenda, AgendaTeam)
- 멀티 모듈 의존성 추가
- 엔티티 수정
- Agenda
-  AgendaTeam
- 테스트용 yml 파일 추가
- 멀티 모듈 의존성 추가
- build.gradle에 의존성 추가
- basePackage에 gg.agenda.api 추가
- 엔티티 수정
- Agenda : 타입 수정
-  AgendaTeam : 타입 수정
- closed #869

869 refactoring 멀티 모듈 의존성 추가 및 엔티티 수정

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/dto/AgendaResponseDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/dto/AgendaSimpleResponseDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
gg-agenda-api/src/test/java/gg/agenda/api/user/controller/AgendaControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/controller/dto/AgendaSimpleResponseDtoTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/service/AgendaServiceTest.java
gg-data/src/main/java/gg/data/agenda/Agenda.java
gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java

- 현재 진행 중인 Agenda 현황 조회 API 
- controller, service, repository 로직 구현
- official 여부 및 deadline 기준으로 정렬
- `AgendaSimpleResponseDto` 구현
- JSON 변환시 원시타입 매핑이 안되는 문제로 인해 `boolean` -> `Boolean`으로 변경
-  `Agenda`, `AgendaResponseDto`, `AgendaSimpleResponseDto`
- `toList()` -> `Collectors.toList()`로 변경 (2e31df57ec9ec6e59febc7fe697dbd6520b88e1d, 1f9a0cb2c4eb3991b299dc6b199f53caf99a6b84)
- closed #858

✨ [Feature] #858 Agenda 현황 전체 조회 API

---

build.gradle
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamCreateReqDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
gg-data/src/main/java/gg/data/agenda/AgendaTeamProfile.java
gg-data/src/main/java/gg/data/agenda/Ticket.java
gg-data/src/main/java/gg/data/agenda/type/Coalition.java
gg-data/src/main/java/gg/data/agenda/type/Location.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/info/OAuthUserInfo.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/info/impl/FortyTwoOAuthUserInfo.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/info/impl/KakaoOAuthUserInfo.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/service/CustomOAuth2UserService.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/utils/external/ApiUtil.java
gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql

- Auth 받아올때 UserProfile 비어있을경우 작성하게 수정
- Team 생성 API 누락된 코드 추가로 작성
- Team 생성 누락된 코드에 대한 Testcode 작성
- 팀 생성할 때 중간 테이블 안만들던 이슈 해결
- 팀 생성할 때 중간 테이블이 없음으로서 중복참가가 되던 버그 해결
- 팀 생성할 때 티켓 줄이지 않던 버그 해결
- -closed #872

✨ [Feature] #872 Auth 받아올 때 AgendaProfile 작성

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java

- 지난 Agenda 목록 조회 (페이지네이션) 기능 추가
- `GET /agenda/history`
- controller - `agendaListHistory` 메서드 추가
- service - `findHistoryAgendaList` 추가
- repostiory - `findAllByStatusIs(Pageable, AgendaStatus)` 추가
- `GetAgendaListHistory` 테스트 코드 추가
- closed #860

✨ [Feature] #860 지난 Agenda 조회 API

---

README.md

Update 6th working at README.md
- 6기 리드미 업데이트
- 개발 기간 추가
- 팀소개 추가
- ERD 변경본 추가
- 커버리지 개선 추가
- 페이지 캡쳐본 추가
- close #880

🔨 [Refactoring] 6th README update

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamCreateReqDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamDetailsReqDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamCreateResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamDetailsResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamMateDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-data/src/main/java/gg/data/agenda/AgendaProfile.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/service/CustomOAuth2UserService.java
gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java

- 팀 상세조회 API 작성
- AgendaProfile에 intraId 컬럼 추가
- 그에 따라 sql문 수정 및 mock데이터 빌더패턴 쓰는 곳 수정
- -closed #841

✨ [Feature] Team 상세조회 API #841

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/MyTeamSimpleResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java

- 내 팀 간단조회 API 작성
- 내 팀 간단조회 TEST 코드 작성
- -closed #842

✨ [Feature] 내 Team 간단조회 API #842

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamCreateReqDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/OpenTeamResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java

- Status가 Open이면서 isPrivate가 False인 팀 리스트 전체 조회 API 작성
- -closed #847

✨ [Feature] 모집중인 팀 리스트 전체 조회 API #847

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/ConfirmTeamResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java

-  Confirm 상태의 팀 리스트를 전체 조회 하는 API 작성
- -closed #848

✨ [Feature] 확정된 팀 리스트 전체 조회 API #848

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/request/AgendaAnnouncementAdminUpdateReqDto.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/service/AgendaAnnouncementAdminService.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/service/AgendaAnnouncementAdminServiceTest.java
gg-data/src/main/java/gg/data/agenda/AgendaAnnouncement.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java

✨ [Feature] Admin 공지사항 수정 및 삭제하기
- Admin 공지사항 수정 및 삭제하기 
- Admin 공지사항 수정 및 삭제하기 기능 구현
- closed #889

✨ [Feature] Admin 공지사항 수정 및 삭제하기 #889

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/request/TeamUpdateReqDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-data/src/main/java/gg/data/agenda/Agenda.java
gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamFixture.java
gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamProfileFixture.java

- 팀 수정 API 작성
- 기존 로직 중 잘못된 부분 수정
- 팀 수정 API 작성
- 팀 수정 테스트 코드 작성
- 팀 로직 수정
- 에러코드 수정
- 팀 생성할때가 아닌 confirm할때 current team count 올리게 수정
- 팀 수정 API 작성
- 에러코드 -> AGENDA_UPDATE_LOCATION_CONFLICT(409, "AG", "지역을 변경할 수 없습니다.") 를
UPDATE_LOCATION_NOT_VALID(400, "AG", "지역을 변경할 수 없습니다.") 로 수정
- -closed #850

✨ [Feature] 팀 내용 수정하기 API #850

---

gg-utils/src/testFixtures/java/gg/utils/AgendaTestDataUtils.java
gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaAnnouncementFixture.java
gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaTeamFixture.java

- Fix TestFixture checkstyle
- Fix TestFixture checkstyle
-
- closed #914

🐛 [Bug] Fix TestFixture checkstyle #914

---

gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
gg-data/src/main/java/gg/data/agenda/Ticket.java
gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaProfileFixture.java
gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/TicketFixture.java

- 티켓 Setup 만드는 API 작성
- 티켓 Setup API 테스트 코드 작성
- -closed #908

✨ [Feature] 티켓 발급 시작 API #908

---

gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/response/TicketCountResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java

- 내 가진 티켓 확인하는 API 작성
- 내 가진 티켓 확인하는 API에 대한 테스트 코드 작성
- -closed #910

✨ [Feature] 가진 티켓 확인 API #910

---

gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaTeamAdminRepository.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminServiceTest.java

- Admin AgendaTeam 전체 조회하기
- Admin AgendaTeam 전체 조회하기
- closed #898

✨ [Feature] Admin AgendaTeam 전체 조회하기 #898

---

gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/response/TicketHistoryResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/TicketFixture.java

- 티켓 히스토리 조회 API 작성
- 티켓 히스토리 조회 TEST 코드 작성
- -closed #911

✨ [Feature] 티켓 히스토리 조회 API #911

---

.github/workflows/checkstyle-validation.yml
gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaProfileFixture.java

- Checkstyle validation - TestFixture 추가
TestFixture에 대한 Checkstyle validation으로 인해 test-deploy 실패하는 경우가 많아져서  
Github Action의 Checkstyle validation에 TestFixture에 대한 검증을 추가합니다.
- Chkecstyle validation - TestFixture 추가
- closed #922

🔨 [Refactoring] Checkstyle validation - TestFixture 추가 #922

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/CurrentAttendAgendaListResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java

-내가 참여 중인 대회 보기 API 
-내가 참여 중인 대회 보기 API 
- closed #854

✨ [Feature] 내가 참여 중인 대회 보기 API #854

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java

- Agenda Admin URL 변경
- change `/admin/agenda` to `/agenda/admin`
-
- closed #926

🔨 [Refactoring] Agenda Admin URL 변경 #926

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/OpenTeamResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java

- Team 생성 API에서 쿼리에러 나는 부분 수정
- Open Team List API에서 Coalition 추가
- -closed #930

🐛 [Bug] Team Create API 쿼리 잘못 쓴 부분 수정 및 Open Team Coaliton 추가 #930

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/validator/AgendaScheduleValidator.java

- AgendaCreateReqDto Custom Validtor 예외처리 로직 추가
- AgendaScheduleValidator
- null guard 추가
- AgendaCreateReqDto
- JsonFormat 어노테이션 추가
-
- closed #934

🐛 [Bug] AgendaCreateReqDto Custom Validtor 예외처리 로직 추가 #934

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java

- AgendaCreateReqDto DateTImeFormat이 UTC로 설정
- AgendaCreateReqDto DateTImeFormat이 UTC로 설정
-
- closed #936

🐛 [Bug] AgendaCreateReqDto DateTImeFormat 수정 #936

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/response/AgendaAdminResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaSimpleResDto.java

- 🐛 [Bug] Agenda 조회 API 응답 필드 추가
- `GET /agenda/admin/request/list` agendaKey 필드 추가
- `GET agenda list` posterUrl 필드 추가
- `GET /admin/team/list` 필드 값 오류
- `GET /admin/agenda/list` isOfficial 필드값 확인
- closed #951

🐛 [Bug] Agenda 조회 API 응답 필드 추가 #951

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/response/AgendaAdminSimpleResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java

- ✨ [Feature] Agenda Admin 목록 조회 기능 구현
- Agenda Admin 목록 조회 기능 구현 `GET /agenda/admin/list`
- closed #954

✨ [Feature] Agenda Admin 목록 조회 기능 구현 #954

---

gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
gg-pingpong-api/src/main/java/gg/pingpong/api/global/security/service/CustomOAuth2UserService.java

- application.yml 완성본이 만들어지지 않아(슬랙 API부분) 일단 string으로 바꿔두고 차후 수정하겠습니다.
- -closed #957

[Bug] Value yml참조가 아닌 String으로 수정

---

gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaAdminRepository.java
gg-admin-repo/src/main/java/gg/admin/repo/agenda/TicketAdminRepository.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/TicketAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/request/TicketAddAdminReqDto.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/response/TicketAddAdminResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/service/TicketAdminService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/CurrentAttendAgendaListResDto.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaprofile/AgendaProfileAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/ticket/TicketAdminControllerTest.java
gg-data/src/main/java/gg/data/agenda/Ticket.java

-admin 티켓생성, 내가 참여했던 agenda 목록 response 수정
-admin 티켓생성, 내가 참여했던 agenda 목록 response 수정
-
- closed #944

✨ [Feature] Admin 티켓 생성 API #944

---

gg-utils/src/main/java/gg/utils/sns/slack/SlackbotApiUtils.java

- 🐛 [Bug] Slack 및 Mail 모듈 URL 수정 
- INTRA_EMAIL_SUFFIX.getValue() 수정
- params MultiValueMap -> HashMap 변경
- closed. #961

🐛 [Bug] Slack 및 Mail 모듈 URL 수정 #961

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/response/AgendaAdminResDto.java

- 🐛 [Bug] Agenda Admin 전체조회 필드 추가
- agendaContent, agendaMinTeam 필드추가
- closed #962

🐛 [Bug] Agenda Admin 전체조회 필드 추가 #962

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/response/TeamDetailsResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-data/src/main/java/gg/data/agenda/AgendaTeam.java

- 팀 상세조회에서 isPraivate 컬럼 추가
- confirm 상태의 팀이 status Open상태의 아젠다에서 폭파 가능하게 수정
- Transaction 전파의 잘못사용으로 인한 500에러 처리
-  -closed #960

✨ [Feature] Confirm된 Team DeadLine 전까지 취소 가능하게 수정 #960

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendaannouncement/service/AgendaAnnouncementAdminService.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/controller/AgendaAnnouncementController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/service/AgendaAnnouncementService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/service/AgendaAdminServiceTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendaannouncement/controller/AgendaAnnouncementAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminServiceTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendaannouncement/controller/AgendaAnnouncementControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendaannouncement/service/AgendaAnnouncementServiceTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
gg-repo/src/main/java/gg/repo/agenda/AgendaAnnouncementRepository.java
gg-utils/src/main/java/gg/utils/dto/PageResponseDto.java

- 🔨 [Refactoring] Pagenation 응답 totalSize 추가
- PageResponseDto 추가
- AgendaAdminController
- AgendaAnnouncementAdminController
- AgendaTeamAdminController
- AgendaController
- AgendaAnnouncementController
- AgendaProfileController
- AgendaTeamController
- TicketController
- closed #953

🔨 [Refactoring] Pagenation 응답 totalSize 추가 #953

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/validator/AgendaCapacityValidator.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/response/TicketCountResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
gg-agenda-api/src/test/java/gg/agenda/api/AgendaMockData.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-data/src/main/java/gg/data/agenda/Agenda.java
gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
gg-utils/src/testFixtures/java/gg/utils/AgendaTestDataUtils.java

- current 팀 -- 하는 부분 status확인하게 수정
- agenda 최소인원 최대인원 같아도 되게 수정
- ticket Count에 setup티켓 유무 필드 추가
- -closed #969

🐛 [Bug] Agenda current Team count가 음수가 되는 버그 #969

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileDetailsResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/IntraProfileUtils.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraAchievement.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraImage.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraImageVersion.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraProfile.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraProfileResponse.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
gg-auth/src/main/java/gg/auth/FortyTwoAuthUtil.java
gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
gg-utils/src/main/java/gg/utils/exception/custom/AuthenticationException.java

- ✨ [Feature] AgendaProfile 상세조회 - 사진 및 업적 조회 기능 추가
- AgendaProfile 상세조회 - 사진 및 업적 조회 기능 추가
- IntraProfileUtils 추가
- FortyTwoAuthUtil 리펙토링
- IntraProfile 클래스 추가
-
- closed #940

✨ [Feature] AgendaProfile 상세조회 - 사진 및 업적 조회 기능 추가 #940

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaHostController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileDetailsResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/MyAgendaProfileDetailsResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/IntraProfileUtils.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaHostControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java

- ✨ [Feature] 다른 사용자 AgendaProfile 조회 API 
- 기존의 AgendaProfileDetailResDto를 MyAgendaProfileDetailResDto로 변경
- AgendaProfileDetailResDto에는 TicketCount 제외하고 동일하게 사용
- IntraId를 Path Variable로 추가
- 프로필 상세 조회 `GET /agenda/profile/{intraId}`
- 참여했던 대회 조회 `GET /agenda/profile/history/list/{intraId}`
- 개최중인 대회 조회 `GET /agenda/host/current/list/{intraId}`
- 개최했던 대회 조회 `GET /agenda/host/history/list/{intraId}`
-
- #977

✨ [Feature] 다른 사용자 AgendaProfile 조회 API #977

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/SnsMessageUtil.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/controller/AgendaAnnouncementController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaannouncement/service/AgendaAnnouncementService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/main/java/gg/agenda/api/utils/AgendaSlackService.java
gg-agenda-api/src/main/java/gg/agenda/api/utils/SnsMessageUtil.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java

AGENDA 공지사항 작성 | 해당 AGENDA 참가자
AGENDA 취소 | 해당 AGENDA 참가자
AGENDA 종료 | 해당 AGENDA 참가자
AGENDA 확정 | 해당 AGENDA 참가자
팀 CONFIRM | 해당 팀 참가자
팀 폭파 | 해당 팀 참가자
팀에 누군가 참가 | 해당 팀 참가자
팀에 누군가 나감 | 해당 팀 참가자
AGENDA 최대 팀 최대 도달 | AGENDA 개최자
AGENDA 최대 팀 최소 도달 | AGENDA 개최자
- 에 대한 slack API 작성
- AgendaTeamCancel API 작성
- -closed #971

✨ [Feature] 상황에 맞게 slack API 보내는 API 작성 #971

---

gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaTeamProfileAdminRepository.java
gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java

- 🐛 [Bug] GET /agenda/team/my 내 팀 정보 조회에서 NonUniqueResultException 발생
- AgendaTeam Admin updateAgendaTeam()
- 이미 다른 팀에 참가한 경우 AGENDA_TEAM_FORBIDDEN
- Agenda requset addAgenda()
- 이미지가 없는 경우 NULL
-
- closed #983

🐛 [Bug] GET /agenda/team/my 내 팀 정보 조회에서 NonUniqueResultException 발생 #983

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-data/src/main/java/gg/data/agenda/AgendaTeam.java
gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamProfileRepository.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java

- 🔨 [Refactoring] Agenda History 조회시 CONFIRM 상태 추가 
- 🔨 [Refactoring] Agenda History 조회시 CONFIRM 상태 추가 
-
- closed #986

🔨 [Refactoring] agenda api 쿼리 조회 성능 개선 #986

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/controller/AgendaTeamController.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendateam/AgendaTeamControllerTest.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java

- 팀원과 팀장 나가기의 API 분리
- 그에 따라 테스트 코드 작성
- -closed #993

✨ [Feature] 팀원 나가기와 팀장 나가기 API 분리 #993

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java

- 🔨 [Refactoring] 진행중 대회 전체조회 API 분리
- 🔨 [Refactoring] 진행중 대회 전체조회 API 분리
-
- closed #992

🔨 [Refactoring] 진행중 대회 전체조회 API 분리 #992

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/service/AgendaAdminServiceTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java
gg-data/src/main/java/gg/data/agenda/AgendaPosterImage.java
gg-pingpong-api/src/main/resources/db/migration/V3__agenda.sql
gg-repo/src/main/java/gg/repo/agenda/AgendaPosterImageRepository.java
gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaPosterImageFixture.java

- AgendaPostImage 테이블 추가
- AgendaPostImage 추가 로직 작성
- AgendaPostImage 테스트 코드 작성
- closed #984

✨ [Feature] PosterImage 수정시 사용 여부를 알기위한 db table 추가 #984

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java

- AgendaService 와 AgendaAdminService의 아젠다 생성 및 수정 부분에 바이트 사이즈 확인로직 추가
- -closed #996

🐛 [Bug] 포스터 이미지 없이 보내도 0바이트짜리 포스터 이미지가 생성되는 버그 #996

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendateam/service/AgendaTeamService.java
gg-repo/src/main/java/gg/repo/agenda/AgendaTeamRepository.java

- ConfirmTeam 조회에서 IsPraivate dataJpa 삭제
- -closed #1000

🐛 [Bug] Agenda Confirm 상태 팀 조회 안되는 버그 #1000

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileDetailsResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/IntraProfileResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/IntraProfileUtils.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraProfile.java
gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/intraprofile/IntraProfileResponse.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
gg-auth/src/main/java/gg/auth/FortyTwoAuthUtil.java
gg-utils/src/main/java/gg/utils/exception/ErrorCode.java

- AgendaProfile정보 조회 API 분리
- 42IntraProfile정보 조회 API 분리
- Auth Refresh 안되는 부분 Uri 추가
- -closed #1002

✨ [Feature] AgendaProfile이 없는 유저 검색시 구분을 위해 함수 분리 #1002

---

gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java
gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java

- AdminTeamUpdate 팀장 로직 수정
- -closed #1006

🐛 [Bug] AdminTeamUpdate시 팀장 비교 로직 수정 #1006

---

gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/TicketController.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/controller/response/TicketCountResDto.java
gg-agenda-api/src/main/java/gg/agenda/api/user/ticket/service/TicketService.java
gg-agenda-api/src/test/java/gg/agenda/api/user/ticket/TicketControllerTest.java
gg-repo/src/main/java/gg/repo/agenda/TicketRepository.java

- TicketFindService에서 TicketCount 수정
- -closed #1008

🐛 [Bug] TicketSetup 유무 확인하는 로직 전부 False로 나가는 버그 발생 #1008

---

README.md
codecov.yml

- codecovyml 수정 이후 테스트 커버리지 추가로 인한 재 PR입니다.
- -closed #1010

✨ [Feature] 7기 README 업데이트 #1010

---

gg-agenda-api/src/main/java/gg/agenda/api/utils/AgendaSlackService.java
gg-agenda-api/src/main/java/gg/agenda/api/utils/SnsMessageUtil.java

- 슬랙 메세지 수정
- 개최자 Min Max 반대로 된 부분 수정
- -closed #1014

🐛 [Bug] 프론트와 백엔드간 URL 주소 다름으로 인한 슬랙 메세지 오류 수정 #1014
