src/main/java/com/gg/server/admin/game/controller/GameAdminController.java, src/main/java/com/gg/server/admin/game/dto/RankGamePPPModifyReqDto.java, src/main/java/com/gg/server/admin/game/exception/NotRecentlyGameException.java, src/main/java/com/gg/server/admin/game/service/GameAdminService.java, src/main/java/com/gg/server/admin/pchange/data/PChangeAdminRepository.java, src/main/java/com/gg/server/admin/pchange/data/PChangeAdminRepositoryCustom.java, src/main/java/com/gg/server/admin/pchange/data/PChangeAdminRepositoryCustomImpl.java, src/main/java/com/gg/server/admin/pchange/exception/PChangeNotExistException.java, src/main/java/com/gg/server/admin/team/data/TeamUserAdminRepository.java, src/main/java/com/gg/server/domain/game/service/GameService.java, src/main/java/com/gg/server/domain/pchange/data/PChange.java, src/main/java/com/gg/server/domain/rank/data/Rank.java, src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java, src/main/java/com/gg/server/domain/team/data/Team.java, src/main/java/com/gg/server/domain/user/User.java, src/main/java/com/gg/server/global/exception/ErrorCode.java, src/test/java/com/gg/server/game/GameControllerTest.java
- admin 에서 게임 점수 수정 가능한 API 입니다.
- 먼저 valid 체크 후에 가장 최근의 pchange 두개를 검색하여 RankRedis 와 Rank Table 에 있는 ppp 값을 이전 값으로 되돌림
- RankRedis 값 update, Zset redis 도 수정
- Team 에 저장된 게임 점수와 승패 여부 값을 Update
- PPP 계산 다시 해서 redis 에 반영
=> GGBE-134 admin 에서 랭킹 점수 수정 가능한 api 생성

src/main/java/com/gg/server/admin/receipt/controller/ReceiptAdminController.java, src/main/java/com/gg/server/admin/receipt/data/ReceiptAdminRepository.java, src/main/java/com/gg/server/admin/receipt/dto/ReceiptListResponseDto.java, src/main/java/com/gg/server/admin/receipt/dto/ReceiptResponseDto.java, src/main/java/com/gg/server/admin/receipt/service/ReceiptAdminService.java, src/main/java/com/gg/server/domain/receipt/data/Receipt.java, src/test/java/com/gg/server/admin/receipt/controller/ReceiptAdminControllerTest.java
- 상품 거래내역 전체 조회 API
- 관리자페이지에서 전체 거래내역 (receipt) 조회 가능하게 하였습니다.
- 기존 receipt 엔티티에서 헷갈릴 수 있는 purchasedAt 컬럼을 다른 엔티티와 동일한 createdAt으로 변경하였습니다. (DB는 그대로)
=> [GGBE4-25--receipt] 관리자 거래내역 조회 API 추가

src/main/java/com/gg/server/domain/item/controller/ItemController.java, src/main/java/com/gg/server/domain/item/data/UserItemRepository.java, src/main/java/com/gg/server/domain/item/dto/UserItemListResponseDto.java, src/main/java/com/gg/server/domain/item/dto/UserItemPageRequestDto.java, src/main/java/com/gg/server/domain/item/dto/UserItemResponseDto.java, src/main/java/com/gg/server/domain/item/service/ItemService.java, src/test/java/com/gg/server/domain/item/controller/UserItemResponseControllerTest.java
- 유저가 자신의 아이템 보관함에서 아이템 리스트를 조회하는 API 입니다.
- 조회 시점에 @Login을 통해 전달 받은 유저 정보 중 intraId를 통해, intraId가 owner인 receipt 내역들을 가져옵니다.
- /pingpong/items?page=${page}&size=${size}처럼 명시된 바와 같이, 각각 page와 size를 조회 시 받아야 합니다
- 아이템 보관함을 최신순으로 정렬하였습니다
- 상점 아이템 조회, 유저별 아이템 보관함 조회. 이상 2개 GET 항목에 대해 service에서 @Transactional(readOnly = true) 로 수정하였습니다
-
=> [GGBE4-41--search-user-storage-api] 유저별 아이템 보관함 리스트 조회 API

src/main/java/com/gg/server/domain/item/dto/UserItemResponseDto.java
- 유저별 아이템 보관함 조회 API에 itemType 추가
- 
- 기존 로직은 동일하며, Dto에 itemType하나만 추가했습니다
- API 결과물에 이제 itemType도 추가됩니다
=> [GGBE4-41--search-user-storage-api] 유저별 아이템 보관함 조회에 itemType도 추가

src/main/java/com/gg/server/domain/game/data/GameRepository.java, src/main/java/com/gg/server/domain/game/service/GameService.java
- 점수 입력 시 Service 메소드에 synchronized 가 되어있음에도 불구하고 insert 가 두번 되는 문제가 있어서 수정함
- 점수 입력 시 Game 상태 체크를 위해 gameId 를 가지고 조회하는데, game Id 조회 시 배타락을 걸어 다른 트랜잭션에서 읽기 및 쓰기 작업을 제한함
=> [fix] 점수 입력 시 game table에 배타락 추가

src/main/java/com/gg/server/admin/user/controller/UserAdminController.java, src/main/java/com/gg/server/admin/user/data/UserImageAdminRepository.java, src/main/java/com/gg/server/admin/user/service/UserAdminService.java, src/main/java/com/gg/server/domain/user/data/UserImage.java, src/test/java/com/gg/server/admin/user/controller/UserAdminControllerTest.java
- admin에서 부적절한 유저 이미지를 삭제하는 api 입니다
- admin에 새로운 userImageAdminRepository를 만들어서 isDeleted 열을 setter로 수정하였습니다.
-
=> [GGBE4-57--profile-image-delete-api] 유저 프로필 이미지 강제 삭제(관리자)

src/main/java/com/gg/server/admin/user/controller/UserAdminController.java, src/main/java/com/gg/server/admin/user/data/UserImageAdminRepository.java, src/main/java/com/gg/server/admin/user/service/UserAdminService.java, src/test/java/com/gg/server/admin/user/controller/UserAdminControllerTest.java
- 모든 유저의 이미지 변경내역을 조회하는 api입니다.
- 각 유저의 처음 인트라넷 사진을 제외한 역대 이미지 내역을 보여주는 api 입니다.
- 직접 쿼리문으로 유저별 min(id)를 group by 해서 포함되지 않는 열만 return하도록 했습니다!
-
=> [GGBE4-42--get-user-image-list-api] 유저 이미지 변경 내역 조회(관리자) 

src/main/java/com/gg/server/admin/user/controller/UserAdminController.java, src/main/java/com/gg/server/admin/user/data/UserImageAdminRepository.java, src/main/java/com/gg/server/admin/user/dto/UserImageAdminDto.java, src/main/java/com/gg/server/admin/user/dto/UserImageListAdminResponseDto.java, src/main/java/com/gg/server/admin/user/service/UserAdminService.java, src/test/java/com/gg/server/admin/user/controller/UserAdminControllerTest.java
- 모든 유저의 이미지 변경내역을 조회하는 api입니다.
- 각 유저의 처음 인트라넷 사진을 제외한 역대 이미지 내역을 보여주는 api 입니다.
- 직접 쿼리문으로 유저별 min(id)를 group by 해서 포함되지 않는 열만 return하도록 했습니다!
-
=> [GGBE4-42--get-user-image-list-api] 유저 이미지 변경 내역 조회(관리자)

src/main/java/com/gg/server/admin/season/service/SeasonAdminService.java, src/test/java/com/gg/server/admin/season/SeasonAdminControllerTest.java
- 이전 기수에서 현재시즌에 대한 수정 요청시 수정 없이 204 반환(사유: 관리자 실수가 없을 것이라 가정 및 판단)
- 이번 기수에서 400번 반환으로 수정 요청(원래 이게 맞는 것이긴 함, 과거의 나는 대체....)
- 수정 작업 요청시 변동되는 시즌의 시작시간이 과거이면 403 반환
- 시즌 생성 및 삭제는 체크 함수에서 이미 걸러냄, 수정만 if문 안에서  체크해 미래 시즌인지 확인하는 과정에서 예외처리를 하지 않음
=> [GGBE4-70-fix-season_outcode]현재 시즌 수정시 204가 아닌 403반환 수정

src/main/java/com/gg/server/admin/coin/controller/CoinAdminController.java, src/main/java/com/gg/server/admin/coin/dto/CoinUpdateRequestDto.java, src/main/java/com/gg/server/admin/coin/service/CoinAdminService.java, src/main/java/com/gg/server/domain/coin/service/CoinHistoryService.java, src/test/java/com/gg/server/admin/coin/controller/CoinAdminControllerTest.java
- 관리자 코인 수정 api 구현
- 코인 내역에 저장
- 관리자가 유저의 코인양을 수정할 수 있어야 한다는 프론트 측의 요청으로 추가하였습니다.
- 수정 내역은 관리자가 입력한 그대로 유저에게 노출됩니다.
- 추후 패널티 등을 고려하여 음수 막지 않았습니다.
=> [GGBE4-77--admin-update-coin-api] 관리자 코인 수정 api 구현

src/main/java/com/gg/server/domain/item/dto/ItemStoreResponseDto.java
- DTO 생성자 및 바디 수정
- this.itemType = item.getType().toString() 대신 item.getType() 으로 수정
- 컨트롤러에서 반환하는 객체(DTO 등)는 HTTP 응답으로 변환되기 전에 내부적으로 Jackson 라이브러리를 통해 JSON형식으로 변환되고, Enum타입 필드는 문자열 값으로 변환됨
-
=> [GGBE4-81--FIX-ItemStoreResponseDto-enum-toString] Dto 생성자 및 바디 수정

src/main/java/com/gg/server/admin/game/service/GameAdminService.java, src/main/java/com/gg/server/global/exception/ErrorCode.java
- admin 페이지에서 게임 점수 입력이 잘못되었을 때 관리자가 수정할 수 있는 기능입니다.
- 승패가 바뀌는 경우, 승패 횟수가 바뀌지 않는 문제를 수정했습니다.
- 이전 게임 결과를 바탕으로 승패 횟수 및 pchange 를 되돌린 후, teamUser 에 저장된 win 값을 변경하도록 수정했습니다.
=> [fix] #232 점수 수정 시 승패 수정 안되는 문제 수정

src/main/java/com/gg/server/domain/user/exception/UserAlreadyAttendanceException.java
- UserAlreadyAttendanceException 의 상속을 DuplicationException 으로 변경
-
-
=> [GGBE4-83-UserAlreadyAttendanceException-to-DuplicationException] UserAlreadyAttendanceException 의 상속을 DuplicationException 으로 변경

src/test/java/com/gg/server/domain/item/controller/ItemStoreListControllerTest.java
- 유저별 아이템 보관함 조회 테스트 코드 수정
- 유저별 아이템 보관함 조회에서 toString() 부분을 삭제하고 ENUM 그대로 받았음
- 이에 따라 테스트 코드도 동일하게 수정
- deploy 돌리던 중 에러 발견함
-
=> [GGBE4-86--ItemStroreResponseDto-TestCode] 유저별 아이템 보관함 조회 테스트 코드 삭제

src/main/java/com/gg/server/domain/touranment/data/Tournament.java, src/main/java/com/gg/server/domain/touranment/data/TournamentGame.java, src/main/java/com/gg/server/domain/touranment/data/TournamentGameRepository.java, src/main/java/com/gg/server/domain/touranment/data/TournamentRepository.java, src/main/java/com/gg/server/domain/touranment/data/TournamentUser.java, src/main/java/com/gg/server/domain/touranment/data/TournamentUserRepository.java, src/main/java/com/gg/server/domain/touranment/type/TournamentRound.java, src/main/java/com/gg/server/domain/touranment/type/TournamentStatus.java, src/main/java/com/gg/server/domain/touranment/type/TournamentType.java
- 토너먼트 entity, repository 생성
- `Round`. `Status`, `Type` type 추가
- `Round`: 몇강 몇번째 게임. ex) 8-1
- `Status`: 토너먼트 진행 상태 -> before, live, end
- `Type`: 토너먼트 종류 -> rookie, master
- Tournament Entity 추가 
- Tournament Repository 추가
- TournamentGame Entity 추가
- TournamentGame Repository 추가
- TournamentUser Entity 추가
- TournamentUser Repository 추가
- close #297
=> ✨ [Feature] Tournament entity repository 생성

src/main/java/com/gg/server/domain/tournament/data/Tournament.java, src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java, src/main/resources/db/migration/V3__migration_42gg_5th.sql
- 토너먼트 테이블 초기화하는 v3 파일 추가
- `TournamentGame` Entity에서 id `@Column` annotation 삭제 (컬럼명 잘못됨)
- enum type을 사용하는 필드에 `@Enumerated` annotation 추가
- `tournamet_user`의 `is_joined` 컬럼을 `BIT(1)` 대신 `BOOLEAN`으로 설정했습니다.
MySQL 내부적으로 `TINYINT(1)`로 저장되며 이를 권장한다고 합니다.
- [Mysql 공식문서](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html)
- [Stack Overflow](https://stackoverflow.com/questions/290223/what-is-the-difference-between-bit-and-tinyint-in-mysql)
- close #299
=> ✨ [Feature] tournament 테이블 초기화 SQL 추가

src/main/java/com/gg/server/domain/tournament/data/Tournament.java, src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java, src/main/resources/db/migration/V3__migration_42gg_5th.sql
- 토너먼트, 토너먼트 게임 테이블 수정
- 토너먼트 테이블 `winner_id` 추가(nullable user_id fk)
- 토너먼트 조회할 때 기존에 winner를 찾기 위해서 너무 많은 join이 필요하고 depth가 깊어지는 문제점을 해결하기 위해 nullable한 `winner_id` 컬럼을 추가하기로 결정되었습니다.
- 토너먼트 게임 테이블 `game_id` (fk) nullable하게 수정
-  Response Dto에서 다음 경기에 대한 정보가 필요해서, `tournament_game_id` 값을 사용하기로 결정되었습니다.
- 이에 따라 tournament 생성 시점에 touranment_game도 함께 생성되어야 하고 game은 생성되지 않을 수 있으므로 `game_id`를 nullable하게 수정했습니다.
- close #312
=> :hammer: [Refactor] 토너먼트, 토너먼트 게임 테이블 수정

src/main/resources/db/migration/V3__migration_42gg_5th.sql
- tournament 관련 테이블의 `VARCHAR` column 길이 수정
- `tournament_game` 데이터가 생성될 때 enum 길이가 길어서 저장이 안 되는 문제가 발생
- `round` 컬럼을 `VARCHAR(10)` -> `VARCHAR(20)`으로 수정
- `tournament`의 `title` column도 `VARCHAR(20)` -> `VARCHAR(30)`으로 수정했습니다.
=> :bug: [Fix]  tournament 관련 테이블의 varchar 길이 수정

src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java, src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java, src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/tournament/data/Tournament.java, src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java, src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java, src/test/java/com/gg/server/utils/TestDataUtils.java
- 토너먼트 수정 API 구현 및 테스트 코드 추가
- 토너먼트 수정에 필요한 controller, service, dto 추가
- 토너먼트 엔티티에 매서드 추가
- 토너먼트 레포 매서드 추가
- 테스트 코드 추가
- 통합 테스트용 매서드 추가
- `TournamentAdminUpdateRequestDto 추가`
- `토너먼트 관리자 서비스 수정 매서드 추가`
- **updateTournamentInfo**: 토너먼트 수정 매서드
- **checkValidTournamentTime**: 토너먼트 개최 가능 시간 판별 매서드
- **checkConflictedTournament**: 기존 토너먼트들과 중복하는 기간인지 판별하는 매서드
- `토너먼트 관리자 수정 컨트롤러 매서드 추가`
- `TestDataUtils 통합테스트용 유틸 매서드 추가`
- **createTournament**: 테스트용으로 토너먼트 객체 생성, 매개변수로 받는 값들만 초기화
- **TournamentAdminUpdateRequestDto**: 테스트용으로 dto 객체 생성, 매개변수로 받는 값들만 초기화
- `TournamentRepository findAllByStatus 매서드 추가` : 토너먼트 개최 상태에 따른 토너먼트들을 받아오는 매서드
- `토너먼트 entity update() & toString() 추가`
- **update**: 토너먼트 entity 수정용 매서드
- ~~`toString`: 필드값들 확인용으로 추가~~
- `@ToString` 추가
- `토너먼트 수정 controller & service 테스트 추가` …
=> ✨ [Feature] Tournament 수정 API 추가

src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java, src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java, src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/tournament/data/Tournament.java, src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java, src/main/java/com/gg/server/domain/tournament/data/TournamentGameRepository.java, src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java, src/main/java/com/gg/server/global/exception/ErrorCode.java, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java, src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java, src/test/java/com/gg/server/utils/TestDataUtils.java
- 토너먼트 관리자 삭제 API 추가 
- `TournamentAdminController`
- delete 맵핑 + 매서드 추가
- `TournamentAdminService`
-  삭제 매서드 추가
- `TournamentGame`
- `id를 제외한 파라미터 생성자 추가` + round 길이 30 제한
- `TournamentGameRepository`
- `토너먼트 id`로 탐색하는 매서드 추가
- `TestDataUtils`
- TournamentGame 리스트 반환 매서드 추가
- `TournamentAdminControllerTest`
- 통합테스트
- `성공`, `타겟 토너먼트 없음`, `삭제 불가` 토너먼트 검사
- `TournamentAdminServiceTest`
- 서비스 계층 단위 테스트
- makeTournamentGames: 토너먼트 게임 리스트 반환 매서드 추가
- `성공`, `타겟 토너먼트 없음`, `삭제 불가` 토너먼트 검사
- `TournamentAdminService`
- `checkConflictedTournament` 매서드 중복 검사 조건 변경, before -> before & live 둘다 체크
- `Tournament`
-   tournamentGames & tournamentUsers 에 `new ArrayList<>()`로 할당
- `TournamentGameRepository`
- `findAllByStatusBeforeAndLive`: before & live 상태 토너먼트 다 찾아주는 매서드 
- `ErrorCode`
- …
=> :sparkles: [Feature] 토너먼트 관리자 삭제 API 추가

src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java, src/main/java/com/gg/server/domain/tournament/data/Tournament.java, src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java, src/main/java/com/gg/server/domain/tournament/data/TournamentUser.java, src/main/java/com/gg/server/domain/tournament/data/TournamentUserRepository.java, src/main/java/com/gg/server/domain/tournament/dto/TournamentFilterRequestDto.java, src/main/java/com/gg/server/domain/tournament/dto/TournamentListResponseDto.java, src/main/java/com/gg/server/domain/tournament/dto/TournamentResponseDto.java, src/main/java/com/gg/server/domain/tournament/service/TournamentService.java, src/main/java/com/gg/server/domain/tournament/type/TournamentStatus.java, src/main/java/com/gg/server/domain/tournament/type/TournamentType.java, src/main/java/com/gg/server/domain/tournament/validation/EnumValue.java, src/main/java/com/gg/server/domain/tournament/validation/ValueOfEnumValidator.java, src/main/java/com/gg/server/domain/user/dto/UserImageDto.java, src/main/java/com/gg/server/global/exception/GlobalExceptionHandler.java, src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java, src/test/java/com/gg/server/utils/TestDataUtils.java
- Tournament 리스트 조회 Api 작성
- Tournament list 조회를 위한 Repository, Dto 추가
- Tournament Type, Status Dto의 Valid 추가
- Tournament 전체 리스트 조회 테스트 코드 추가
- `TournamentController` (Pageable) 
- param -> pagenation에 필요한 `page`, `size` 그리고 검색 조건에 사용되는 `TournamentFilterRequestDto`
-   `TournamentFilterRequestDto` : `TournamentStatus`, `TournamentType`이 담겨있는 Dto
- Tournament data 에 `updateWinner()` 함수 추가
- `TournamentResponseDto` : 검색된 토너먼트 정보들
- `TournamentListResponseDto` : `TournamentResponseDto와` `totalPage` 정보가 포함된 dto
- `EnumValue` : `String` type을 EnumValue로 검사하기 위해 사용되는 **`@Enumvalue` 어노테이션**
- `ValueOfEnumValidator` : `@EnumValue` 에서 valid 검사를 위한 validator
- close #302 
- close #321
=> ✨  [Feature] 토너먼트 전체 리스트 조회 Api 추가

src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java, src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/tournament/data/TournamentUserRepository.java, src/main/java/com/gg/server/domain/tournament/dto/TournamentUserListResponseDto.java, src/main/java/com/gg/server/domain/tournament/dto/TournamentUserResponseDto.java, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminUserControllerTest.java, src/test/java/com/gg/server/utils/TestDataUtils.java
- 토너먼트에 참가된 유저들을 조회하는 API 추가
- `TournamentAdminController` && `TournamentAdminService` : 토너먼트 유저 조회 API 추가
- `TournamentUserRepository` findAllByTournament, findAllByTournamentAndIsJoined 추가
- `TestDataUtils` : TournamentUser 데이터 추가하는 로직 추가
-  TournamentAdminUserControllerTest 테스트 코드 추가
-  close #332
=> ✨ [Feature] 토너먼트 유저 조회 API 추가

src/main/java/com/gg/server/domain/game/data/GameRepository.java, src/main/java/com/gg/server/domain/game/dto/GameResultResDto.java, src/main/java/com/gg/server/domain/team/dto/TeamUserListDto.java, src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java, src/main/java/com/gg/server/domain/tournament/data/TournamentGameRepository.java, src/main/java/com/gg/server/domain/tournament/dto/TournamentGameListResponseDto.java, src/main/java/com/gg/server/domain/tournament/dto/TournamentGameResDto.java, src/main/java/com/gg/server/domain/tournament/service/TournamentService.java, src/main/java/com/gg/server/domain/tournament/type/TournamentRound.java, src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java, src/test/java/com/gg/server/domain/tournament/controller/TournamentGameControllerTest.java, src/test/java/com/gg/server/utils/TestDataUtils.java
- 토너먼트 Id에 해당하는 게임 전체 조회 api 추가
1. 토너먼트에서 이루어진 게임들(`TournamentGame`)을 찾아서 `TournamentGameListResponseDto` 에 넣어 반환
2. TournamentGameListResponseDto -> 토너먼트, 게임, 팀, 유저 에 대한 정보를 가지고있다.
1. `TeamUserListDto`에 teamId를 가지는 생성자 추가
2. `GameRepository`에 teamId 도 포함하여 return 해주는 메소드 추가
3.  `GameResultResDto` 에도 teamId추가
1. `TournamentRound` Enum 에 NextRound 데이터 추가
2. `TournamentService` 에서 `findNextTournamentGame` 로 nextTournaemtGame 찾는 메소드 추가
1. 기존 토너먼트 id순으로 오름차순 정렬 ->  startTime 기준으로 내림차순 정렬로 수정
2. 이에 따른 테스트 코드도 수정
-  close #307
=> ✨ [Feature] 토너먼트 Id에 해당하는 게임 전체 조회 api 추가

src/main/java/com/gg/server/admin/game/controller/GameAdminController.java, src/main/java/com/gg/server/domain/match/controller/MatchController.java, src/main/java/com/gg/server/domain/match/service/MatchFindService.java, src/main/java/com/gg/server/domain/match/service/MatchService.java, src/main/java/com/gg/server/domain/match/type/Option.java, src/main/java/com/gg/server/domain/match/utils/SlotGenerator.java, src/main/java/com/gg/server/domain/tournament/data/Tournament.java, src/main/java/com/gg/server/domain/tournament/exception/TournamentConflictException.java, src/main/java/com/gg/server/domain/tournament/service/TournamentService.java, src/main/java/com/gg/server/domain/tournament/type/TournamentType.java, src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java, src/test/java/com/gg/server/domain/match/service/MatchTestUtils.java
- `TOURNAMENT` 추가로 인한 match, slot 관련 로직 수정
1. 게임 매칭 요청했을 때 토너먼트 확인 후 블락 
- `POST /pingpong/match?type={type}`
- `MatchService`의   `makeMatch()` -> `checkValid()`에서 토너먼트 시간과 겹칠 경우 exception throw
2. 슬롯 정보 가져올 때 토너먼트 확인 후 블락
- `GET /pingpong/match/time/scope?mode={mode}`
- `MatchFindServie`의 `getAllMatchStatus()`에서 토너먼트에 대한 슬롯 block 로직 추가
- `MatchServiceTest` 기존 코드  `@Nested`로 리팩토링 
- 테스트코드는 기존 match 레거시 테스트코드에 맞게 작성했습니다.
- 현재 게임 매칭 요청에 대한 테스트코드는 레디스 관련 문제로 동작하지 않습니다.
- 동일한 테스트 환경에서 동일한 데이터로 테스트하기 위해 `MatchTestUtils`의 `makeTestSeason()`에서 저장되어있는 season을 확인하는 로직을 삭제했습니다.
- `TournamentStatus`에 `CUSTOM` 추가
- `Match`의 `Option`에 `TOURNAMENT` 추가
- 삭제했던 게임 전체 / 시즌별 조회하기 API `GET /pingpong/admin/games?page={page}`추가
- `TournamentConflictException`에 default constructor 추가
- `Tournament` Entity에 …
=> ✨ [Feature] 토너먼트 추가로 인한 Match 로직 수정

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/game/data/Game.java, src/main/java/com/gg/server/domain/match/service/GameUpdateService.java, src/main/java/com/gg/server/domain/team/data/Team.java, src/main/java/com/gg/server/domain/tournament/data/Tournament.java, src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java, src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java, src/main/java/com/gg/server/domain/tournament/data/TournamentUser.java, src/main/java/com/gg/server/domain/tournament/service/TournamentService.java, src/main/java/com/gg/server/domain/tournament/type/TournamentRound.java, src/main/java/com/gg/server/global/scheduler/TournamentScheduler.java, src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java, src/test/java/com/gg/server/domain/tournament/controller/TournamentSchedulerTest.java, src/test/java/com/gg/server/utils/TestDataUtils.java
- 토너먼트 첫 경기 (현재 8강) 매칭하는 Scheduler 생성
- **스케줄러는 매일 자정에 실행됩니다.**
- **오늘 날짜 기준으로 시작하는 토너먼트가 있을 경우 토너먼트의 status를 `LIVE`로 바꾸고 첫 8강 경기 4경기를 생성합니다.**
- 8강에 대한 `TouranmentGame`을 찾고, `Team`, `TeamUser`를 생성하여 저장합니다.
- `TournamentRound` enum class를 활용하여 sort(정렬)하는데, 내부적으로 `ordinal()`로 정렬이 됩니다. **그래서 enum 값들 순서가 중요합니다. 주의를 위한 주석을 추가했습니다.** 하지만 좋은 코드는 아닌 것 같아서 이후에 enum에 대한 리팩토링을 진행할 예정입니다.
- `ALLOWED_JOINED_NUMBER`, `ALLOWED)MINIAL_START_DAYS`, `MINIMUM_TOURNAMENT_DURATION` 상수들 `TournamentAdminService`에서 `Tournament`로 옮겼습니다.
- 추가로 데이터 타입을 `long`에서 `int`로 수정했습니다.
- `Game`, `Team` Entity의 멤버필드중 list에 대해서 초기화하는 코드를 추가했습니다.
- close #338
=> ✨ [Feature] 토너먼트 첫 경기 매칭하는 Scheduler 생성

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/game/data/GameRepository.java, src/main/java/com/gg/server/domain/tournament/data/TournamentRepository.java, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java, src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java, src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java
1. 토너먼트를 생성하고 수정할 때 해당 기간에 게임이 존재하는지 확인하는 매서드 추가
2. 기존 유효 시간을 검증하는 로직을 쿼리문으로 변경
- `TournamentAdminService`
- `checkConflictedTournament` : 기존 로직 쿼리문으로 변경
- `createTournament && updateTournament `: 게임 존재 여부 확인 매서드 추가
- `checkGameExistence`: 쿼리문을 통한 게임 존재 확인 매서드
- `GameRepository`: 쿼리문 추가
- `TournamentRepository`: 쿼리문 추가
- `TournamentAdminControllerTest && TournamentAdminServiceTest && TournamentServiceTest` : 테스트 코드
-
- close #337
=> 🔨  [Refactor] 토너먼트 생성 및 수정 매서드 추가 및 수정

src/main/java/com/gg/server/admin/tournament/controller/TournamentAdminController.java, src/main/java/com/gg/server/admin/tournament/dto/TournamentGameUpdateReqDto.java, src/main/java/com/gg/server/admin/tournament/dto/TournamentGameUpdateRequestDto.java, src/main/java/com/gg/server/admin/tournament/exception/TournamentNotLiveException.java, src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/game/data/GameRepository.java, src/main/java/com/gg/server/domain/game/exception/ScoreNotInvalidException.java, src/main/java/com/gg/server/domain/team/dto/TeamReqDto.java, src/main/java/com/gg/server/domain/tournament/exception/TournamentGameNotFoundException.java, src/main/java/com/gg/server/domain/tournament/exception/TournamentNotFoundException.java, src/main/java/com/gg/server/domain/tournament/exception/TournamentUpdateException.java, src/main/java/com/gg/server/global/exception/ErrorCode.java, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java, src/test/java/com/gg/server/utils/TestDataUtils.java
- 토너먼트 게임 결과 스코어 수정 api
- 게임이 완료 전인 wait, live 상태에서도 수정 가능
- `TournamentAdminService` 
1. updateTournamentGame : 토너먼트 게임 스코어 수정 함수
2. updateTeamScore : 팀 스코어를 업데이트 하고 게임 상태를 업데이트 해주는 함수
3. canUpdateScore : 업데이트 가능한 게임인지 확인 하는 함수
- 예외 처리 부분들에 대해서 기본 생성자로 하도록 기본생성자 추가
- 테스트 코드 추가
- close #308
=> ✨ [Feature] 토너먼트 게임 결과 수정 api 추가

src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminAddUserResponseDto.java, src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java, src/main/java/com/gg/server/domain/tournament/data/TournamentUserRepository.java, src/main/java/com/gg/server/domain/tournament/service/TournamentService.java, src/test/java/com/gg/server/domain/tournament/controller/TournamentFindControllerTest.java, src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java
- 유저 참가 신청 API 입니다.
- 해당 토너먼트에 참가 신청을 하지않은 상태인 `BEFORE` 일때만 신청 가능합니다. (아닐시 throw)
- `TournamentAdminAddUserResponseDto` : boolean -> Boolean 으로 변경
- `TournamentAdminService`: java docs 추가 및 코드 가독성 개선
- `TournamentController` && `TournamentService`: 토너먼트 유저 참가 신청 매서드 추가
- `TournamentUserRepository` : findAllByUser 매서드 추가
- `TournamentFindControllerTest` && `TournamentServiceTest`: 테스트 코드 추가
- `TournamentServiceTest`: 잘못된 테스트 코드 삭제
- close #344
=> ✨  [Feature] 토너먼트 유저 참가 신청 API

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/game/data/Game.java, src/main/java/com/gg/server/domain/team/data/Team.java, src/main/java/com/gg/server/domain/tournament/data/Tournament.java, src/main/java/com/gg/server/domain/tournament/data/TournamentGame.java, src/main/java/com/gg/server/domain/tournament/data/TournamentUser.java, src/main/java/com/gg/server/domain/tournament/service/TournamentService.java, src/main/java/com/gg/server/global/exception/ErrorCode.java, src/main/java/com/gg/server/global/exception/custom/BusinessException.java, src/main/java/com/gg/server/global/exception/custom/CustomRuntimeException.java, src/main/java/com/gg/server/global/utils/BusinessChecker.java, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java, src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java, src/test/java/com/gg/server/domain/game/data/GameUnitTest.java, src/test/java/com/gg/server/domain/team/data/TeamUnitTest.java, src/test/java/com/gg/server/domain/tournament/controller/TournamentSchedulerTest.java, src/test/java/com/gg/server/domain/tournament/data/TournamentUnitTest.java, src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java, src/test/java/com/gg/server/utils/ReflectionUtilsForUnitTest.java, src/test/java/com/gg/server/utils/TestDataUtils.java, src/test/resources/schema.sql
- 토너먼트 도메인에 연관관계 편의 메서드를 적용합니다.
- 테스트 코드 작성시 오동작이 발생하는 경우가 많아 예외를 바로 파악할 수 있게 검증 로직들을 추가했습니다.
- 모든 연관관계 관리는 연관관의 주인, fk를 가진 쪽에서 수행합니다.
- 토너먼트 연관관계 메서드 작성
- Game 연관관계 메서드 개선 
- 메서드 파라미터 단 @ NotNull은 기능이 없어 제거
- 토너먼트 엔티티의 연관관계 필드 변경 및 검증 메서드를 fk를 가지고 있는 엔티티가 아닌 외부(기타 서비스 코드)에서 호출하지 못하도록 protected 레벨로 선언.
- 개발자 로직 정상작성 체크용 검증 static 유틸리티 추가
- schema.sql 최신화 (Cascade 추가) 
- Tournament, Game, Team 단위테스트 추가
- Builder가 존재하는 클래스에 존재하는 AllArgConstructor는 서비스 일관성을 해치게 됩니다. 따라서 제거합니다.
- 유닛 테스트에서 private id 필드 값을 조정하기 위해 reflection을 사용해서 처리하는 것으로 대체
- 여기서 정의된 연관관계 편의 메서드란 양방향 매핑 관계의 있는 엔티티들을 일치시키는 역할을 말합니다.
- 필드 변경 및 검증 메소드는 토너먼트에 존재하는 addTournamentGame, addTournamentUser, deleteTournamentUser 가 해당합니다. 연관관계 일치 책임은 fk를 가진 엔티티가 가지지만 필드 검증은 해당 필드를 가진 엔티티가 담당해야 하기 때문에 해당 메소드가 존재합니다.
- #378
=> ✨ [Feature] 토너먼트 연관관계 메서드 처리

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java, src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java, src/test/java/com/gg/server/utils/TestDataUtils.java
- 기존 시간로직 수정
- 최소 48시간 이후 생성 가능 하던 로직을 현재일 기준 이틀뒤로 수정
- interval 시간으로 시작시간의 분이 나누어 떨어져야함 (15분, 30분, 45분, 00분)
- `TournamentAdminService`: checkValidTournamentTime 매서드 수정
- `TournamentAdminControllerTest` && `TournamentAdminServiceTest`: 테스트 코드 수정
- `TestDataUtils`: createSlot 매서드 추가
-
- close #388
=> 🔨 [Refactor] 토너먼트 생성 및 수정 시간 검증 로직 수정

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/game/GameController.java, src/main/java/com/gg/server/domain/game/service/GameService.java, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java, src/test/java/com/gg/server/domain/game/GameControllerTest.java
- 토너먼트 게임 점수 수정시 pchange를 추가하지 않아 생기는 버그 수정
- 토너먼트 게임 점수를 개인이 수정할때, 관리자가 수정할 떄 pchange를 추가하도록 함
- 토너먼트 게임이 Before 상태일때 점수정되던 부분 수정 안되도록 수정
- close #408
- close #409
=> 🐛 [Fix] 토너먼트 게임 결과 등록할 때 pchange 생성 안 되는 문제 해결

src/main/java/com/gg/server/domain/match/service/MatchService.java, src/main/java/com/gg/server/domain/match/utils/SlotGenerator.java, src/test/java/com/gg/server/domain/match/service/MatchServiceTest.java
- 토너먼트 시간에 게임 매칭 요청에 대한 block 에러 수정
- 현재 매칭 시도한 시간에 토너먼트 진행시간과 겹치는지 확인하는 `isExistTournamentNotEnded` 함수의 boolean return을 잘못하고 있었습니다.
- 리턴값 수정과 `매칭 요청한 시간 + interval(15분)` 종료시간도 확인하는 로직을 추가했습니다.
- 로직 수정 후 정상적으로 테스트코드 돌아가서 `@Disabled` 삭제했습니다.
- 추가로 warning 메세지를 없애기 위해 약간의 수정이 포함되어 있습니다.
- close #373
=> 🐛 [Fix] 토너먼트 시간에 매칭 block 에러 수정

src/main/java/com/gg/server/admin/game/data/GameAdminRepository.java, src/main/java/com/gg/server/admin/game/service/GameAdminService.java, src/main/java/com/gg/server/domain/pchange/data/PChangeRepository.java, src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java
- 기존 게임을 가져오는 data jpa 가 `모든 게임을 가져오는` 매서드여서 `토너먼트를 제외한 게임들`을 가져오도록 수정
- `GameAdminRepository`
- `findBySeasonAndModeIn`: 해당 모드와 시즌의 모든 게임
- `findAllByModeIn`: 해당 모드의 모든게임
- `GameAdminService` : data jpa 변경 매서드로 수정
- `GameAdminControllerTest` : 테스트 코드 추가
-
- close #399
=> 🐛  [Fix] 관리자 게임 전체 조회에서 토너먼트 보이는 문제

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/game/service/GameService.java, src/main/java/com/gg/server/domain/pchange/data/PChangeRepository.java, src/main/java/com/gg/server/domain/team/dto/TeamUserListDto.java, src/main/java/com/gg/server/domain/tournament/dto/TournamentGameResDto.java, src/main/java/com/gg/server/domain/tournament/service/TournamentService.java, src/main/java/com/gg/server/domain/tournament/type/TournamentRound.java, src/main/java/com/gg/server/global/exception/ErrorCode.java, src/test/java/com/gg/server/domain/tournament/controller/TournamentGameControllerTest.java
1. 토너먼트 게임 조회시 점수 없는 게임은 score 필드 삭제
2. 토너먼트 게임 조회 토너먼트 라운드 기준으로 정렬
3. 토너먼트 게임 pchange가 이미 있을경우 생성 안되게 수정
4. 종료된 토너먼트의 결승전 수정 가능하도록 수정
- close #424 
- close #421
- close #420 
- close #418
=> [Refactoring] 토너먼트 게임 조회시 점수 없는 게임은 score 필드 삭제

src/main/java/com/gg/server/domain/match/dto/MatchStatusDto.java, src/test/java/com/gg/server/domain/match/dto/MatchStatusDtoUnitTest.java
- 현재 match 엔드포인트는 게임 타입 정보를 제공해주지 않습니다. 추가적인 정보 제공보다는 프론트에서 토너먼트 게임의 경우는 isImminent를 true로 전달할 것을 요청하셔서 해당 내용으로 진행합니다.
- 유닛 테스트코드 작성
- 토너먼트 게임의 경우는 isImminent를 true로 전달
- #441
=> 🔨 [Refactor] 토너먼트에 경우 isImminent true로 전달

src/main/java/com/gg/server/domain/tournament/service/TournamentService.java
- 토너먼트 LIVE 상태에서도 신청 삭제 되는 이슈 해결
- 토너먼트가 BEFORE 가 아니라면 `TournamentUpdateException()`
-
- close #455
=> :bug: [Fix] 토너먼트 LIVE 상태에서도 신청 삭제 되는 이슈

src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java, src/test/java/com/gg/server/domain/tournament/data/TournamentUnitTest.java, src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java, src/test/java/com/gg/server/utils/ReflectionUtilsForUnitTest.java
- 토너먼트 updateEndTime 매서드 유닛 테스트 추가
- 기존 `@Disabled` 테스트 코드 리플렉션 사용해서 돌아가도록 수정
- `TournamentAdminServiceTest` && `TournamentServiceTest`: `static` 키워드 추가로 인한 수정 및 기존 코드 개선
- `TournamentUnitTest`: updateEndTime 유닛 테스트 추가
- ReflectionUtilsForUnitTest : `static` 키워드 추가
- `checkValidTournamentTime` 로직 수정
- 년도가 넘어갈때 로직이 이상해지는 현상 수정 -> `LocalDate` 사용으로 해결
-
=> 🧪 [Unit Test] 토너먼트 updateEndTime 매서드 유닛 테스트 추가 및 기존 테스트 코드 수정

src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminCreateRequestDto.java, src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java, src/main/java/com/gg/server/global/security/config/SecurityConfig.java, src/main/resources/db/migration/V3.1__update_tournament_content_column.sql, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java
- `GUEST` 유저는 토너먼트 참가 불가능하도록 수정
- spring security config에서 토너먼트 참가 신청 API는 `USER`, `ADMIN`만 허용하도록 설정 추가
- `tournament` 테이블의 `contents` 컬럼을 `VARCHAR(3000)`으로 수정
- 토너먼트 생성 API, 토너먼트 수정 API Request DTO에서 `@Length`로 길이 제한
=> 🐛 [Fix] GUEST 토너먼트 참가 불가능하도록 수정

.gitattributes, src/main/java/com/gg/server/admin/game/service/GameAdminService.java, src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminCreateRequestDto.java, src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java, src/main/java/com/gg/server/admin/tournament/service/TournamentAdminService.java, src/main/java/com/gg/server/domain/match/service/MatchTournamentService.java, src/main/java/com/gg/server/domain/rank/redis/RankRedisService.java, src/main/java/com/gg/server/global/security/config/SecurityConfig.java, src/main/resources/db/migration/V3.1__update_tournament_content_column.sql, src/test/java/com/gg/server/admin/game/controller/GameAdminControllerTest.java, src/test/java/com/gg/server/admin/tournament/controller/TournamentAdminControllerTest.java, src/test/java/com/gg/server/admin/tournament/service/TournamentAdminServiceTest.java, src/test/java/com/gg/server/domain/tournament/data/TournamentUnitTest.java, src/test/java/com/gg/server/domain/tournament/service/TournamentServiceTest.java, src/test/java/com/gg/server/utils/ReflectionUtilsForUnitTest.java
=> 💚 [Merge] 리허설 토너먼트를 위한 merge

src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminCreateRequestDto.java, src/main/java/com/gg/server/admin/tournament/dto/TournamentAdminUpdateRequestDto.java, src/main/java/com/gg/server/domain/tournament/data/Tournament.java
- Dto에서 valid check에서 잘못된 길이 제한 수정
- 토너먼트 생성/수정 API에 사용되는 DTO의 contents 길이 제한 1000 -> 3000으로 수정
=> :bug: [Fix] tournament contents에 대한 길이 valid 수정

src/main/java/com/gg/server/domain/rank/data/RankRepository.java, src/main/java/com/gg/server/domain/rank/service/RankService.java, src/main/java/com/gg/server/domain/user/data/UserRepository.java
- exp랑 ppp rank 페이징 버그문제 해결
- query의 limit, offest 인자값 수정하였습니다.
- offset값은 pagenum * pagesize로 계산하도록 수정
- 테스트 코드는 이후 작성해서 pr다시 올리겠습니다
-
- closed #489
=> [Fix] rank pagig bug 해결

src/main/java/com/gg/server/domain/match/service/MatchFindService.java, src/main/java/com/gg/server/domain/match/utils/SlotGenerator.java
- 토너먼트 진행 시간동안의 슬롯 블락 로직 삭제
- 토너먼트 진행 시간동안의 슬롯 블락하는 로직 전체 삭제
- 이후에 탁구대가 하나인 상황이 올 경우... 해당 코드 다시 추가하면 됩니다..ㅎㅎ
- closed #487
=> :hammer: [Refactor] 토너먼트 진행 시간동안의 슬롯 블락 로직 삭제

src/main/java/com/gg/server/admin/announcement/controller/AnnouncementAdminController.java, src/main/java/com/gg/server/admin/announcement/service/AnnouncementAdminService.java, src/main/java/com/gg/server/domain/announcement/service/AnnouncementService.java, src/test/java/com/gg/server/admin/announcement/controller/AnnouncementAdminControllerUnitTest.java, src/test/java/com/gg/server/admin/announcement/service/AnnouncementAdminServiceUnitTest.java, src/test/java/com/gg/server/domain/announcement/controller/AnnouncementControllerUnitTest.java, src/test/java/com/gg/server/domain/announcement/data/AnnouncementUnitTest.java, src/test/java/com/gg/server/domain/announcement/service/AnnouncementServiceUnitTest.java
- ~`LF` -> `CRLF` 로 변경~
- `Announcement 단위 테스트` 추가
- Announcement 서비스 로직 중 쿼리 두번 날리는 부분 수정
- `AnnouncementAdminController`: 빌더 패턴으로 반환
- `AnnouncementAdminService`: announcement 레포에서 똑같은 값을 두번 호출하는 부분 수정
- `AnnouncementService`: java doc 추가 및 람다식 수정
- `Announcement 유닛 테스트 `
- mock 사용한 부분들에 대해서 verify 추가
- 서비스단 테스트들만 일단 마무리하였습니다. 컨트롤러는 추후에 다른 방식으로 수정해야해서 건드리지 않았습니다.
- naver 컨벤션 적용
- close #465
=> 🧪 [Unit Test] Announcement 단위 테스트 추가

src/main/java/com/gg/server/admin/item/service/ItemAdminService.java, src/main/java/com/gg/server/domain/item/service/ItemService.java, src/test/java/com/gg/server/admin/item/service/ItemAdminServiceUnitTest.java, src/test/java/com/gg/server/domain/item/data/ItemUnitTest.java, src/test/java/com/gg/server/domain/item/service/ItemServiceUnitTest.java
- `Item 유닛테스트` 추가
- `자바독` 추가
- 자잘한 코드 다듬기
- `ItemService`
- `purchaseItem()` && `giftItem()`: 할인가 정하는 로직 다듬었습니다.
- verify 추가
- 네이버 컨벤션 적용
- close #496
=> 🧪 [Unit Test] Item 유닛테스트 추가 및 자바독 추가 및 자잘한 코드 다듬기

src/main/java/com/gg/server/admin/noti/service/NotiAdminService.java, src/test/java/com/gg/server/admin/noti/service/NotiAdminServiceUnitTest.java
- `NotiAdminService` 단위 테스트 코드입니다.
- `sendAnnounceNotiToUser`, `getAllNoti`, `getFilteredNotifications` 세 개의 메서드에 대한 단위 테스트 코드를 작성하였습니다.
- `dto`와 `page` 내에 존재하는 메서드 검증에 대해서는 `todo`로 적어두었는데, 이는 Noti의 다른 단위 테스트를 추가할 때 수정하도록 하겠습니다.
- `SendAnnounceNotiToUserTest` 메서드 내 `UserNotFoundException`의 전제 조건 코드를 추가하였습니다.
- #469
=> 🧪 [Unit Test] NotiAdminService 단위 테스트

src/main/java/com/gg/server/domain/tournament/controller/TournamentController.java, src/test/java/com/gg/server/domain/tournament/controller/TournamentControllerMvcTest.java
- TournamentController 단위테스트를 작성합니다.
- TournamentController 단위테스트 작성
- @pathvarible 검증 및 단위테스트 편의를 위해 컨트롤러에 Validated 추가
- #439
=> 🧪 [Unit Test] tournamentController 단위 테스트

gg-data/src/main/java/gg/data/party/Comment.java, gg-data/src/main/java/gg/data/party/UserRoom.java, gg-pingpong-api/src/main/java/gg/party/api/user/comment/controller/CommentController.java, gg-pingpong-api/src/main/java/gg/party/api/user/comment/controller/request/CommentCreateReqDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/comment/service/CommentService.java, gg-repo/src/main/java/gg/repo/party/CommentRepository.java, gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java, gg-utils/src/main/java/gg/utils/exception/ErrorCode.java, gg-utils/src/main/java/gg/utils/exception/party/CommentNotValidException.java, gg-utils/src/main/java/gg/utils/exception/party/RoomNotFoundException.java, gg-utils/src/main/java/gg/utils/exception/party/RoomUpdateException.java
- 게시글에 댓글 작성하는 API 생성 
- due date를 넘지 않은 방에만 댓글 작성 가능
- 현재 참여 중인 방에만 댓글 작성 가능
- closed #642
=> [Feature] 댓글 생성 api

gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/RoomController.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java, gg-utils/src/main/java/gg/utils/exception/ErrorCode.java, gg-utils/src/main/java/gg/utils/exception/party/CategoryNotFoundException.java, gg-utils/src/main/java/gg/utils/exception/party/InvaildPeopleException.java, gg-utils/src/main/java/gg/utils/exception/party/NotHostException.java, gg-utils/src/main/java/gg/utils/exception/party/RoomNotEnoughPeopleException.java
- 방 시작하는 api입니다. 시작 이후 복면가왕 즉, 익명 삭제 관련 로직은 추후 논의가 필요한 로직이니 해당 로직 제외한 버전입니다.
- 방 나가기 API의 JAVA 명세 수정했습니다
-
- close #641
=> [FIX] startRoom API without 복면가왕 logic

build.gradle, gg-pingpong-api/src/main/java/gg/PingpongApiApplication.java, gg-pingpong-api/src/test/java/gg/pingpong/api/admin/coin/controller/CoinPolicyAdminControllerTest.java, gg-recruit-api/build.gradle, gg-recruit-api/src/main/java/gg/recruit/api/TestController.java, gg-utils/build.gradle, gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java, settings.gradle
- api module 추가했습니다
- pingpong-api에서 recruit-api 의존하는 이유는 component scan관련해서 등록해야하기 때문에 추가했습니다
- devtools는 사용하면 편한거같아서 추가했습니다
- testcontroller로 잘 동작하는거 확인했고 dir업로드를 위해 지우지않고 올립니다
-
- #688
=> [FEAT] #688 api module add

gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java, gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminRoomListResDto.java, gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminRoomResDto.java, gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomResDto.java
- 어드민이 게시글을 전체 조회하는 API
- 게시글 작성자 intraid를 같이 response로 보낼 수 있게 작성
- 기존 게시글 전체 조회에 creator user id response dto에서 제거
- closed #692
=> ✨ [Feature] Admin 게시글 전체 조회 API

gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java, gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/request/PageReqDto.java, gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminRoomListResDto.java, gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java, gg-pingpong-api/src/main/java/gg/party/api/user/comment/controller/CommentController.java, gg-pingpong-api/src/main/java/gg/pingpong/api/global/dto/PageRequestDto.java, gg-repo/src/main/java/gg/repo/party/RoomRepository.java
- pagination기능 추가
- admin에서 방 전체 조회에 pagenation 기능 추가 및 dto 수정
-  closed #698
=> ✨ [Feature] admin 방 전체 조회 api pagination기능 추가

gg-data/src/main/java/gg/data/party/GameTemplate.java, gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/TemplateAdminController.java, gg-pingpong-api/src/main/java/gg/party/api/admin/templates/controller/request/TemplateAdminUpdateReqDto.java, gg-pingpong-api/src/main/java/gg/party/api/admin/templates/service/TemplateAdminService.java
- 탬플릿 수정 api
- 템플릿 Admin Controller 코드 추가
- 템플릿 Admin TemplateUpdateDto 추가
- 템플릿 Admin Service 코드 추가
- GameTemplate 엔티티 코드 추가
- closed #651
=> ✨ [Feature] 탬플릿 수정 API

gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/RoomAdminController.java, gg-pingpong-api/src/main/java/gg/party/api/admin/room/controller/response/AdminRoomDetailResDto.java, gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomAdminService.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/CommentResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/UserRoomResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java, gg-pingpong-api/src/main/java/gg/pingpong/api/user/noti/service/PartyNotiService.java, gg-pingpong-api/src/main/java/gg/pingpong/api/user/noti/service/sns/SlackPartybotService.java, gg-pingpong-api/src/main/java/gg/pingpong/api/user/noti/service/sns/SlackbotService.java
- 슬랙 초대하는 API 작성했습니다.
- 파티원이 전부 모이거나 host가 시작했을시에 슬랙 그룹 DM으로 초대해주는 기능 작성했습니다.
- 42gg봇이 나가도 다른사람이 DM메세지를 보낼경우 다시 기록이 남기때문에, 다음에 같은 인원이 시작할 경우 내역이 남아있는 방으로 초대되는것은 막을 수 없다고 판단했습니다. (유일한 해결방법은 게임시작한지 하루정도 지난 후 전부 강퇴하고 슬랙 봇이 나가는 기능을 구현하면 가능할 수 있을 것 같으나, 채팅방이 유지되길 바라는(하루가 지나도) 사람이 있을 수 있을 것 같아 폐지)
- 메세지는 비슷한 맥락을 유지하되 슬로건 및 URI은 차후 수정 예정입니다.
- SlackBotService에 같이 작성할 수 있었으나, 따로 작성한 이유는 차후 모듈화에서 분리할 수 있을까봐 따로 작성했습니다.
- Email까지 보내는건 슬랙 단체DM을 만들어주는 과정에서 너무 많은 알림을 막기 위함이었으며, 마찬가지로 알림의 불편함 때문에 댓글도 알림을 보내지 않기로 결정했습니다. (사용자가 파티에 참여한 후, 자기 할일 하다가 슬랙알림이 오면 play하는걸 의도) 차후 댓글기능이 채팅방의 기능을 할 경우 슬랙 댓글 알림을 추가할 예정입니다.
- 프론트의 요청으로 DTO 몇가지 수정했습니다.
- closed #720
=> ✨ [Feature] slack 초대 API

gg-data/src/main/java/gg/data/party/UserReport.java, gg-pingpong-api/src/main/java/gg/party/api/user/report/controller/ReportController.java, gg-pingpong-api/src/main/java/gg/party/api/user/report/service/ReportService.java, gg-repo/src/main/java/gg/repo/party/UserReportRepository.java, gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java, gg-utils/src/main/java/gg/utils/exception/party/UserAlreadyInRoom.java
- 노쇼 신고 API
- UserNotInRoom exception 클래스의 부모 클래스를 Runtimeexception 에서 Duplicateexception으로 변경
- close #647
=> 647 노쇼 신고 api

gg-data/src/main/java/gg/data/recruit/recruitment/Question.java, gg-data/src/main/java/gg/data/recruit/recruitment/Recruitments.java, gg-data/src/main/java/gg/data/recruit/recruitment/enums/InputType.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/RecruitmentController.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/CheckItemResDto.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/FormDetailResDto.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/response/RecruitmentDetailResDto.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/ApplicationService.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/QuestionService.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/RecruitmentService.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/CheckItemSvcDto.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/FormDetailSvcDto.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/response/RecruitmentDetailSvcDto.java, gg-recruit-api/src/test/java/gg/recruit/api/user/controller/RecruitmentControllerTest.java, gg-repo/src/main/java/gg/repo/recruit/user/application/ApplicationRepository.java, gg-repo/src/main/java/gg/repo/recruit/user/recruitment/CheckListRepository.java, gg-repo/src/main/java/gg/repo/recruit/user/recruitment/QuestionRepository.java, gg-repo/src/main/java/gg/repo/recruit/user/recruitment/RecruitmentRepository.java, gg-utils/src/main/java/gg/utils/exception/custom/NotExistException.java, gg-utils/src/testFixtures/java/gg/utils/RecruitMockData.java
- 공고 상세 조회 api 입니다.
- application Id 도 추가했습니다
- close #552
=> #552 feature 공고 상세 조회 api

gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswer.java, gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerCheckList.java, gg-data/src/main/java/gg/data/recruit/application/ApplicationAnswerText.java, gg-data/src/main/java/gg/data/recruit/recruitment/CheckList.java, gg-data/src/main/java/gg/data/recruit/recruitment/Question.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/ApplicationController.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/CheckListFormRequest.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/FormPatchRequestDto.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/FormRequest.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/request/TextFormRequest.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/ApplicationService.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/CheckListFormParam.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/FormParam.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/FormPatchParam.java, gg-recruit-api/src/main/java/gg/recruit/api/user/service/param/TextFormParam.java, gg-recruit-api/src/test/java/gg/recruit/api/user/RecruitMockData.java, gg-recruit-api/src/test/java/gg/recruit/api/user/controller/ApplicationControllerTest.java, gg-repo/src/main/java/gg/repo/recruit/user/application/ApplicationAnswerRepository.java, gg-repo/src/main/java/gg/repo/recruit/user/recruitment/CheckListRepository.java
- 지원서 수정 API입니다
- 테스트코드 아직 미추가
-
-
=> [FEAT] #557 patch application api

gg-admin-repo/src/main/java/gg/admin/repo/category/CategoryAdminRepository.java, gg-pingpong-api/src/main/java/gg/party/api/admin/category/controller/CategoryAdminController.java, gg-pingpong-api/src/main/java/gg/party/api/admin/category/controller/request/CategoryAddAdminReqDto.java, gg-pingpong-api/src/main/java/gg/party/api/admin/category/service/CategoryAdminService.java, gg-pingpong-api/src/test/java/gg/party/api/admin/category/CategoryAdminControllerTest.java, gg-utils/src/main/java/gg/utils/exception/ErrorCode.java, gg-utils/src/main/java/gg/utils/exception/party/DefaultCategoryNeedException.java, gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
- admin 유저가 카테고리를 추가하거나 제거하는 로직을 작성했습니다.
- 기존 서비스 로직에서 고정값으로 받던 defaultCategory를 name으로 검색("etc")으로 수정했습니다.(사유 : 처음 카테고리 생성시 defalut를 만들지 않으면 db에 접근해야함)
- 카테고리를 제거할때, defaultCategory로 바뀌는지 확인하는 로직도 추가했습니다.
- 400으로 오지 않는 exception을 수정했습니다.
- 400으로 오던 duplicate exception을 수정했습니다.
- 머지를 대비해 컨플릭트를 줄이기 위해 testUtills만 따로 수정
- closed #759
=> 🧪 [Test] Admin 카테고리 추가 및 제거 테스트 코드 작성

gg-pingpong-api/src/main/java/gg/party/api/admin/room/service/RoomStatusService.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomFindService.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java, gg-pingpong-api/src/test/java/gg/party/api/user/room/RoomControllerTest.java, gg-repo/src/main/java/gg/repo/party/RoomRepository.java, gg-utils/src/main/java/gg/utils/exception/party/RoomNotEnoughPeopleException.java, gg-utils/src/main/java/gg/utils/exception/party/RoomNotParticipantException.java
- 방 시작하기 및 참여하기에 있는 시작API 테스트코드 작성
- 방 시작하기 및 참여하기에 있는 시작API 테스트코드 작성
- [Bug] 마지막 사람이 나갈경우 방장이권이 되려시도하다 Null 접근하는 부분 수정
- [Bug] FINISH된 방 참여자가 IntraId 못보는 버그 수정
- [Bug] 스케줄러가 시간에 상관없이 START된 방을 FINISH로 만들던 버그 수정
- 방 상세조회 테스트케이스 및 RoomControllerTest 코드 리팩토링(반복문으로 수정)
- 방 시작하기 에러코드 다른 것 들 수정
- [Feature] 방 10개까지 조회하게 수정
- closed #751 
- closed #752 
- closed #766
=> 🧪 [Test] && 🐛 [Bug] 방 시작하기 및 참여하기에서 시작되는 부분 테스트 코드 작성 && 마감된 방 && Finish방 Intra조회

gg-pingpong-api/src/main/java/gg/party/api/user/category/controller/response/CategoryListResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/CommentResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/LeaveRoomResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomCreateResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomDetailResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomJoinResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomListResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/RoomStartResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/controller/response/UserRoomResDto.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomFindService.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomManagementService.java, gg-pingpong-api/src/main/java/gg/party/api/user/room/utils/GenerateRandomNickname.java, gg-pingpong-api/src/main/java/gg/party/api/user/template/controller/TemplateController.java, gg-pingpong-api/src/main/java/gg/party/api/user/template/controller/response/TemplateListResDto.java, gg-pingpong-api/src/main/java/gg/pingpong/api/user/noti/service/sns/SlackPartybotService.java, gg-repo/src/main/java/gg/repo/party/RoomRepository.java, gg-repo/src/main/java/gg/repo/party/UserRoomRepository.java
- report된 comment 조회되던 버그 수정
- db에 여러번 접근하던 코드 수정
- slack api 다른 res참조하던 버그 수정
- report된 comment 조회되던 버그 수정
- db에 여러번 접근하던 코드 수정
- slack api 다른 res참조하던 버그 수정
- exception 순서 맞게 수정
- dto에 protect 안되어있던거 수정
- 로직들 간소화
- #778 (리팩토링은 진행 중이라 닫지 않았습니다)
=> 🐛 [Bug] [Refactoring] 6기 Party 서비스 전체 리팩토링 중 찾은 버그들 수정

build.gradle, gg-admin-repo/src/main/java/gg/admin/repo/recruit/ApplicationAdminRepository.java, gg-admin-repo/src/test/java/gg/admin/repo/recruit/ApplicationAdminRepositoryTest.java, gg-data/src/main/java/gg/data/recruit/application/Application.java, gg-data/src/main/java/gg/data/recruit/application/enums/ApplicationStatus.java, gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java, gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/request/SetFinalApplicationStatusResultReqDto.java, gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java, gg-recruit-api/src/main/java/gg/recruit/api/admin/service/dto/UpdateApplicationStatusDto.java, gg-recruit-api/src/test/java/gg/recruit/api/WebMvcTestApplicationContext.java, gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentAdminControllerUnitTest.java, gg-recruit-api/src/test/java/gg/recruit/api/admin/controller/RecruitmentResultMessageAdminControllerUnitTest.java, gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceTest.java, gg-recruit-api/src/test/resources/application.yml, gg-utils/src/testFixtures/java/gg/utils/TestDataUtils.java
- 최종 결과 등록 api 입니다
- 최종 결과 등록 기능 작성 및 단위 테스트 추가
- 알림 기능은 멀티 모듈 사이클 이슈로 추후 구현
- gradle 의존성 오류 수정
- webMvcTest용 컨텍스트 구성
- #554
=> ✨ [Feature] 최종결과 등록

gg-pingpong-api/src/main/java/gg/pingpong/api/user/game/service/GameFindService.java, gg-pingpong-api/src/main/java/gg/pingpong/api/user/game/service/GameService.java, gg-pingpong-api/src/main/java/gg/pingpong/api/user/game/service/GameStatusService.java, gg-pingpong-api/src/test/java/gg/pingpong/api/user/game/service/GameFindServiceUnitTest.java, gg-pingpong-api/src/test/java/gg/pingpong/api/user/game/service/GameServiceUnitTest.java, gg-pingpong-api/src/test/java/gg/pingpong/api/user/game/service/GameStatusServiceUnitTest.java, gg-pingpong-api/src/test/java/gg/pingpong/api/user/game/service/PChangeServiceUnitTest.java
-Game unit test 중 일부 유닛 테스트 pr 입니다.
- GameFindService::`allGameListUser` 동적 할당 부분 추가
- `Arrays.asList(StatusType.END.name())` 는 동적 할당이 아니어서 add 하면 에러 발생
- `GameFindService` 유닛 테스트
- `PChangeService` 유닛 테스트
- `GameStatusServiceUnitTest` 추가
- `GameStatusService` javadoc 추가
-
- #627
=> 🧪 [Unit Test] Game unit test

gg-admin-repo/src/main/java/gg/admin/repo/recruit/RecruitmentAdminRepository.java, gg-data/src/main/java/gg/data/recruit/recruitment/Recruitment.java, gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/RecruitmentAdminController.java, gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentDto.java, gg-recruit-api/src/main/java/gg/recruit/api/admin/controller/response/RecruitmentsResponse.java, gg-recruit-api/src/main/java/gg/recruit/api/admin/service/RecruitmentAdminService.java, gg-recruit-api/src/main/java/gg/recruit/api/user/controller/RecruitmentController.java, gg-recruit-api/src/test/java/gg/recruit/api/admin/service/RecruitmentAdminServiceUnitTest.java
- 공고 전체 조회 API의 잘못된 응답에 대한 수정
- `status` -> `isFinish` 필드명 수정
- 공고 전체 조회시 삭제된 공고는 필터링하여 보내지 않도록 수정했습니다. (`isDeleted`가 true인 공고 필터링)
- `PageRequestDto`에 대해 valid 검사가 이루어지지 않아 500 에러 발생 가능했습니다. `@Valid` 추가했습니다.
=> 🐛 [Fix] 공고 전체 조회 API의 잘못된 응답 수정

gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaAdminRepository.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/AgendaAdminController.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/response/AgendaAdminResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/service/AgendaAdminService.java, gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/controller/AgendaAdminControllerTest.java, gg-agenda-api/src/test/java/gg/agenda/api/admin/agenda/service/AgendaAdminServiceTest.java, gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
- Admin Agenda 전체 조회 기능 (페이지네이션)
- Admin Agenda 전체 조회 기능 (페이지네이션)
- admin-repo 분리
- closed #886
=> ✨ [Feature] #886 Admin 대회 전체 조회하기

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaSimpleResDto.java
- Agenda isRanking 필드 추가
- Agenda isRanking 필드 추가
- closed #899
=> ✨ [Feature] Agenda isRanking 필드 추가 #899

gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileDetailsResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AgendaProfileInfoDetailsResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java, gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java, gg-repo/src/main/java/gg/repo/agenda/AgendaProfileRepository.java
-로그인 사용자 프로필 정보 조회 API (admin여부)
-로그인 사용자 프로필 정보 조회 API (admin여부)
-profile details조회시, intraId로 바꿈
- closed #912
=> ✨ [Feature] 로그인 사용자 프로필 정보 조회 API #912

gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaTeamAdminRepository.java, gg-admin-repo/src/main/java/gg/admin/repo/agenda/AgendaTeamProfileAdminRepository.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminController.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/request/AgendaTeamKeyReqDto.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaProfileResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamDetailResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminService.java, gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/controller/AgendaTeamAdminControllerTest.java, gg-agenda-api/src/test/java/gg/agenda/api/admin/agendateam/service/AgendaTeamAdminServiceTest.java, gg-utils/src/testFixtures/java/gg/utils/fixture/agenda/AgendaProfileFixture.java
- ✨ [Feature] Admin AgendaTeam 상세 조회하기
- Admin AgendaTeam 상세 조회하기
-
- closed #901
=> ✨ [Feature] Admin AgendaTeam 상세 조회하기 #901

gg-agenda-api/src/main/java/gg/agenda/api/admin/agenda/controller/request/AgendaAdminUpdateReqDto.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaCreateReqDto.java
- 🔨 [Refactoring] Agenda DateTimeFormat 변경 
- DateTimeFormat 변경
- 변경 전 : `@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")`
- 변경 후 : `@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)`
- `@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)`로 변경한 이유
- `@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)`인 경우 `@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")`를 포함하여 바인딩 가능
- `@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")`인 경우 테스트코드에서 추가적인 문자열 처리 필요
- closed #967
=> 🔨 [Refactoring] Agenda DateTimeFormat 변경 #967

gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamDetailResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/agendateam/controller/response/AgendaTeamResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/TicketAdminController.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/controller/request/TicketChangeAdminReqDto.java, gg-agenda-api/src/main/java/gg/agenda/api/admin/ticket/service/TicketAdminService.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaProfileController.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/AttendedAgendaListResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/CurrentAttendAgendaListResDto.java, gg-agenda-api/src/test/java/gg/agenda/api/admin/ticket/TicketAdminControllerTest.java, gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java, gg-data/src/main/java/gg/data/agenda/Ticket.java, gg-utils/src/main/java/gg/utils/exception/ErrorCode.java
-Admin 티켓 수정 API 
-datetime format 수정
-AgendaTeam Admin content 필드 추가(yhames)
-agendaprofile /info 주석 변경
-agendaprofile 내가 참여했던/참여중인 대회 response에 agenda key 추가
-Admin 티켓 수정 API 
-datetime format 수정
-AgendaTeam Admin content 필드 추가(yhames)
-agendaprofile /info 주석 변경
-agendaprofile 내가 참여했던/참여중인 대회 response에 agenda key 추가
- closed #946
=> ✨ [Feature] Admin 티켓 수정 API #946

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/response/AgendaResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/AgendaHostController.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/response/HostedAgendaResDto.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java, gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaHostControllerTest.java, gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java, gg-utils/src/testFixtures/java/gg/utils/AgendaTestDataUtils.java
- ✨ [Feature] 내가 개최한 대회 조회 API 기능 구현
- 개최한 대회 및 개최중인 대회 조회
- AgendaController 응답 DTO 이름 수정 (Contents -> Content)
- closed #952
=> ✨ [Feature] 내가 개최한 대회 조회 API 기능 구현 #952

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java, gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java, gg-repo/src/main/java/gg/repo/agenda/AgendaRepository.java
- 🔨 [Refactoring] Agenda History 조회시 CONFIRM 상태 추가 
- Agenda History 조회시 CONFIRM 상태 추가 
-
- closed #988
=> 🔨 [Refactoring] Agenda History 조회시 CONFIRM 상태 추가 #988

gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java, gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/service/AgendaService.java, gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/controller/AgendaControllerTest.java, gg-agenda-api/src/test/java/gg/agenda/api/user/agenda/service/AgendaServiceTest.java
- Open 아젠다 get DeadLine 오름차순으로 수정
- Confirm 아젠다 get DeadLine 오름차순으로 수정
- Finish 아젠다 get StartTime 오름차순으로 수정
- -closed #998
=> ✨ [Feature] Agenda 조회 전체 정렬 기준 수정 #998
